DataBiosphere/terra-workspace-manager

- build.gradle
Recently there were some stairway changes that overwrote the version that we were using in workspace manager. Some of the changes were breaking, so pinning to a self-published stable version for now until we can adopt the changes
> pin stairway to stable version

- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/resources/api/service_openapi.yaml
This adds new model objects to the OpenAPI document, but does not add any endpoints that use them. This doesn't add any useful functionality, but allows us to build multiple DataReference-based endpoints at the same time without merge conflicts.
The actual references are currently raw JSON strings with no schema specified, which we'll need to validate in the service itself. I'd like to use the `oneOf` operator (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) to validate them against one of several different schemas, but those don't work in the openapi-generator for spring-boot yet (see https://github.com/OpenAPITools/openapi-generator/issues/5381)
> Add DataReferenceDescription and ResourceDescription models to OpenAPI doc

- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/common/utils/SamUtils.java
- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/iam/SamService.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceStateStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlight.java
- src/main/resources/api/service_openapi.yaml
- src/main/resources/db/changesets/20200227_initial_schema.yaml
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Adds an endpoint to delete a workspace.
This uses Stairway, but `delete` seems like a weird operation for the Saga pattern - generally, it's really hard to undo partial deletes. It's also currently missing steps for planned but unimplemented features: deleting controlled resources with the Resource Manager library, notifying registered applications, and deleting policy objects in the Policy Manager.
> AS228 Delete Workspace

- config/deployment.yaml
- src/main/java/bio/terra/workspace/app/configuration/ApiResourceConfig.java
- src/main/resources/api/service_openapi.yaml
- src/main/resources/api/swagger-ui.html
A collection of small changes necessary to demo endpoints with swagger-ui. Some of these changes were used in the 4/3 demo, but I never checked them in (sorry!)
-Adds bearer token auth to swagger API
-Fixes missing swagger resources
-Adds dev backend to the SwaggerUI selection box
-Provides address of dev Sam. I don't know exactly how we plan to wire these together in the future and it'll probably change when Sam moves to K8s.
You can see a demo of this running in my testing environment at `http://34.71.179.202/zloery-terra-workspace-manager/api/swagger-ui.html`.
I haven't tested data reference endpoints, but basic workspace endpoints work correctly.
> Small cleanups before demo

- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/common/exception/DuplicateWorkspaceException.java
- src/main/java/bio/terra/workspace/common/exception/SamApiException.java
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/job/StairwayExceptionFields.java
- src/main/java/bio/terra/workspace/service/job/StairwayExceptionSerializer.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceCreateFlight.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This PR fixes the issue raised directly in AS-317 (WM not validating tokens before performing a createWorkspace SQL call) and also several issues that this uncovered. The full list of changes is:
-WM now authenticates with Sam to create an IAM object before creating a workspace in its own DB. This prevents unauthorized users from fishing for the existence of workspaces.
-WM now returns a user-friendly DuplicateWorkspaceException when an authorized user attempts to create a new Workspace with an ID that's already used, rather than directly returning an SQL error.
-WM now correctly uses the authentication token provided in the request body for create calls, rather than the token from the header. The token in the header is intended to validate that a request comes from the Folder Manager, …
> AS-317 Fix CreateWorkspace error serialization and auth before making SQL calls

- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
- src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
In the case of Rawls/TDR integration, the workspace created in WSM will fail because a Sam resource has always already been created for the workspace by Rawls.
If we test if the user isAuthorized to read the workspace, we can know whether or not the workspace exists (or whether the user should think it exists) and we can skip the resource creation step and avoid the conflict.
The original plan was to inspect the token passed in the header to see who is calling WSM, and if it was the rawls SA, we could skip this step. But the `userReq` doesn't contain enough information to know the email address of the user behind the request. This seemed like an appropriate alternative.
> Tolerate sam resource already existing

- README.md
Replace a TODO now that we have stable instances in multiple environments.
> Add README links to swagger-ui in various envs

- build.gradle
- src/main/java/bio/terra/workspace/mdc/MdcLogEnhancerFilter.java
- src/main/java/bio/terra/workspace/mdc/MdcResponseFilter.java
- src/main/resources/application.properties
Log messages will look something like:
```
2020-06-19 09:40:41.535 pn3N7J3M ERROR 17147 --- [nio-8080-exec-1] b.t.w.a.c.GlobalExceptionHandler         :    cause: bio.terra.workspace.common.exception.DuplicateWorkspaceException@2696eb2[causes=<null>,statusCode=400 BAD_REQUEST]
```
This does _not_ add the ID to anything that happens asynchronously within stairway. It will be added to the message that says the flight was launched, but no subsequent messages from within the flight.
> AS-368: Add Request-Id to every log message associated with an API call

- .github/workflows/dev_push.yml
- .github/workflows/integration-test.yml
- README.md
Before I merge this, I'll change the main branch in the repo config. The `dev` branch right now is a copy of `master`.
> rename master to dev

- .github/workflows/dev_push.yml
This [PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/56) changed the git and image tag syntax to [this](https://github.com/broadinstitute/terra-helmfile/blob/c9994a6923834ba05eac35274880b0c341d77550/versions.yaml#L18). I'm assuming y'all don't want that. The [tagging action](https://github.com/broadinstitute/github-tag-action) has a baked-in assumption that any branch that's not master is not a release branch and thus has this syntax. The variable I set should fix that by telling it that dev is a release branch.
> Fix tag syntax

- src/main/java/bio/terra/workspace/app/configuration/ApiResourceConfig.java
We deleted the entire ApiResourceConfig.java in a PR to use webjars and prevent UI caching, and then accidentally re-added the UI handling piece along with other functionality in that file.
> Remove webjar config that was accidentally re-added

- src/main/resources/application.properties
Revert the config flip used to re-create the DB.
I've validated that WM's db has been recreated, and dev Rawls no longer sees old invalid references.
> Revert "Set application properties to re-create DB schema."

- .gitignore
- DEVELOPMENT.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- local-dev/.gitignore
- workspace-manager-client/build.gradle
Compile is deprecated, more explicit ignoring.
Gitignore for Gradle from https://github.com/github/gitignore
> Tidy .gitignore and clean up deps

- build.gradle
This should fix caching for non-local versions of the swagger UI.
> real last-modified date for files in jib

- build.gradle
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This will require minor changes to update to the newest client library, but the new 0.1.1 server code is fully compatible with the existing 0.1.0 client library because serialized UUIDs and strings are interchangeable.
That means this will not break Rawls, but will require a small change to Rawls when it updates its dependency on the WM client library.
> Make workspaceId field of CreatedWorkspace a UUID instead of string

- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/datareference/utils/DataReferenceValidationUtils.java
- src/main/java/bio/terra/workspace/service/job/JobService.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This adopts TDR's existing naming standard for data reference names in Workspace Manager. The standard is 1-63 alphanumeric characters and underscores, with the first character not an underscore. To quote TDR:
> Dataset, table, and column names follow this pattern. This should be used for the name of any object in the
> system. It enforces BigQuery naming rules except it disallows a leading underscore so we avoid collisions with
> any extra columns the DR adds. For table names, this is shorter than what BigQuery allows.
By aligning on a standard, we eliminates a source of potential bugs. I chose TDR's existing standard for snapshots because we expect that in an e2e user journey, the name WM stores for a data reference to a snapshot will match TDR's name for that snapshot and will be …
> [AS-371] Adopt Data Repo's snapshot naming standard for data references

- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/java/bio/terra/workspace/integration/common/configuration/TestConfiguration.java
- src/test/resources/application-integration-test.properties
This adds an integration test which covers the flow of adding a reference to a Data Repo snapshot to a workspace. It does not create the referenced snapshot or dataset in Data Repo, and instead assumes that it persists as part of the dev environment. This pattern will need to be revisited if we ever test against non-dev environments of Data Repo.
> [AS-381] Add integration test for creating a reference to a Data Repo Snapshot

- build.gradle
- src/main/java/bio/terra/workspace/app/configuration/ApplicationConfiguration.java
- src/main/java/bio/terra/workspace/service/job/JobService.java
- src/main/resources/application.properties
- src/test/resources/application.properties
Made the following changes to be compatible with new Stairway version:
- Change Stairway constructor to use Builder pattern. Provided values are unchanged
- Places that caught StairwayExceptions now also catch InterruptedExceptions and treat them the same way
- Added a call to `recoverAndStart` as the third Stairway initialization step, as detailed in [Stairway code](https://github.com/DataBiosphere/stairway/blob/develop/src/main/java/bio/terra/stairway/Stairway.java#L244)
- Pulled `waitForFlight` into Workspace Manager instead of Stairway. The method was marked as deprecated in Stairway because it didn't work nicely with Stairway's new multi-instance functionality, but we don't use this new functionality.
- Changed polling time for stairway jobs from 10s to 1s, as all current WM Stairway …
> [AS-406] Update stairway version to 0.0.20

- src/main/java/bio/terra/workspace/common/exception/MDCHandlingException.java
- src/main/java/bio/terra/workspace/common/utils/MDCUtils.java
- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceFlight.java
- src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceStep.java
- src/main/java/bio/terra/workspace/service/datareference/flight/DataReferenceFlightMapKeys.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceStateStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceCreateFlight.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlight.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
MDC information is local to a thread, and Stairway does not execute flights on the same thread that submits the flights. Because of this, any work happening inside a Stairway flight couldn't be logged with the same MDC ID as the work happening outside the flight for the same request.
This PR stores MDC information in the input FlightMap for each of WM's three flights. Each step of these flights (in both directions) can then read and use this information. This allows us to use the same unique identifier for logging and tracing over a request's lifetime, even if that request is handled across multiple threads via Stairway.
This PR does not add MDC information to outbound requests (e.g. to Sam or Data Repo). That's still required to fully support MDC logging over the lifetime of a request …
> [AS-417] Store MDC info in Stairway FlightMaps

- .github/workflows/dev_push.yml
Use terra-helmfile's [new service-update workflow](https://github.com/broadinstitute/terra-helmfile/pull/101) to deploy the latest version of WSM to **`dev`** without automatically including it in the next Terra monolith release.
> DDO-545 Use new service-update workflow

- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Removes calls to Mockito's `doNothing` method, as that's already the default behavior for mocks.
The failing test consistently has an error about calling `doNothing` on a method with the wrong return type. This isn't the actual issue, but it makes me suspicious that the unnecessary calls to `doNothing` are causing problems. I don't know Mockito well enough to understand why this is happening, or why it's specific to one test.
Removing the calls seems to fix the flakiness. On the dev branch, I was seeing something like a 1% to 5% failure rate. After the changes, I saw ~600 consecutive successes over two days.
I don't think it's worth digging further into Mockito to understand this since it seems like the fix works and the failure rate was so low.
> [AS-468] Fix test flakiness

- build.gradle
list our Artifactory proxy to maven central before the real maven central, inside our gradle build.
I like this approach, since it affects anywhere our builds run, and our artifactory is internet-facing. An alternate approach is to leave the build.gradle as-is, but modify individual build/test scripts to override the repository settings. I like that less due to its complexity.
See https://www.jfrog.com/confluence/display/JFROG/Repository+Management#RepositoryManagement-RemoteRepositories for context
> use Broad proxy repo before maven central [no ticket; risk: low]

- src/main/resources/application.properties
Adds `terra-alpha` and `terra-staging` as valid Data Repo instances.
All WM requests to reference snapshots from data repo specify which instance they are calling. Because we currently have no tests or calls that run on the alpha or staging instances of Workspace Manager, this is the only change needed for AS-470.
> [AS-470] Add alpha and staging data repos as valid instances

- src/main/java/bio/terra/workspace/common/utils/BaseStatusService.java
- src/main/resources/api/service_openapi.yaml
This change allows callers to see which subsystems of WM are considered "critical" and which are not. Workspace Manager's overall status is defined as ok if all critical subsystems are ok. This change was brought up at a sprint review several months back, but never made it to a ticket.
Because this is an unauthenticated endpoint, I'm also going to explore using the new preview environments for this.
> Expose 'critical' field of subsystem status

- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
Adds a new integration test for listing references. I added two references to the same underlying snapshot so that we're not just getting a list of one element.
I also cleaned up the other data reference integration tests, since they all shared common code for creating data references.
> [AS-384] Add listReference integration test

- .github/workflows/preview-manage.yml
We now have a [build/release pipeline](https://github.com/DataBiosphere/github-actions#build-process) for building actions images so updating the workflow to use that. Should speed it up a decent amount.
> Pull pre-built action image instead of pointing at code

- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
Data Repo dev environment is having stability issues. Jade team needs to about two weeks to look into fixing it, so disabling automated integration tests that involve Data Repo. 
I've created a small task AS-506 to follow up on re-enabling the tests.
> Disable integration tests that talk to Data Repo

- src/main/java/bio/terra/workspace/db/DataReferenceDao.java
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/status/WorkspaceManagerStatusService.java
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
Inspired by comments in https://github.com/DataBiosphere/jade-data-repo/pull/641
Currently, we create a NamedParameterJdbcTemplate bean and never use it. Instead, our code re-creates the NamedParameterJdbcTemplate from the same input in several places in the code. This is unnecessary duplication, and we should use the common bean throughout the code.
> Properly use the JdbcTemplate bean

- src/main/java/bio/terra/workspace/common/utils/SamUtils.java
- src/main/java/bio/terra/workspace/service/job/JobService.java
Will's investigation into Workspace creation authz found a few Sam constants that aren't used (and aren't valid in Sam), as well as a "steward" check we forgot to remove. The check is never executed as we've temporarily disabled the `deleteJob` endpoint, but we should still remove it.
> Remove unused Sam resource types/actions

- build.gradle
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/workspace/CloudType.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceCloudContext.java
- src/main/resources/db/changelog.xml
- src/main/resources/db/changesets/20200227_initial_schema.yaml
- src/main/resources/db/changesets/20201016_fk_cloud_context.yaml
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
Add WorkspaceDao methods for working with the workspace_cloud_context table.
Define an intial JSON format for workspace_cloud_context.context. Initially, we're just storing a Google project id.
Change `Map<String, Object> paramMap` to the more descriptive `MapSqlParameterSource params` type.
Cloud context first used in follow up PR where we will create a google project as a part of workspace creation.
Also fix foreign key constraint on workspace_cloud_context. In the intial_schema, no `references: workspace(workspace_id)` was set. Compare to other FK constraints that are correct.
> PF-152 Add WorkspaceDao workspace_cloud_context methods

- src/main/java/bio/terra/workspace/db/DataReferenceDao.java
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
Do the same on a couple of test cases in WorkspaceDaoTest.
MapSqlParameterSource is a more descriptive type for these variables. This standardizes our JdbcTemplate parameter types.
> PF-152 Use MapSqlParameterSource instead of a raw Map for sql parameters in DataReferenceDao.

- render_config.sh
- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/java/bio/terra/workspace/integration/common/auth/AuthService.java
- src/test/java/bio/terra/workspace/integration/common/configuration/IntegrationTestConfiguration.java
- src/test/resources/application-integration-test.yml
Use the firecloud delegated service account to act as the test user in integration tests and use WM app service account to run WM application.
Previously, the common firecloud service account was used for both purposes.
Rename WorkspaceIntegrationTest config field names to make it clearer how they are used.
> PF-152 Use the WM service account and user delegated SA for integration tests correctly.

- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
Broken at head by the combination of renaming the method (https://github.com/DataBiosphere/terra-workspace-manager/pull/125/files) and new use of the method with the old name (https://github.com/DataBiosphere/terra-workspace-manager/pull/122).
> Fix new DataReference integration tests to use renamed testConfig.getUserEmail()

- .github/workflows/integration-test.yml
- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/resources/application-integration-test.yml
Currently, the integration test runs against the dev environment after the PR is merged, but before the new image is pushed to dev. This PR makes it so that the integration test for a PR is run against a local instance of the service with the PR changes.
Also change the integration test workflow to run on PRs as well as after merges to dev.
> [PF-199] Run integration test against localhost instead of dev

- build.gradle
- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/java/bio/terra/workspace/integration/common/utils/WorkspaceManagerTestClient.java
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This is a follow-on to broadinstitute/rawls#1298.
Highlights of this PR:
* for create- and delete-workspace, honor the auth token in the HTTP headers, and ignore any token sent in the request body
* in fact, remove the request-body token from the model definitions for the create- and delete-workspace API signatures
* since the token was the only member of the `DeleteWorkspaceRequestBody` class, remove that class entirely and define the delete API to not have a request body at all
* update all the runtime and test code to reflect these changes
Once these changes are in, we will publish a new workspace manager client lib, which we will adopt in Rawls in a future PR.
> AS-525: auth token in header for create- and delete-workspace [risk: low]

- src/main/java/bio/terra/workspace/service/job/JobService.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/test/java/bio/terra/workspace/common/BaseConnectedTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Add methods to WorkspaceService for creating and getting cloud context. Delete to follow. 
I'm ambivalent about adding these methods to WorkspaceService vs creating a CloudContextService. There's not much meat to them, but they cold be considered distinct. The WorkspaceService's workspace deletion flight will want to reference steps in the cloud context deletion service, so there will be cross package dependencies.
I would like to change the other tests in WorkspaceService to use its API instead of http endpoints in another PR.
Also removes a WorkspaceServiceTest `workspaceCreatedFromJobRequest` that duplicates `testGetExistingWorkspace` AFAICT.
> PF-155 Add service level methods for getting and creating google cloud context.

- .github/workflows/connected-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/unit-test.yml
- DEVELOPMENT.md
- local-dev/run_postgres.sh
This upgrades Postgres from 9.6 to 12.3 in our tests, local dev env setup, and README. 
See also broadinstitute/terraform-ap-modules#97
> AS-458: upgrade postgres from 9.6 to 12.3 [risk: low]

- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
The WorkspaceService test should test against the WorkspaceService's API, not the controller API. This is also much less verbose.
> Refactor WorkspaceServiceTest to use the WorkspaceService API instead of the HTTP controller endpoints

- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
[PR 133](https://github.com/DataBiosphere/terra-workspace-manager/pull/133) changed the interface of a method in workspaceService, but a new test was added using the old interface. Git didn't detect this as a merge conflict and all pre-merge tests passed, but the tests now fail to build.
> [PF-154] Fix test breakage in PR 133

- build.gradle
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/spendprofile/SpendProfileService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
Change WM representation of a "spend profile id" from a UUID to a String. As-is, WM is dictating that spend profile ids have to look like UUIDs, but WM should be agnostic to SPM's id format.
This does change the API and client library, but nobody other than our own tests are using the spend profile id fields on create/get workspace. This will also invalidate any outstanding Stairway create workspace flights with the spend profile id set, but we really don't have any of those since the field is never used.
I will update Rawls after this is merged and a new client is built.
(couple misc spotlessApply changes in this PR. My fault from previous commit.)
> PF-186 Update the API for spend profile ids to be strings instead of UUIDs.

- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/common/model/Workspace.java
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
This PR creates a new `Workspace` object for internal representation of workspaces and separates that internal representation from API objects. All changes happen at the Controller level and below, so this does not require an update to the client library.
This is the first of a few changes to apply this layering pattern across all of WM.
> Separate API objects from internal objects in WorkspaceService

- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/exceptions/MissingSpendProfileException.java
- src/main/java/bio/terra/workspace/service/workspace/exceptions/NoBillingAccountException.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlight.java
- src/main/java/bio/terra/workspace/service/workspace/flight/SetProjectBillingStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- src/test/java/bio/terra/workspace/service/spendprofile/SpendConnectedTestUtils.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
- src/test/resources/application-connected-test.yml
Check that a workspace has a valid spend profile id and that the user is authorized to link it before creating the google context. Set up that billing account on the project as a part of creating the google context. This allows the created project to spend money.
For now, only have tests with mocked sam spend link interaction.
> PF-186 Add spend authz check and billing account setup to create google context flight.

- src/main/java/bio/terra/workspace/common/utils/BaseStatusService.java
- src/main/resources/application.yml
- src/test/resources/application-test.yml
I think the Mockito flaky issue is due to the status service regularly (every 60s) calling the mocked Sam service. Mockito doesn't like concurrent modifications and calls to a mock (https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe). How mockito decides to fail seems up in the air.
Switch to `@Scheduled` cron to allow easily disabling of the scheduled function.
Flakiness first noticed from connected test run https://github.com/DataBiosphere/terra-workspace-manager/runs/1387146442?check_suite_focus=true. The failing test creates/deletes a project, taking minutes.
> Disable scheduled status checks in tests for Mockito flakiness.

- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceFlight.java
- src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceStep.java
- src/main/java/bio/terra/workspace/service/datareference/flight/GenerateReferenceIdStep.java
(These changes were originally in #142, I'm splitting them out here as the WorkspaceService-specific changes get more complex)
This PR makes changes related to the way we're using Stairway's working map. Working map updates are persisted at step boundaries, so the previous pattern of "set flag to false, perform action, set flag to true" within a single step did not work.
This breaks generating a data reference ID into a separate step, which allows us to handle undos more cleanly. Generating IDs as an early step in a flight is a best-practice when using Stairway.
This portion of the changes doesn't touch any objects in the interface layer, and so does not require an update to the client library.
> PF-227 Fix stairway working map interactions in DataReferenceService

- build.gradle
(This probably could have been part of #142)
Bump client library version after PR #142 added an optional new field to CreateWorkspaceRequest.
> [PF-227] Update client library version

- workspace-manager-clienttests/src/main/java/scripts/testscripts/GetWorkspace.java
Currently, the workspace creation request in the `GetWorkspace` client test always specifies the same value for `JobId`. This field is intended to deduplicate requests - by using the same value across multiple test runs, Workspace Manager is treating multiple workspace creation requests (with different IDs) as duplicates, which leads to unexpected return values.
This also cleans up explicitly setting SpendProfile to null, which is already the default value when unspecified.
> [no ticket] Remove unnecessary fields from GetWorkspace client test

- build.gradle
#164 added a new set of endpoints for WM's permissions API, we need to publish a new version of the client library with those endpoints available.
> [no ticket] Bump WM version to publish updated client library

- workspace-manager-clienttests/src/main/java/scripts/testscripts/GetWorkspace.java
- workspace-manager-clienttests/src/main/java/scripts/utils/WorkspaceManagerServiceUtils.java
- workspace-manager-clienttests/src/main/java/scripts/utils/WorkspaceTestScriptBase.java
Introduce a base TestScript class called `WorkspaceTestScriptBase`. This class takes care of
- obtaining a WorkspaceApi object
- basic logging
- assertions around common things (like nonempty user lists)
- checking HTTP codes
It currently only handles authenticated  tests.
I updated the `GetWorkspace` test script to use the new base class.
> shim test class

- workspace-manager-clienttests/src/main/java/scripts/testscripts/GetWorkspace.java
- workspace-manager-clienttests/src/main/java/scripts/utils/WorkspaceFixtureTestScriptBase.java
Frequently, we need to set up just one workspace and tear it down as part of a related test. This intermediate base class allows us to do this. With it, the `GetWorkspace` test script becomes a 2-liner.
> Base Class for tests with single workspace as a fixture

- src/main/java/bio/terra/workspace/service/workspace/exceptions/RetryableCrlException.java
- src/main/java/bio/terra/workspace/service/workspace/flight/GoogleCloudSyncStep.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/DataReferenceLifecycle.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/EnumerateDataReferences.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/ServiceStatus.java
- workspace-manager-clienttests/src/main/java/scripts/utils/ClientTestUtils.java
- workspace-manager-clienttests/src/main/java/scripts/utils/WorkspaceTestScriptBase.java
- workspace-manager-clienttests/src/main/resources/configs/BasicAuthenticated.json
- workspace-manager-clienttests/src/main/resources/configs/DataReferenceLifecycle.json
- workspace-manager-clienttests/src/main/resources/configs/EnumerateDataReferences.json
Create, read (two ways), and delete a data reference. Uses the new test-fixture version of the base class, which needs to be merged first. It's at #181.
> [PF-328] data reference enumeration test

- build.gradle
- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/service/workspace/exceptions/RetryableCrlException.java
- src/main/java/bio/terra/workspace/service/workspace/flight/GoogleCloudSyncStep.java
- src/main/resources/api/service_openapi.yaml
Currently, the `grantRole` endpoint is at `PUT /api/workspaces/v1/{id}/roles/{role}/members/{memberEmail}` and does not take a body. The swagger generated client (using Jersey2) enforces its own rules about HTTP requests and disallows PUT requests with an empty body, which means we can't call this endpoint from the client.
This changes PUT to POST, which may have empty request bodies.
As this is a change to the API, I've bumped the project version to 0.8.0 and will publish a new client library when this change is merged.
This also includes unrelated lint changes to `RetryableCrlException` and `GoogleCloudSyncStep` because I pushed without linting in #172. Sorry!
> [PF-356] Move memberEmail to request body for grantRole

- build.gradle
- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/resources/api/service_openapi.yaml
Previously in #184, I changed the `grantRole` endpoint from PUT to POST, leaving all parameters in the URL. This is allowed by both the server and client, but GCP automatically rejects POST requests without a `Content-length` header (which Jersey does not include for empty bodies).
This change moves the `memberEmail` parameter from the URL to the request body for `grantRole`. The `removeRole` endpoint is unchanged, as DELETE requests should not have bodies.
From an API design standpoint this makes the most sense to me: we are adding one member to a role's collection of members. This endpoint is not creating a new role, so I did not want to move role to the request body.
While this does mean our POST and DELETE endpoints are no longer symmetrical, this is the same approach we've taken for …
> [PF-356] Move memberEmail from url to request body on grantRole endpoint

- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/exceptions/DuplicateGoogleContextException.java
- src/main/resources/api/service_openapi.yaml
Currently, making a call to create a google context on a workspace which already has one will result in partially executing the stairway flight (including allocating a new GCP project) before failing (and deleting the new GCP project). This is a waste of time and projects, and we can avoid it and provide a more useful error code with a simple check.
> [PF-363] Handle calls to create duplicate context better

- src/main/java/bio/terra/workspace/common/exception/ForbiddenException.java
- src/main/java/bio/terra/workspace/common/exception/SamUnauthorizedException.java
- src/main/java/bio/terra/workspace/service/buffer/exception/BufferServiceAuthorizationException.java
- src/main/java/bio/terra/workspace/service/datareference/exception/DataRepoAuthorizationException.java
- src/main/java/bio/terra/workspace/service/job/exception/JobUnauthorizedException.java
- src/main/java/bio/terra/workspace/service/spendprofile/exceptions/SpendUnauthorizedException.java
- src/main/resources/api/service_openapi.yaml
Currently, lots of things in WM return an HTTP 401 response to indicate a user does not have permission for an action. Technically [401 means authentication info is missing or unreadable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) while [403 means permission is denied](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403). 
Note that Sam does not distinguish between "resource not found" and "permission denied" in calls to its `resourcePermission` endpoint. While WM does not explicitly need to hide this difference, it uses that endpoint to check permissions. Because WM cannot distinguish between 403 and 404 responses from Sam, WM will return 403 in this case, with an error message indicating either case is possible.
> [PF-372] Change 401 responses to 403

- src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
Add a notebooks admin role for workspace owners and writers for the Enterprise alpha. When we introduce controlled resources for notebooks, we will revise the permissions. This initial role allows users to demo notebooks.
> PF-341 Temporarily add 'roles/notebooks.admin' for workspace owners and writers

- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/iam/SamService.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This would eliminate the need for broadinstitute/rawls#1347.
In this PR, we change workspace- and data reference-related APIs, which all operate in the context of a single workspace, to always return a 404 if the workspace doesn't exist. It still returns a 403 if the workspace exists but you don't have permission; and returns an appropriate code (generally 200/204) if you do have permission.
In the case of 403,  it changes the error message from "User %s is not authorized to %s workspace %s or it does not exist" to "User %s is not authorized to %s workspace %s". 
For those who haven't followed all the conversation, we realize the 403/404 differentiation leaks existence of a workspace to those who don't have permission to see it. Because Workspace Manager is a low-level service, this is …
> AS-592: return 404 from workspace-specific APIs if the workspace doesn't exist [risk: low]

- src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
Changed the allowed permissions for a workspace WRITER and OWNER from storage.objectAdmin -> storage.admin. This will allow the CLI to create buckets, until the WSM controlled resource API for buckets is available.
Thanks to @gjuggler for finding this fix!
> PF-422: Temporarily expand workspace user storage permissions.

- src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
This role enables all owners and writers to "use" any service account in the project.
This is a temporary measure to enable AI Notebooks while we build APIs for controlled service accounts. Until then, to create AI Notebooks, a user needs to have the user role on a service account.
> PF-338 Add the service account user role temporarily for owners & writers

- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/db/DataReferenceDao.java
- src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- src/main/java/bio/terra/workspace/service/buffer/BufferService.java
- src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
- src/main/java/bio/terra/workspace/service/datareference/model/DataReferenceType.java
- src/main/java/bio/terra/workspace/service/datareference/model/ReferenceObject.java
- src/main/java/bio/terra/workspace/service/datareference/model/SnapshotReference.java
- src/main/java/bio/terra/workspace/service/datarepo/DataRepoService.java
- src/main/java/bio/terra/workspace/service/iam/SamService.java
- src/main/java/bio/terra/workspace/service/job/JobService.java
- src/main/java/bio/terra/workspace/service/migrate/MigrateService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/SyncSamGroupsStep.java
- src/test/java/bio/terra/workspace/common/BaseStatusServiceTest.java
- src/test/java/bio/terra/workspace/common/utils/MdcHookTest.java
- src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
- src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java
- src/test/java/bio/terra/workspace/service/datareference/DataRepoServiceTest.java
- src/test/java/bio/terra/workspace/service/datareference/model/ReferenceObjectTest.java
- src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileServiceTest.java
- src/test/java/bio/terra/workspace/service/status/WorkspaceManagerStatusServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
- removed `String.format` nested in a logger
- fixed a javadoc tag (`@Code` -> `@code`)
- normalized tests
- removed `public`, matching JUnit docs
- removed some unthrown exceptions
- also added a bit of nesting, so **better reviewed with whitespace hidden**
> Tidy up [post- AS-512]

- src/main/java/bio/terra/workspace/app/configuration/external/BufferServiceConfiguration.java
- src/main/java/bio/terra/workspace/service/status/WorkspaceManagerStatusService.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/exceptions/BufferServiceDisabledException.java
- src/test/resources/application-test.yml
This re-adds the `workspace.buffer.enabled` flag that was removed in #215, and checks that it is true before adding Buffer Service as a dependency to check for WSM's status endpoint.
Without this check, WSM's status endpoint is broken in environments where it does not have a Buffer service configuration. With this change those environments still will not have access to Buffer Service functionality, but this is acceptable as it is gated behind the workspace stage feature flag.
This change depends on a [corresponding Helm change](https://github.com/broadinstitute/terra-helm/pull/293) to actually provide this configuration value. In any environment where it is not provided, it will default to `false` and WSM's status endpoint will not depend on Buffer service.
> [PF-457] Only depend on Buffer Service status if Buffer Service integration is enabled

- src/main/java/bio/terra/workspace/common/utils/BaseStatusService.java
This adds a warning level log message when WSM has a non-ok status with information about which dependencies have issues, as this information is otherwise inaccessible. This message is logged when WSM checks its dependencies (once per minute), not when the `/status` endpoint is called.
> [PF-480] Add logging when WSM dependencies are not healthy

- src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
Add the serviceusage.serviceUsageConsumer role to workspace owners and writers.
The goal of this change is to resolve the 403 error I get when trying run a Nextflow workflow inside a workspace project.
`"pet-110017243614237806241@terra-wsm-test-8a063ae7.iam.gserviceaccount.com does not have serviceusage.services.use access to the Google Cloud project."`
The roles that [GCP says to use](https://cloud.google.com/life-sciences/docs/tutorials/nextflow#create_a_service_account_and_add_roles) for running Nextflow are:
1. Cloud Life Sciences Workflows Runner = roles/lifesciences.workflowsRunner
This has the same permissions as roles/lifesciences.editor, which is already granted.
2. Service Account User = roles/iam.serviceAccountUser
This was already granted for AIP notebooks, per the comment in …
> PF-421: Add serviceusage.serviceUsageConsumer role.

- .github/workflows/test.yml
No ticket because this only affects test infrastructure.
Currently, when a test run fails the GHA workflow will skip steps after "run tests", and so the test report is not uploaded. We should always make the test report available to make debugging failed tests easier.
> [No ticket] Always upload test results on failure

- .github/workflows/test-runner-nightly-integration.yml
- .github/workflows/test-runner-pr-integration.yml
The current setup for TestRunner integration tests runs on commits to a PR and builds a local client, but runs against the `wsmtest` environment server, meaning server-side changes are not captured in these PR checks. They also don't run nightly like the perf tests, which we want.
This change switches the existing `test-runner-nightly-integration` action to run the nightly integration tests in the wsmtest environment. It also switches to using the currently specified version of the client library, rather than building a client with potentially unpublished changes from head. The tests will run at 7 AM UTC since the perf tests also use the `wsmtest` environment and run at 6 AM UTC.
Additionally, I added a new `test-runner-pr-integration` action. On push to a PR, this action will run client …
> [PF-306] Add nightly integration tests, make client tests run locally

- .github/workflows/test-runner-pr-integration.yml
On merging #241, I discovered that `description` isn't actually a valid field for a workflow. This change moves the description to a comment instead. Sorry for the churn!
> [PF-306] Fix invalid description field in GHA workflow

- build.gradle
We need to publish a new version of the client library for the new `listWorkspaces` endpoint added in #251, but I forgot to bump the app version in that PR. sorry!
> [PF-530] Bump version and publish new client library

- .github/workflows/test-runner-pr-integration.yml
- .github/workflows/test.yml
- DEVELOPMENT.md
- local-dev/run_postgres.sh
Update tests, readme, and local-dev script to use Postgres 13 instead of 12. This reflects our production deployment.
> postgres 12->13 [AS-650]

- src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- src/main/java/bio/terra/workspace/service/job/JobService.java
- src/main/java/bio/terra/workspace/service/job/exception/InvalidJobIdException.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
The `jobId` field, part of the create-workspace request, is too easy for an end user to get wrong by specifying the empty string.
to use a system-generated jobid, the caller must omit the jobId entirely:
```
{
"id": "123e4567-e89b-12d3-a456-426614174000",
"stage": "RAWLS_WORKSPACE"
}
```
but a common mistake is to leave the jobId key in the payload but blank out its value:
```
{
"id": "123e4567-e89b-12d3-a456-426614174000",
"jobId": "",
"stage": "RAWLS_WORKSPACE"
}
```
which could result in many jobs attempting to have the same jobId of "", leading to conflicts.
This PR changes the behavior to validate that iif a caller specifies a jobId, its value is not the empty string nor is whitespace-only. This validation happens fairly low in `JobService`, so it affects any code using `JobService`, …
> jobid should not be empty string/whitespace [AS-679]

- .github/workflows/test.yml
- src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
add Slack notifications to #dsde-qa, using https://github.com/broadinstitute/action-slack. Code shamelessly copied from data repo.
Tested by manually changing the `if:` clause in the job to `if: always()` and seeing the notifications arrive in #dsde-qa. The [Jenkins job](https://fc-jenkins.dsp-techops.broadinstitute.org/job/workspacemanager-integration-test-trigger/configure) that triggers the alpha and staging tests is hardcoded to use the `dev` branch of this repo, so I can't test the real thing easily; I don't want to edit the Jenkins job.
if you don't like the :mariostar: emoji I can change that :)
> slack notifications for alpha/staging tests [AS-694]

- .github/workflows/test.yml
Follow-on PR to #264 to tweak the contents of the Slack notifications. The notifications are working correctly, but I thought they could be more informative. This PR:
* Changes the author from the totally unhelpful "8398a7@action-slack" to "Workspace Manager ${ENV} (unitTest|connectedTest|integrationTest)"
* Changes the username to include the environment - from "Workspace Manager tests" to "Workspace Manager ${ENV} tests"
After:
Before:
> tweak username and author_name for Slack notifications [AS-694]

- HOTFIX.md
- README.md
I think the original ticket suggests to copy the HOTFIX.md file into this repo but I would rather defer to the common documentation in the terra-helmfile repo since I have a feeling that it's more likely to be kept up to date. I don't think the WSM process is different than what's in terra-helmfile, anyway.
I'm open to discussing disagreements :)
> AS-695: Document hotfix procedure

- build.gradle
Change the logging level for the profiler agent to be less spammy. Ref https://cloud.google.com/profiler/docs/profiling-java#agent_logging
> PF-618 Only log errors and fatal from the cloud profiler agent.

- src/main/java/bio/terra/workspace/common/exception/ErrorReportException.java
While many of the ErrorReportException's constructors have default HttpStatus values, the constructors that explicitly take a  HttpStatus allow the value to be null. Change these constructors so that HttpStatus is never null.
When there's a non http-status Sam ApiException, Stairway serialization of the wrapping ErrorReportException fails because it expects a non-null statusCode. 
https://github.com/DataBiosphere/terra-workspace-manager/blob/894e24101da748254297a95fbb30cd29a24c3053/src/main/java/bio/terra/workspace/service/job/StairwayExceptionSerializer.java#L45
Do a similar change with causes so that the default value for the collection is an empty list instead of null so that clients can skip a null check.
I will also make the corresponding change in terra-common-libs.
> PF-621 Make ErrorReportException status and causes always have non-null values.

- src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateGcsBucketStep.java
- src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteControlledResourceGcsBucketFlight.java
- src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- src/main/java/bio/terra/workspace/service/resource/referenced/flight/create/CreateReferenceMetadataStep.java
- src/main/java/bio/terra/workspace/service/resource/referenced/flight/create/CreateReferenceResourceFlight.java
- src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CheckSamWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteGcpContextStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteProjectStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceAuthzStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceStateStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/StoreGcpContextStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/SyncSamGroupsStep.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceCreateFlight.java
- src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlight.java
- src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
Currently, WSM serializes UUIDs and enums directly to Stairway flightmaps. This works fine normally, but causes issues when flights are dropped and recovered. As a short-term workaround, I've moved all direct serialization of enums and final classes (currently just UUID) to Strings instead. In the longer term, there's more work to be done on Stairway ser/des.
> [PF-641] Serialize UUID and enums as strings in flightmap

- src/test/resources/application-test.yml
(No ticket, this only affects test configuration)
This points WSM tests (currently just connected tests) to a newer pool from RBS. The old v3 pool was deleted recently ([see PR](https://github.com/DataBiosphere/terra-resource-buffer/pull/141)), and all sources should use the new v6 pool instead.
> [no ticket] Bump WSM tests to use newer RBS pool

- DEVELOPMENT.md
- README.md
- workspace-manager-clienttests/README.md
Updating documentation on how to publish new versions of the WSM client library
> [PF-597] Update client library publishing documentation

- src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateGcsBucketStep.java
- src/main/resources/api/service_openapi.yaml
- src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
I erroneously used a type that didn't support exact time or time zones due to misreading an example or some other documentation.
> PF-614: use date-time instead of date

- src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
Creating controlled buckets requires its own set of parameters (`ApiGcpGcsBucketCreationParameters`). Other controlled resource types will have their own creation parameters. Rather than trying to make a single "create controlled resource" function on ControlledResourceService, make creating buckets its own method, paving the way for adding other resource overloads.
This matches the bucket specific method for deletion.
I'd like to make this tiny change to avoid further merge conflicts on AI notebook instances & bigQuery data set controlled resources.
> PF-469 Give controlled bucket creation its own method on ControlledResourceService.

- src/main/java/bio/terra/workspace/app/Main.java
- src/main/java/bio/terra/workspace/common/utils/BaseStatusService.java
- src/main/java/bio/terra/workspace/service/status/WorkspaceManagerStatusService.java
- src/main/resources/application.yml
This is a small PR to try to address the likely issues with the stuck /status endpoint. I made two changes:
1. Put a timeout on the database connection check
2. Allocate a single thread scheduled executor just for the status check.
In thinking about the problem, I realized I want to understand why we are bothering doing all of this. I wrote [Status Checking Reconsidered](https://docs.google.com/document/d/1UqEZ0UsnSvv0E_bWfMuSYAZiCQFVIgNUDmWIGHNXxG0/edit#heading=h.jl83h28nja15l)
When MC Terra Arch Council has figured out the system level view, we can come back to elaborating or eliminating this endpoint. In the meantime, I am hoping this will get us by!
> PF-669 Minimal fix for status endpoint

- src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateControlledResourceFlight.java
I read the comments and then forgot to actually change the RetryRule to not be a static instance...
> PF-469 Fix gcp notebook retry rule to not be re-used across flights.

- build.gradle
- workspace-manager-clienttests/build.gradle
Small change to update WSM version and publish an updated client library with the "create controlled BQ dataset" endpoint available (#307). I had originally planned to publish once delete/update/get were also available, but making this available now is easier for CLI development.
> [PF-418] Update version and publish new client

- src/main/resources/application.yml
- src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/CreateGetDeleteControlledGcsBucket.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- workspace-manager-clienttests/src/main/resources/configs/integration/CreateGetDeleteControlledGcsBucket.json
- workspace-manager-clienttests/src/main/resources/configs/integration/PrivateControlledGcsBucketLifecycle.json
- workspace-manager-clienttests/src/main/resources/configs/perf/BasicAuthenticated.json
- workspace-manager-clienttests/src/main/resources/configs/perf/DataReferenceLifecycle.json
- workspace-manager-clienttests/src/main/resources/configs/perf/EnumerateDataReferences.json
- workspace-manager-clienttests/src/main/resources/configs/perf/GetRoles.json
- workspace-manager-clienttests/src/main/resources/testusers/liam.json
- workspace-manager-clienttests/src/main/resources/testusers/neville.json
A number of controlled resource related client tests do not run regularly through GitHub actions, and they've been broken by other changes recently. This PR fixes the following:
- Adds a new user, `liam`. This is to replace `neville`, who is no longer listed in Sam.
- Adds a spendprofile parameter to the perf tests which need it. These tests have been failing since creation due to this missing parameter.
- Refactors `PrivateControlledGcsBucketLifecycle` to reflect the requirement that users assign private resources to themselves. Previously, this test had a workspace owner assign a resource to a workspace reader.
> [PF-638] Fix broken client tests for controlled resources

- src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/notebook/CreateAiNotebookInstanceStep.java
- src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- src/test/java/bio/terra/workspace/service/resource/controlled/flight/create/notebook/CreateAiNotebookInstanceStepTest.java
For some reason git secrets has a false positive for the string 'service_account' when it is in double quotes, `"like_this"`. 
The only pattern that looks related is `secrets.patterns ("type": "service_account"|"privateKeyType": "TYPE_GOOGLE_CREDENTIALS_FILE",)` but this doesn't have the type.
This is mysterious, but not especially hard to avoid.
> PF-734 Avoid " around 'service_account' for git secrets false positives

- workspace-manager-clienttests/src/main/java/scripts/testscripts/DataReferenceLifecycle.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/EnumerateDataReferences.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/EnumerateResources.java
- workspace-manager-clienttests/src/main/java/scripts/utils/ClientTestUtils.java
- workspace-manager-clienttests/src/main/java/scripts/utils/DataRepoTestScriptBase.java
- workspace-manager-clienttests/src/main/java/scripts/utils/ResourceMaker.java
- workspace-manager-clienttests/src/main/resources/configs/integration/DataReferenceLifecycle.json
- workspace-manager-clienttests/src/main/resources/configs/integration/EnumerateDataReferences.json
- workspace-manager-clienttests/src/main/resources/configs/integration/EnumerateResources.json
This is the first PR (more iterations to come) for migrating WSM integration tests form JUnit to TestRunner. I'm breaking the work down into different PR's in order to get early feedback and also make the changes easier to review.
This PR:
- Parameterizes the arguments used in creating data references
- Creates a base test script (`DataRepoTestScriptBase.java`) that's tailored towards tests that work with data references
- Moves the data references util code from `ClientTestUtils.java` to `DataRepoTestScriptBase.java`
- Updates related files/tests
The next set of PRs will address running the tests in other environments, and updating the GitHub workflows accordingly.
> AS-723 - (First Pass) Migrate WSM integration tests from JUnit to TestRunner

- src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleMapping.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- workspace-manager-clienttests/src/main/java/scripts/testscripts/EnumerateResources.java
- workspace-manager-clienttests/src/main/java/scripts/utils/ClientTestUtils.java
- workspace-manager-clienttests/src/main/java/scripts/utils/ResourceMaker.java
- workspace-manager-clienttests/src/main/resources/configs/integration/ControlledBigQueryDatasetLifecycle.json
- workspace-manager-clienttests/src/main/resources/configs/integration/ControlledGcsBucketLifecycle.json
- workspace-manager-clienttests/src/main/resources/suites/FullIntegration.json
This change adds client testing to cover the new endpoints for controlled BigQuery datasets. It also modifies the existing EnumerateResources test to include controlled BigQuery datasets. While looking at the equivalent test for GCS buckets, I also renamed the test to be more consistent.
I've also added `bigquery.tables.get` permission to our custom BigQuery READER role. We already included `bigquery.tables.list`, and leaving `get` out was a small oversight.
> [PF-728] Add BQ dataset client tests, fix reader permissions

- src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateGcsBucketStepTest.java
Reports of flakkiness when unit tests are run simultaneously in the same DB point to the bucket name uniqueness check. Hence, using unique bucket names everywhere.
> replace static fixtures with methods that generate unique bucket names

- src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- src/test/resources/application-connected-test.yml
- src/test/resources/application-integration-test.yml
`william.thunderlord@test.firecloud.org` has problems getting more GCP permissions. Avoid using him in connected tests and leave a TODO for the integration tests that are being ported in AS-723.
More details on william.thunderlord's affliction in PF-746.
It is not simple to remove him everywhere because he has special Data Repo permissions not given to all test users. I'm doing a limited change at this time for the kinds of tests that he currently breaks.
> PF-746 Avoid william.thunderlord as the test user in connected tests.

- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
Expected value should come first. In almost all cases it's clear which is which. It might  be good to have another set of eyes search for "assertEquals" and scan for anomalies.
> [PF-772] assertEquals argument order

- integration/src/main/resources/configs/perf/DataReferenceLifecycle.json
- integration/src/main/resources/configs/perf/EnumerateDataReferences.json
This PR fixes the snapshot-related error in perf tests
`java.lang.IllegalArgumentException: Must provide Spend Profile ID, Data Repo snapshot ID, and Data Repo Instance Name in the parameters list`
> Add data reference info in perf config files

- service/build.gradle
- service/gradle.lockfile
Bump CRL dependencies to more recent versions to include shared guava and google dependency updates.
> PF-774 Bump CRL dependencies

- .github/workflows/workflow-tester.yml
You cannot run a workflow that is on a branch unless the workflow already exists in the default branch.
So here is a test workflow that is manually triggered that we can use for testing workflows.
In particular, I will use it for testing the database cleaning.
> PF-730 prework - add workflow tester

- .github/workflows/release-promotion-tests.yml
- integration/src/main/resources/suites/dev/FullIntegration.json
Create dedicated test suite for dev environment. I had set it up earlier to use the [generic test suite](https://github.com/DataBiosphere/terra-workspace-manager/blob/dev/integration/src/main/resources/suites/FullIntegration.json) which is more targeted towards wsmtest environment.
This provides consistency by running the same tests that we run on alpha and staging during release promotion.
> AS-723 follow-up: Create integration suite for dev env

- .github/workflows/release-promotion-tests.yml
- .github/workflows/test.yml
- service/src/test/java/bio/terra/workspace/common/BaseConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/status/WorkspaceManagerStatusServiceTest.java
Whether we should even run this test is being tracked separate in [AS-789](https://broadworkbench.atlassian.net/browse/AS-789?atlOrigin=eyJpIjoiNDlkYmZjNzY0NjIwNGMwYzk3MDE3MzIxYzM5MDk3ODkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
This change makes the dev environment work in the same was as the alpha and staging environments.
There are three small fixes:
1. Add `dev` to the environments that skip tests that require Buffer/Janitor configuration
2. Change workflow logic so `alpha` and `staging` results will always get reported to QA via slack
3. Set the `write-config` to be `local` always for these tests, since they always are running against a local WSM service and local postgres.
> [PF-826] Fix test.yml when run with dev environment

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
This change will make WSM stop granting most project level permissions for GCS buckets and BigQuery datasets in new projects. The major exception is `roles/bigquery.jobUser`. This grants permission to run BigQuery jobs, which was previously included with `roles/viewer`. This role must be granted at the project level, rather than the individual dataset level.
Removing `roles/viewer` will remove a ton of over-granted permissions across GCP. All controlled resources have appropriate READER roles and I think the remaining lifescience and serviceusage roles should cover existing usecases, but we should keep an eye out if this causes unexpected breakage for users.
As always there is no backfill mechanism, so users in existing projects will still be overpermissioned.
Leaving this as a draft …
> [PF-633][PF-735] Remove bucket and BQ project level permissions

- .github/workflows/test.yml
- service/build.gradle
Add envvar control of printing standard streams during tests; enabled it in test workflow
> [PF-842] Test log control

- client/build.gradle
We have been publishing the client to the wrong place ever since I re-org's the build.
The reason is that the `artifactId` is taken by default from the project name. I changed the project name to `client`.
This change explicitly sets the artifactId which, the docs say, will do the right thing.
The only way I can think of to test this is to do a tag-publish action on the branch. If that works, I then merge right away and get a proper tag-publish on the mainline.
> [PF-853] Explicitly set the artifact id for publishing

- service/local-dev/skaffold.yaml.template
- service/src/main/java/bio/terra/workspace/app/StartupInitializer.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerUtils.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/update/UpdateControlledGcsBucketResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/update/UpdateGcsBucketStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceStateStep.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/main/resources/application.yml
This change fixes issues with WSM's asynchronous endpoints:
- By design, the async endpoints (and their polling endpoints) were supposed to return 202 for "job still running" and 200 for "job finished", with a more informative code inside the JobReport of the response body. As written, the endpoint copied the status from the JobReport, and the JobReport status was incorrectly either 202 or 200 (even for failed jobs, when it should have been 4xx or 5xx).
- A utility for building result URLs had parameters switched and was missing the scheme, so the provided URLs were incorrect. This change fixes the utility, so that the `resultURL` field of all JobReports WSM returns now point to valid endpoints.
- Unrelated to async endpoints,  but I also fixed some findbugs warnings and updated the …
> [PF-732] Fix async endpoints

- integration/build.gradle
- integration/gradle.lockfile
- integration/src/main/resources/configs/resiliency/DeleteInitialPods.json
Bump TestRunner version to 0.0.6-SNAPSHOT to fix intermittent NPE issue in resiliency tests.
For more information, please refer to this PR as well: [https://github.com/DataBiosphere/terra-test-runner/pull/17](https://github.com/DataBiosphere/terra-test-runner/pull/17)
> QA-1504: Fix intermittent NPE in resiliency test.

- service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
A notebook instance id can contain lowercase letters, digits, and dashes. Fixed error message that swapped underscore with dash.
> [no ticket] Swap underscore for dash in notebook instance id validation.

- integration/build.gradle
- integration/gradle.lockfile
Bump the Test Runner library version. Details of the fixes that went into this version bump are in the [Test Runner PR](https://github.com/DataBiosphere/terra-test-runner/pull/18).
> PF-861: Bump test runner to 0.0.7

- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
Ignore case when validating a private resource user email. Came across this when writing CLI tests for private resources.
> PF-871: Ignore case in private resource user email.

- service/src/main/java/bio/terra/workspace/service/resource/controlled/GcsApiConversions.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/GcsApiConversionsTest.java
This adds support for a few GCS lifecycle rules that were previously included in WSM's API but not propagated to GCP due to versioning issues with the GCS library. The newly supported lifecycle conditions are:
- noncurrentTimeBefore
- daysSinceCustomTime
- daysSinceNoncurrentTime
- customTimeBefore
This did not require updating the version of CRL that WSM was using - I think that update happened sometime between when the bug was filed and now, though we didn't add support inside WSM.
> [PF-506] Add omitted GCS lifecycle conditions to WSM

- .github/actions/bump-skip/action.yml
- .github/workflows/tag-publish.yml
- .github/workflows/test.yml
Skip the test workflow and the tag-publish workflow if the push to dev commit message is `"^bump .*"`. This will save a complete, redundant test pass and tag computation when merging code.
I added a composite action, `bump-skip`, that performs the check and sets an output. Then each following step includes an `if:` that checks against that output.
There is no "exit at this point" logic in github actions, so the `if:` approach is the recommended solution. An alternative is to use sequential jobs and put the `if:` at the job level. However, that would mean two separate checkouts, so the step level seemed like the more straightforward approach.
> [PF-749] fix tag publish

- service/src/main/resources/application.yml
Update the default RBS project pool id to `workspace_manager_v8` instead of the previous `workspace_manager_v6`.
The new pool does not delete the default compute engine service account or the default VPC network. This was to support Nextflow, which required both of these things. Now there is a Nextflow edge release that allows overriding both defaults.
I've tested this against my personal environment WSM and updated CLI code. There is a [terra-helmfile PR](https://github.com/broadinstitute/terra-helmfile/pull/1439) out to update WSM dev and all personal environments. Once this PR and the terra-helmfile one are merged, I will update the RBS pool schema for dev and tools to remove the `_v6` pools.
> PF-538: Bump default RBS project pool id from `_v6` to `_v8`.

- settings.gradle
Use the fixed bumper. This _should_ properly publish a new client with a new version number.
> [PF-749] Restore the version number

- service/local-dev/.gitignore
- service/local-dev/setup_local_env.sh
Currently, the `setup_local_env` script performs a full branch clone on two repos under the root of the terra-workspace-manager repo. This causes some confusion in the IDE, as the directories can't be .gitignore'd, so their files look like they live in the top repo in search results.
It's also confusing on the command line if you navigate into one of the directories, as your git context switches. Since it's not a good workflow anyway to be checking out branches or looking at the log from within these nested repos, I'm deleting the `.git` directories. This also makes them `.gitignore`-able, which cleans up the UI and project structure.
> [no ticket] remove .git dirs and ignore repo dirs

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/GcpPolicyBuilder.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRole.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateCustomGcpRolesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/GcpCloudSyncStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/CloudSyncRoleMappingTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
This changes the way WSM handles project-level permissions. Previously, it granted a collection of predefined roles for each workspace role (READER, WRITER, OWNER). Now, it grants a single custom role for each workspace role. The actual permissions are unchanged for this PR - I'll modify the list for PF-869 separately to keep changes separated.
As a reminder, we do not currently have any backfill support for old workspaces/projects using the predefined roles. This change will only affect newly created GCP contexts, though older workspaces can delete and recreate context to pick up this change. This will not affect RAWLS_WORSPACEs, which do not have cloud contexts.
> [PF-878] Move WSM to custom project-level roles

- integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
- integration/src/main/resources/configs/integration/CloneReferencedResources.json
- integration/src/main/resources/suites/FullIntegration.json
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedDataRepoSnapshotResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- service/src/main/resources/api/service_openapi.yaml
Create clones of all reference types that point to the original referent. This didn't involve any new flights, but reused the create reference flight.
> [PF-811] Clone Referenced Resources

- service/src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
This change (re)adds support for polling notebook start/stop operations. These permissions must be granted at the project level - we previously granted them on individual notebook instances, which had no effect. This functionality was removed when we moved permissions from broad project-level roles to narrower resource-level roles (#361), though it can be supported again now that we have custom project-level roles (#399).
This change does not address the second part of PF-869 which is focused on notebook usability in the cloud console. That will be handled as part of a design change as we revisit visibility of private resources.
> [PF-869] Support polling notebook start/stop operations

- service/src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
Added `bigquery.readsessions.*` permissions to the project reader role. ~1/2 page summary [here](https://docs.google.com/document/d/12z7e2VHbe8Q0UpDRHqbDJd2IrMGZj4H3RK5hw1hHflk/edit?resourcekey=0-98P0n7HBnhkL_NVEzJiw2A#).
Also removed `bigquery.jobs.create` permission from the resource-level role (`BIG_QUERY_DATASET_READER_PERMISSIONS `), since it's already included in the project-level role (`PROJECT_READER_PERMISSIONS`).
> PF-904: Add bigquery.readsessions.* permissions to project reader.

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
There are a few spots in our tests where we wait a static 15s for cloud IAM permissions to propagate. According to GCP these changes may take several minutes, and as a result we sometimes get flaky failures for not waiting long enough. This change replaces the static 15s waits with polling every 30s up to a 10 minute timeout, which should reduce flaky test failures.
> [PF-903] Replace 15s timeouts in tests with longer polling

- integration/src/main/java/scripts/testscripts/EnumerateResources.java
- integration/src/main/java/scripts/utils/ResourceMaker.java
- integration/src/main/resources/configs/integration/EnumerateResources.json
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/WsmResourceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
This change modifies the behavior of WSM's resource enumeration endpoint. Previously, we only showed the controlled resources that users had permissions on, meaning that workspace readers would generally not see private resources. After this change, all members of a workspace will see all resources in that workspace, including private resources which they cannot read/write to. Filter behavior on the endpoint is unchanged, and callers will not see these controlled resources if they only request referenced resources.
Additionally, this adds a number of GCP permissions so that all workspace users can navigate GCS buckets and AI Platform Notebooks directly in the cloud console. This allows workspace users to view metadata on these resources, though they still cannot read/write to private …
> [PF-909] Make listResources show private resources, support GCP cloud console

- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
This change ensures WSM stores the assigned user of a private resource in its database in all cases, even when `assignedUser` is not specified and we default to assigning the resource to the caller.
This ticket originally covered storing and returning the actual roles that private users held (READER, WRITER, EDITOR), but I decided against this approach after further discussion.
> [PF-616] Ensure assignedUser field is always stored, even if not specified

- service/src/main/resources/application.yml
Change the RBS pool id from `workspace_manager_v8` -> `workspace_manager_v9`. This new pool uses GCP-style project names with two words and a number. It also changes the project id prefix from `terra-wsm-test` -> `terra-wsm-t`, in order to leave more room for the generated words. e.g. `terra-wsm-t-shining-okra-5362`
> PF-228: Bump RBS pool id from v8 -> v9.

- service/local-dev/README.md
- service/local-dev/setup_local_env.sh
- service/local-dev/skaffold.yaml.template
Update local dev workflow to use terra-helmfile's `render` tool to render manifests instead of configuring Skaffold to use hard-coded paths to files in the terra-helmfile repo. DevOps is preparing to make some changes to the directory structure of terra-helmfile; the `render` tool is a public API for the terra-helmfile repo and will not break when those changes are made.
References to terra-helm will be removed in a future PR, when the workspacemanager chart is moved out of terra-helm.
Note that this is a reimplementation of https://github.com/DataBiosphere/terra-workspace-manager/pull/384, based on feedback on that PR.
I have tested this locally, against the `gmalkov` personal environment.
> DDO-1319 Update local dev workflow to use `render` tool

- .github/actions/start-local-server/action.yml
The action code has a scripting bug so it is not dumping the log file when the local WSM fails to come up.
Trying a fix for that and hoping it reveals whether anything is actually wrong with the integration tests post-rename.
I think this is still a good fix, even though it looks like the previous failures were Sam-related.
The problem was that the `timeout` statement would cause the action to terminate. By wrapping it in a subprocess and catching the output, it stops doing that.
I hope that the next time startup-local-server timesout, we will get a log of what went wrong.
> [PF-879] Fix error reporting on start-local-server

- integration/src/main/java/scripts/testscripts/CloneBigQueryDataset.java
- integration/src/main/java/scripts/testscripts/CloneGcsBucket.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
Two changes:
1. Added a wait for the cloning user to be able to read the dataset before proceeding with the user journey
2. Made a general `assertJobSuccess` that will info-log success and error-log the ErrorReport on failure. In the current state, if we assert the job status is SUCCEEDED, then on failure we get no information about why. I applied that change to all places where we were asserting on SUCCEEDED.
> [PF-945] integration test wait for grant to propagate

- integration/src/main/resources/configs/integration/ValidateReferencedResources.json
Moving this test to use `liam` as the test user without access to our test reference bucket, as we recently granted `elijah` access for other tests. Documentation on what the resources that each user can/can't access to follow.
> [PF-957] Fix ValidateReferencedResources test

- integration/src/main/java/scripts/testscripts/CloneBigQueryDataset.java
- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/RemoveUser.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- integration/src/main/java/scripts/utils/ResourceMaker.java
- integration/src/main/java/scripts/utils/ResourceModifier.java
- integration/src/main/resources/configs/integration/RemoveUser.json
- integration/src/main/resources/suites/FullIntegration.json
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/ControlledResourceIamRole.java
- service/src/main/java/bio/terra/workspace/service/iam/model/SamConstants.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateGcsBucketStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/notebook/ServiceAccountPolicyStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CheckUserStillInWorkspaceStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/ReadUserPrivateResourcesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/RemovePrivateResourceAccessStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromSamStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/ResourceRolePair.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
This change revokes users' access to private resources when they are removed from a workspace (i.e. when their last role in a workspace is revoked). Previously, users would maintain private resource access even when they were no longer in the workspace.
This can only handle cases where users are direct members of a workspace. WSM does not manage groups, and so cannot remove users from a workspace if they have access via a group. However, WSM can check that users have access, and will not revoke private resource access if a user still has workspace access via a group.
As part of this change, I also made two unrelated fixes:
- Controlled GCS buckets now have uniform project level access enabled. This is in line with the Terra IAM model of resources as the most granular permissions.
- Access …
> [PF-937] Handle removing users from private resources

- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
#431 added additional functionality as part of removing a user from a workspace. However, it also introduced a bug when checking whether a user is a direct member of a workspace. Sam will always return user emails as lowercase strings, but WSM is comparing those to user-provided strings without lowercasing. This meant calls to remove a user would always do nothing if the provided `userEmail` was not all lowercase already.
> [PF-937] Fix email check when removing users

- AZURE_POC.md
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/iam/ProxiedAuthenticatedUserRequestFactory.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/test/java/bio/terra/workspace/common/BaseAzureTest.java
- Enable basic auth in OpenApi spec for REST API
- Restructure `ProxiedAuthenticatedUserRequestFactory` to handle the additional option; only available when azure profile is enabled.
- When azure is enabled, stub out createWorkspace so it just logs the basic auth info; temporary for hand-testing.
> [PF-985] Azure PoC authn

- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/iam/SamRethrow.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/spendprofile/SpendProfileService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CheckSamWorkspaceAuthzStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceAuthzStep.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
In working on the Azure PoC, I noticed that some Sam methods were taking the auth token directly. Most were taking `AuthenticatedUserRequest`. It is a minor inconsistency, but in order to plumb in the mock Sam for Azure PoC, I need access to the `AuthenticatedUserRequest` in all cases.
This PR changes SamService so that all public methods use `AuthenticatedUserRequest`.  I think this is worth doing in the main branch.
In addition, I factored out the static `rethrowIfSamInterrupted` code into a separate module. SamService is pushing 1KLOC. There are probably other chunks that could be refactored to make it more manageable. In any case, now instead of saying
```
SamService.rethrowIfSamInterrupted(...)
```
you say
```
SamRethrow.onInterrupted(...)
```
> [PF-992] Make SamService more consistent

- .github/workflows/nightly-tests.yml
DevOps set up hosted runners for github actions. There are VMs within the Broad perimeter and therefore can access the ArgoCD server. That allows the nightly test to poke ArgoCD to update the software on the `wsmtest` cluster ahead of running the tests.
Since these are running with our own container, they do not have all of the software that comes with the github runners. So the big change in this flow is installing postgres ahead of running the tests.
> [PF-949] use self hosted runners for nightly tests

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/AwaitCloneAllResourcesFlightStep.java
We rely on at least one resource flight having set up this map, and failed with an NPE if an empty workspace was cloned.
> PF-987 prevent NPE in resource map

- scripts/cleanup-sam-resources.sh
This adds a small script to clean up a user's Sam resources leftover after WSM tests fail to clean them up.
> [no ticket] Add script for cleaning up after test users

- integration/src/main/java/scripts/testscripts/EnablePet.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
Followup to #427 and https://github.com/DataBiosphere/terra-cli/pull/134 which removes the project-level SA permissions WSM previously granted in workspaces. As a temporary workaround for the CLI, this continues to allow pet SA self-impersonation (tracking in PF-991).
Additionally, this lowers the role required to call the `enablePet` endpoint from WRITER to READER to align with the CLI approach of calling this endpoint as soon as users create or load a workspace. This does not change the role required to run Pipelines API jobs, which is still WRITER.
This should not merge before https://github.com/DataBiosphere/terra-cli/pull/134.
> [PF-765] Remove project-level SA permissions

- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/mappings/CustomGcpIamRoleMapping.java
Add the `storage.objects.update` permission to the custom role for controlled GCS bucket writers.
[Documentation](https://cloud.google.com/storage/docs/access-control/iam-permissions#object_permissions) says that this grants the ability to "update object metadata, excluding ACLs."
This was reported by the solutions team when trying to set the Content Type of a storage object.
> PF-999: Add storage.objects.update permission for bucket writers.

- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
A previous change replaced a call to `getEmailFromToken` with `getRequestUserEmail`, which have subtly different (and poorly documented) differences in behavior around reading an email from a `AuthenticatedUserRequest` object directly vs. calling Sam. This is an important difference when making requests as a pet service account, as the userRequest will contain the pet's email but Sam will return the owner's email.
I've renamed the methods here to be clearer and added additional documentation. In order not to break the Azure POC changes from #440, I've also changed the interface of `getEmailFromSam` to take an `AuthenticatedUserRequest` instead of a token directly.
> [PF-992] Fix email extraction to call Sam when needed

- integration/src/main/resources/configs/integration/DataReferenceLifecycle.json
- integration/src/main/resources/configs/integration/EnumerateDataReferences.json
- integration/src/main/resources/configs/integration/alpha/DataReferenceLifecycle.json
- integration/src/main/resources/configs/integration/alpha/EnumerateDataReferences.json
- integration/src/main/resources/configs/integration/staging/DataReferenceLifecycle.json
- integration/src/main/resources/configs/integration/staging/EnumerateDataReferences.json
- integration/src/main/resources/testusers/hermione.json
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
`hermione.owner` is a shared test user that's also used by Rawls and possibly other services' tests. For the sake of test isolation, we should use test users exclusive to WSM for the integration tests here.
Outside of this PR I've given `bella.redwalker` read access to the appropriate TDR snapshots in dev, alpha, and staging.
> [PF-1011] Remove Hermione from WSM integration tests

- integration/src/main/resources/testusers/README.md
Adds a small doc outlining the set of integration test users, their access to external resources, and a pointer to the Confluence page on test users.
> [PF-957] Add test user documentation

- .github/workflows/nightly-tests.yml
DevOps made changes to the self-hosted runners and that broke our tests. After several attempts (see [slack conversation](https://broadinstitute.slack.com/archives/CADM7MZ35/p1633353466459200)) we have re-settled on a working state.
This change adds `sudo` to the postgres install commands. That fixes the change that switched us off running as `root`.
> [PF-1031] gha fix

- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationUnitTest.java
The unit test `processAppTest` was consistently failing when run on Github with `DuplicateKeyExceptions` from the DB, indicating it was not being cleaned up properly. I've switched the `DirtiesContext` annotation so the test will restart before each of the marked tests instead of after, which should handle this problem more consistently.
No ticket because this only affects unit test code.
> [No ticket] Fix unit tests which fail on Github

- service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateGcsBucketStep.java
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateGcsBucketStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferenceValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
- settings.gradle
https://broadworkbench.atlassian.net/browse/PF-998
When creating a controlled resource GCS bucket with an invalid name (too long, contains goog prefix, etc), wsm ValidationUtils cannot catch these cases. Thus a StorageException with status code 400 is thrown. We should handle this case by re-throwing an InvalidReferenceException with useful messages about the error.
> PF-998: When creating a new gcs-bucket with invalid bucket name, handle StorageException correctly by re-throwing an InvalidReferenceException

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedDataRepoSnapshotResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- service/src/test/java/bio/terra/workspace/serdes/ControlledGcsBucketResourceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
This change:
- Ensures that all descendent classes of `WsmResource` call `validate()` in their constructors to ensure that all `WsmResource` objects are validated 
- Removes unnecessary explicit calls to `validate()` in a few places
- Adds name/description validation to `update` calls for both controlled and referenced resources, as these modify DB values without constructing (and thus validating) `WsmResource` objects
- Removes references to viewing logs in user-facing error messages
> [PF-1167][PF-1056] Add missing validate() calls, other validation cleanup

- integration/src/main/java/scripts/testscripts/CloneGcsBucket.java
- integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlightTest.java
Recently our tests started failing because our test users were in too many groups, which was mainly due to tests not cleaning up Sam workspaces after they finish. This change adds cleanup for all connected and integration tests which weren't previously cleaning up.
> [PF-1169] Fix tests which fail to clean up Sam workspaces

- build.gradle
- service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/WsmResourceType.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureDiskResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureIpResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureVmAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureVmResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateControlledResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/GetAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteAzureDiskStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteControlledResourceFlight.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/main/resources/application-azure.yml
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateAzureVmStepTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/create/azure/CreateControlledResourceFlightTest.java
- service/src/test/resources/application-azure-test.yml
Adds Create/Get/Delete VM code.
Note that this depends on the IP, Disk, and Network controlled resources.
Network is not done as of this PR, so there are some TODOs. I don't think this should be merged ahead of the Network PR, but it could be and is fully functional (essentially the create vm step creates a network too for testing purposes)
> [IA-2973] Add Azure vm controlled resource

- service/src/main/java/bio/terra/workspace/service/buffer/BufferService.java
- service/src/main/java/bio/terra/workspace/service/crl/CrlService.java
- service/src/main/java/bio/terra/workspace/service/datarepo/DataRepoService.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
This change refactors behavior for WSM's calls to downstream services so that all requests now share a common HTTP client object. Previously, we created a new client object for each call to a remote service. However per documentation, these clients are heavyweight objects (e.g. each `OkHttpClient` underneath a Sam `ApiClient` creates and manages its own threadpool), and this led to a large number of idle threads (peak of ~850 while running integration tests, or ~1700 while running integration tests + CLI tests). After this change, WSM peaked at ~130 threads while running integration + CLI tests, and did not increase as significantly under additional load.
I also fixed a few warnings that kept showing up in logs.
> [PF-1206][PF-1194] Share heavyweight Client objects across requests, remove warnings

- integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/DeleteGcpContextWithControlledResource.java
- integration/src/main/java/scripts/testscripts/EnumerateResources.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ValidateReferencedResources.java
- integration/src/main/java/scripts/utils/ResourceMaker.java
- integration/src/main/java/scripts/utils/ResourceModifier.java
This change fixes integration test flakiness I accidentally introduced in #486. That change made creating referenced resources flaky because:
- Previously, test users had access to our test referenced resources directly, so they would always have access as soon as we checked for it.
- After #486, we sometimes check referenced resource access using the test users' pet SAs instead of their credentials directly, depending on whether their workspace has a GCP context or not.
- Pet SAs have access to the referenced resources via the proxy group. That means the access check on these cloud objects now depends on Google Group propagation, which can take up to 5 minutes. Until the pet SA's membership in the proxy group propagates through GCP, the pet SA will not have access to the referenced cloud …
> [PF-1110] Fix test flakiness via wsm/cloud retries

- integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/ValidateReferencedResources.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- integration/src/main/java/scripts/utils/ResourceMaker.java
- integration/src/main/resources/configs/integration/ValidateReferencedResources.json
- integration/src/main/resources/testusers/README.md
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/app/controller/ResourceController.java
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/crl/CrlService.java
- service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/WsmResourceType.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsBucketFileResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsObjectAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsObjectResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResource.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
Also rename Gcs bucket file to object because that's the term cloud storage uses to refer to things in the bucket.
> PF-1234: Add GCS object level access check support

- service/build.gradle
This change means WSM will reject requests with invalid enum values with 400 status codes instead of accepting the invalid values and silently coercing them to `null`.
> [PF-1149] Add errorOnUnknownEnum flag to swagger

- integration/src/main/java/scripts/testscripts/CloneBigQueryDataset.java
- integration/src/main/java/scripts/testscripts/CloneGcsBucket.java
- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/ControlledApplicationPrivateGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledApplicationSharedGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/DeleteGcpContextWithControlledResource.java
- integration/src/main/java/scripts/testscripts/DeleteWorkspaceWithControlledResource.java
- integration/src/main/java/scripts/testscripts/EnumerateResources.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/RemoveUser.java
- integration/src/main/java/scripts/utils/ResourceMaker.java
- integration/src/main/resources/configs/integration/ControlledApplicationSharedGcsBucketLifecycle.json
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledGcsBucketAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateBigQueryDatasetStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateGcsBucketStep.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledAiNotebookInstanceResourceTest.java
Currently, user needs to specify both resource name and the resource-type specific name (e.g. datasetId, bucket name, etc).
Instead, we can just generate a default name if it's not specified.
To create a BQ dataset, one can say
terra resource create bq-dataset --name=foo
WSM will then create a bq-dataset of resource name foo and datasetId foo given "foo" is a valid dataset name as well. If the resource name is not a valid datasetid, we will generate a unique dataset id terra_uuid_dataset.
For create a GCS bucket, we will create a bucket of name terra_uuid_bucket
For AiNotebook, we will also reuse the resource name if it is a valid ai notebook name. Otherwise, we will generate a unique ai notebook name.
> PF-1201: Generate sensible resrouce id when it is not specified for Controlled resources

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Remove the incorrect use of `UnauthorizedException`. Change it to `ForbiddenException`.
The only throw was in SamService. Other changes are in tests that validate the error thrown.
> [PF-1208] Switch from unauthorized to forbidden

- service/src/main/java/bio/terra/workspace/service/job/JobBuilder.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WsmApplicationService.java
- service/src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
The original WSM JobBuilder was taken from TDR where all of the constructor parameters are required. That didn't match our usage, where we often do not supply all of the inputs. Further, we were minting job ids in many different places.
This rewrites the JobBuilder in a fully fluent style, so we only set what we use. It takes charge of all validation, defaulting, and filling in of the MdcHook and TracingHook parameters. Those tasks were previously split between JobService and JobBuilder.
> [PF-1222] Make JobBuilder fully fluent

- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateAzureVmStepTest.java
This should fix the failing VM test.
At first I thought I'd use a stable Linux image, but discovered VM creation as implemented only accepts a custom Linux image. It might be nice in the future to make the custom image optional, and support more generic OS types.
> [no ticket] Fix Azure VM creation failure due to invalid image

- service/src/test/java/bio/terra/workspace/connected/ApplicationAccessUtils.java
- service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationConfigurationTest.java
- service/src/test/resources/application-app-test.yml
- service/src/test/resources/application-configuration-test.yml
This change separates the real application configuration used for the `PrivateResourceCleanupServiceTest` connected test from the fake application configuration used by the `ApplicationConfigurationTest` unit test. Future tests which need an application should use the `app-test` profile to include this valid application configuration.
This change allows me to override the real application used in non-Broad deployment tests without also having to ignore/break the hardcoded values being checked in the unit test.
> [PF-1264] Split up WSM application testing profiles

- .github/workflows/nightly-tests.yml
- .github/workflows/pr-integration.yml
- .github/workflows/test.yml
This change moves test notifications to the new `#terra-wsm-alerts` channel.
I also changed how the emoji works, so it reflects the status result.
I added `@channel` to the message on failure, but I have not been able to confirm that works.
As usual, it is hard to test push tests without doing a push...
> [PF-1287] Reroute and pretty up slack messages

- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
For async resource create, wait until the row is present in the database (or the flight fails) to reply to the client. If that doesn't happen within a set time, return service unavailable.
This change is made so that an enumerateResources call performed while a resource is being created will show the resource. The related change for querying jobs allows the UI to know the state of the async resource create.
> [PF-1285] Wait for database row before async return

- scripts/write-config.sh
- service/src/main/resources/application.yml
A better terraformed credential is created via https://github.com/broadinstitute/terraform-ap-deployments/pull/502
Update WSM to use that
> [IA-3196] update credential path

- integration/src/main/java/scripts/testscripts/DeleteGcpContextWithControlledResource.java
- service/src/main/java/bio/terra/workspace/app/controller/Alpha1ApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ResourceController.java
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceHandler.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/MakeApiResourceDescriptionTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResourceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
In working on the larger resource handler implementation I ran into a problem. Notebooks and controlled buckets returned their GCP projectId in the resource return, but did not save the projectId in their attributes. That meant that we had to do a cloud context lookup in the database in those specific cases.
This change stores projectId as part of the attributes for those objects. The projectId is immutable, so it is safe to store with the resource. This is upward compatible, but not backward compatible. The new version of attributes can deserialize the old version of attributes, but not vice versa. This is only an issue during a rolling upgrade, so not something I think we need to worry about right now.
To implement the upward compatibility, I needed to call the GcpCloudContextService …
> [PF-1308] Make projectId an attribute of notebooks and controlled buckets.

- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/db/model/UniquenessCheckAttributes.java
- service/src/main/java/bio/terra/workspace/db/model/UniquenessCheckParameters.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/ControlledAzureDiskResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/ControlledAzureIpResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/ControlledAzureNetworkResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/ControlledAzureStorageResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/model/ControlledResource.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceType.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
Add the method `getUniquenessCheckParameters` to all controlled resource classes. The method is called from ResourceDao to get the parameters to check. The DAO then generates a SQL statement and executes the check.
This moves per-resource code out of ReesourceDao. Making the POJO to describe the check seemed better than letting the resources pass in SQL to execute. See what you think.
> [PF-1297] Refactor DAO uniqueness check

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/CreateAzureDiskStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/GetAzureDiskStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/CreateAzureIpStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/GetAzureIpStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/CreateAzureNetworkStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/GetAzureNetworkStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/GetAzureStorageStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/GetAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateControlledResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/GetCloudContextStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/AzureCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/CreateAzureDiskStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/GetAzureDiskStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/CreateAzureIpStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/GetAzureIpStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/CreateAzureNetworkStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/GetAzureNetworkStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/GetAzureStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
For GCP, we have a step that retrieves the cloud context and puts it in the working map. For Azure, we were retrieving the context in the Flight constructor and passing it as a parameter. This consolidates the cloud context retrieval in a new step calls `GetCloudContextStep`.
In general, avoid doing any interesting code in the flight constructor. The error handling from exceptions thrown in the constructor are not handled as well as from a step. Also, there is efficiency gained if the flight is paused and restarted.
This is part 1 of 2 that will extract resource steps into the resource object and remove the big switch statements. All part of making it simpler and more localized to add resources.
> [PF-1298] Retrieve all cloud contexts in a step

- integration/src/main/resources/configs/integration/DataReferenceLifecycle.json
- integration/src/main/resources/configs/integration/EnumerateDataReferences.json
- integration/src/main/resources/configs/integration/ReferencedDataRepoSnapshotLifecycle.json
- integration/src/main/resources/configs/perf/DataReferenceLifecycle.json
- integration/src/main/resources/configs/perf/EnumerateDataReferences.json
The [`ReferencedDataRepoSnapshotLifecycle`](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/integration/src/main/java/scripts/testscripts/ReferencedDataRepoSnapshotLifecycle.java) IT is failing because the snapshots it was consuming were deleted. 
* Points at 2 newly created snapshots that were created and explicitly named for this test
* I need to look into creating a dev group that can own these snapshots, for now they are under my dev acct and readable by the IT SAs.
> [WOR-137] Point at new snapshots for ITs

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
This test is very occasionally failing as we do not wait for the workspace WRITER group to sync before checking their GCP permissions. I had assumed that since we do wait for Sam to sync the workspace READER group, all groups in the same workspace would be synchronized at once, but this does not appear to be true.
> [PF-1346] Add wait for workspace writer test user to fix mild flakiness

- service/src/test/java/bio/terra/workspace/service/workspace/flight/create/azure/CreateAzureContextFlightTest.java
The missing parameter to azure context create was fixed by WOR-122.
There was no test that caught that problem. I modified one of the service tests to exercise that path so this won't regress.
> [PF-1350] Modify test to exercise azure context create service call

- service/src/main/resources/api/service_openapi.yaml
They are listed as optional, but will be present on success.
> [PF-1090] Mark bucket and bigquery response properties as required

- .run/Main.run.xml
- service/src/main/java/bio/terra/workspace/app/configuration/external/CliConfiguration.java
- service/src/main/java/bio/terra/workspace/app/controller/UnauthenticatedApiController.java
- service/src/main/resources/api/service_openapi.yaml
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
Read `WORKSPACE_CLI_OLDESTSUPPORTEDVERSION` env var and provide value on the `/version` endpoint.
> [PF-1034] Expose oldest CLI version property

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/utils/BqDataTableUtils.java
- integration/src/main/java/scripts/utils/BqDatasetUtils.java
This change removes the places in integration tests where we currently implicitly use BigQuery temporary tables to hold query results. Instead, all queries which return results now have the destination table explicitly specified. This allows us to run these tests in cloud environments where Domain Restricted Sharing is enforced - otherwise, BigQuery will attempt to grant IAM policies on temporary tables directly to end-users, which causes errors.
> [PF-1347] Use BQ result tables instead of temporary tables in tests

- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
This fixes an error in the `createAiNotebookInstanceUndo` connectedTest where we checked a pre-flight assertion during a flight instead of before it. This led to flaky failures depending on how far along the flight was when the assertion ran.
> [PF-1371] Fix flaky createAiNotebookInstanceUndo test

- service/src/main/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupService.java
WSM periodically polls Sam for all active private resources to ensure that users lose access when they are removed from workspaces. Doing this requires that the WSM SA have the `manager` role on all workspaces, so it's only possible to enforce this on workspaces created after https://github.com/DataBiosphere/terra-workspace-manager/pull/505/files was merged. The intent was to ignore older workspaces to avoid repeatedly polling.
However, this is broken because WSM was expecting the wrong response code from Sam. As a result, private resource cleanup has been broken for a few weeks.
> [PF-1322] Fix private resource cleanup handling for old workspaces

- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightV2.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreatePetSaStep.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightV2Test.java
This change adds a new step to the "create GCP context" flight to create a pet service account in the newly-created GCP project for the caller. Previously, pet SAs would only be created the first time they were explicitly requested from Sam. This is a small optimization to prevent the following failure case which has appeared a few times:
1. Sam immediately adds new pet SAs to the appropriate proxy group on creation. However, there can be a small delay (generally a few seconds) before GCP permissions granted to the proxy group apply to the new group member.
2. A common use of pet SAs in Workspace Manager is checking access to referenced cloud resources, which happens on referenced resource creation. If this is the first time a user's pet is needed in the workspace, WSM will request Sam …
> [PF-1363] Create caller's pet SA on GCP context create

- .github/workflows/tag-publish.yml
Not sure how I messed it up, but here is a fix. I am leaving the logging step in because
- it is cheap
- when we add other things to the release it will help the next dev know what the right path is
> [No Ticket] Fix the release workflow to have the right file path

- README.md
The WSM client has been published as `workspace-manager-client` instead of `terra-workspace-manager-client` for the past > year, but we never updated the README.
> [No ticket] Fix outdated client library documentation

- service/src/main/java/bio/terra/workspace/app/configuration/external/WsmApplicationConfiguration.java
This changes the application configuration reader to return an empty `Map` instead of null when no applications are configured. This is similar to the previous `List` behavior prior to #580.
Without this change, WSM will always [throw a NPE](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/main/java/bio/terra/workspace/service/workspace/WsmApplicationService.java#L261) on startup if no applications are configured. This was hidden in this repo because one application is present in the default configuration values, but the Verily default configuration did not have this.
> [PF-1330] Return empty application map from config instead of null

- integration/src/main/java/scripts/testscripts/EnumerateJobs.java
- openapi/src/parts/alpha1.yaml
- service/src/main/java/bio/terra/workspace/app/controller/Alpha1ApiController.java
Based on feedback from @cbookg I revised the enumerate jobs API to return the same structure as the enumerate resources. That is, with the common metadata factored out and only the attributes separated into the union.
> [PF-1410] Revise the enumerate jobs return

- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
Before PR:
1. Line 87: Create first notebook
2. In `createAControlledAiNotebookInstanceWithoutSpecifiedInstanceId_validInstanceIdIsGenerated()`
- Create second notebook
- Delete second notebook
3. In `createAControlledAiNotebookInstanceWithoutSpecifiedInstanceId_specifyLocation()`
- Create third notebook
- Delete third notebook
4. Line 157: List notebooks and assert there are 3 notebooks
4 was sometimes failing because second notebook was deleted, so there were 2 notebooks instead of 3.
I moved 4 to before 2. Instead of 3 notebooks, I assert there is 1 notebook.
> Fix flaky test PrivateControlledAiNotebookInstanceLifecycle

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
https://broadworkbench.atlassian.net/browse/IA-3211
Previously nic is created implicitly, and when we're using an image size that's not supported in a location, Azure will somehow try to implicitly create 2 nics, and VM creation will fail with a very non helpful message
```
Resource /subscriptions/3efc5bdf-be0e-44e7-b1d7-c08931e3c16c/resourceGroups/mrg-terra-integration-test-20211118/providers/Microsoft.Network/networkInterfaces/nic63118f8d27a/ipConfigurations/primary is referencing public IP address /subscriptions/3efc5bdf-be0e-44e7-b1d7-c08931e3c16c/resourceGroups/mrg-terra-integration-test-20211118/providers/Microsoft.Network/publicIPAddresses/ip-1647876356741 that is already allocated to resource /subscriptions/3efc5bdf-be0e-44e7-b1d7-c08931e3c16c/resourceGroups/mrg-terra-integration-t …
```
> IA-3211 Explicitly create nic instead of relying on Azure to implicitly creating nic

- service/src/main/java/bio/terra/workspace/app/configuration/spring/BeanConfig.java
Informational finding from a pentest, recommendation was unicode-escaping certain characters in all JSON responses to prevent potential XSS attacks if the responses is rendered improperly in a UI.
This is difficult to test directly as the Java client our integration tests use automatically un-escapes the characters in responses, but I tested manually as follows:
1. Create a workspace with description `test string with characters " \n \t & < > \ /`
2. Prior to the change, calls to GET this workspace return description `test string with characters \" \\n \\t & < > \\ /` in the response. The UI displays a string matching the original description.
3. After this change, calls to GET this workspace return description `test string with characters \" \\n \\t \u0026 \u003C \u003E \\ /` in the …
> [PF-1256] Unicode-escape certain characters in WSM JSON responses

- .github/workflows/tag-publish.yml
The `google-github-actions/setup-gcloud` action is moving their main branch from `master` to `main`, we're currently pinned to the version at `master` (extensive warning here: https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2040799754). This is the only usage of this action in this repo.
Pinning this at `v0` instead per above warning, since I don't think we should set `SETUP_GCLOUD_I_UNDERSTAND_USING_MASTER_WILL_BREAK_MY_WORKFLOW_ON_2022_04_05`
> [No Ticket] Pin setup-gcloud Github Action to version

- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/create/CreateReferenceResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/create/ValidateReferenceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/update/UpdateReferenceResourceFlight.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
Remove the access step check from the `CreateReferencedResourceFlight`, but don't delete it, as it will be needed again soon for the on-demand access check functionality.
> [PF-1428] don't check access on referenced resource create or update

- service/src/main/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupService.java
Unfortunately the SLF4J `Logger` interface doesn't support logging both a Throwable and an arbitrary JSON object in the same entry, so this needs to be two separate log entries. This approach will log the full stacktrace of the thrown exception. Previously, the exception wouldn't be included in the log at all, although the JSON object would be.
These stacktraces will only appear in logs, and are not returned as responses to users.
> [PF-1247] Include stacktrace in privateResourceCleanup failure logs

- service/src/main/java/bio/terra/workspace/app/configuration/spring/BeanConfig.java
Spotbugs warns that we're exposing a `private final` array via public method as required by the `CharacterEscapes` class. This is expected, and the class documentation notes "Caller is not to modify contents of this array, since this is expected to be a shared copy" on the return value of `getEscapeCodesForAscii`.
> [PF-1449] Suppress unnecessary spotbugs warning

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
We recently had a failure due to a BQ dataset name conflict in `ControlledResourceServiceTest` resources. This should make those conflicts much less likely.
I also fixed a `Logger` bug in `ControlledBigQueryDatasetLifecycle`, I think the wrong class got copied when this test was written, which gave us slightly misleading logs.
> [PF-1530] Make connected test dataset names more unique

- service/src/main/java/bio/terra/workspace/service/petserviceaccount/PetSaService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/GrantPetUsagePermissionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/StorageTransferServiceUtils.java
Two changes to the pet SA impersonation implementation:
1. Test the policy bindings before making a policy update. The setIam call is rate limited and we hit the limit in testing. We can avoid the call when the same user makes and/or deletes multiple notebooks.
2. Add handling for the conflict (409) error from GCP. We use the step's retry, so it is a matter of making a good error and then returning `Retry` from the step.
> [PF-1488] [PF-1496] Improve Pet SA impersonation processing

- .github/workflows/tag-publish.yml
The current `bumper` action version is currently broken due to Github's mitigation of a security issue, moving this to the latest version which has a patch (https://github.com/DataBiosphere/github-actions/pull/32)
Example failure (see `Bump tag to a new version`): https://github.com/DataBiosphere/terra-workspace-manager/runs/6011344595?check_suite_focus=true
> [No Ticket] Use latest bumper GHA version

- openapi/src/parts/controlled_azure_vm.yaml
- openapi/src/resources/azure_vm.yaml
- service/src/main/java/bio/terra/workspace/app/configuration/StoragetransferConfiguration.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/AzureVmUtils.java
- service/src/main/java/bio/terra/workspace/common/utils/FlightBeanBag.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/DeleteStorageTransferServiceJobStep.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CreateStorageTransferServiceJobStepTest.java
Extend 'Create VM' functionality with VM custom script extension. One of the main use case is to setup Data Science VM and expose Jupyter Notebook via Azure Relay.
VM create endpoint will handle optional parameter for 'custom script extension'. This allows to customize VM provisioning with custom startup script.  Also currently we can use standard VM image from marketplace. This functionality requires username/password for VM to be passed to the endpoint as well.
-Updated VM create endpoint payload with new optional parameter - customScriptExtension
-Updated CreateAzureVmStep to handle this new parameter.
!!Not all the files directly related to this feature. Some of the files just have updated formatting.
> TOAZ-83 Run listener inside the Notebook VM.

- .github/workflows/nightly-tests.yml
No longer has any benefit after https://broadinstitute.slack.com/archives/C2B7JFJ4S/p1649802203643319.
The action has run off of this branch successfully here: https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2162363076, https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2198707115, https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2204640363
> [DDO-2025] Remove self-hosted runners from WSM

- DEVELOPMENT.md
- integration/src/main/java/scripts/testscripts/GetWorkspace.java
- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/exceptions/DuplicateUserFacingIdException.java
- service/src/main/java/bio/terra/workspace/service/workspace/exceptions/DuplicateWorkspaceException.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/model/Workspace.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextUnitTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Tested with swagger: create succeeds, create fails, update succeeds, update fails.
If someone tries to create a workspace with an existing userFacingId, we show friendly error:
Same with update workspace:
----
[In Workspace.build()](https://github.com/DataBiosphere/terra-workspace-manager/blob/19c461a3d0e94c5be0f4cf3f674a0c7f3ffb566d/service/src/main/java/bio/terra/workspace/service/workspace/model/Workspace.java#L170), I can't do this:
```
if (userFacingId == null) {
userFacingId = "";
}
```
Because for tests that don't set `userFacingId`, it will be set to `""` in DB. Creating the first workspace works. Creating the second workspace fails; the uniqueness constraint for `userFacingId` fails because there is already a workspace with `userFacingId = ""`.
In PF-1596, I will auto-populate …
> [PF-1576, PF-1596] Add Workspace.userFacingId and plumb through to API

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
- service/src/test/java/bio/terra/workspace/connected/WorkspaceConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/StoreControlledResourceMetadataStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AzureWorkspaceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightV2Test.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGcpContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
Before this PR:
- CloneWorkspaceRequest doesn't have `userFacingId` field
- In db, destination workspace dosen't have userFacingId set
After:
- CloneWorkspaceRequest has `userFacingId` field
- In db, destination workspace has userFacingId set
Before we validated (`ControllerValidationUtils.validateUserFacingId`) `userFacingId` in:
- controller `createWorkspace` `updateWorkspace`
In this PR, I added validation to:
- controller `cloneWorkspace`
- dao `createWorkspace` `updateWorkspace`
I added validation to dao to be extra-safe -- for example, what if there's some new endpoint in the future that calls `dao.createWorkspace`.
Dao validation meant I had to change a bunch of unit/connected tests to set `userFacingId`. (In normal application, this is set in controller, which unit/connected tests …
> [PF-1616] Have CloneWorkspace work with userFacingId

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
`--defer-login` is going away, so authenticate before calling `terra workspace set`. See PF-1622 for why `--defer-login` is going away.
> [PF-1622] In startup script, authenticate before setting workspace

- service/gradle/deploy.gradle
The only way to test this in the nightly test context is to merge it, so I am going to force merge.
> Use jre:17-debian base docker image

- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/StoreControlledResourceMetadataStepTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightV2Test.java
This will allow the UI to create a rich experience on the destination workspace page while clone is happening. Previously, there was no way to know which workspaces were in the process of being cloned into, and no way to find the source workspace associated with a given destination workspace (to enumerate the clone job and/or its resource jobs).
Two spotless fixes stowed away here. These are necessary in order to pass the now-re-required lint checks.
> [PF-1635] Assign destination workspace ID as Job ID for clone

- .gitignore
- service/src/main/java/bio/terra/workspace/service/petserviceaccount/PetSaService.java
Previously, WSM was the only service which would grant the ServiceAccountUser role on pet service accounts. Now that Sam is also giving pet SAs permission to impersonate themselves, some of the logic inside WSM for handling IAM bindings is incorrect. 
GCP IAM bindings have one role and a list of members with that role. WSM previously tried to create/remove bindings with exactly one member, but it's now possible (and technically should always be true) that there will be a second member with that role, since pets have permission to impersonate themselves.
This issue broke a few tests (connected test `createAiNotebookInstanceUndo` and integration test `EnablePet`) which check that we can revoke a user's permission on their pet, but the test logic is actually still correct, the issue is in …
> [IA-3326] Handle pet impersonation IAM roles properly

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/CreateAiNotebookInstanceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/exception/ReservedMetadataKeyException.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/CreateAiNotebookInstanceStepTest.java
The default notebook startup script currently retrieves the workspace ID from the notebook metadata key `instance/attributes/terra-workspace-id` and attempts to run the command `terra workspace set --id=${TERRA_WORKSPACE}`. 
WSM is still setting the UUID workspace ID as the value for this key, but terra workspace set now requires the user-facing ID instead of the UUID. This breaks the default startup script (and indirectly breaks git repo cloning because the script errors out before it gets there). I think the right behavior here is to store the UFID as the metadata key
> [PF-1658] Store UFID as notebook metadata instead of uuid

- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
https://cloud.google.com/artifact-registry/docs/access-control
PROJECT_READER_PERMISSION maps to roles/artifactregistry.reader (view and get artifacts, view repository metadata)
PROJECT_WRITER_PERMISSION maps to roles/artifactregistry.writer (READA and write artifacts)
https://cloud.google.com/build/docs/iam-roles-permissions
PROJECT_READER_PERMISSION maps to cloudbuild.builds.viewer (can view cloud build resources)
PROJECT_WRITER_PERMISSION maps to cloudbuild.builds.editor (full control of cloud build resources)
> [PF-1524] Add permissions for GAR and Cloudbuild

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/petserviceaccount/PetSaService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/GrantPetUsagePermissionStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/RevokePetUsagePermissionStep.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
(small bug I noticed while adding test coverage)
Currently, the undo step of RevokePetUsagePermissionStep tries to re-grant the same permission it revokes in the do step. However, when this flight is triggered by one user removing another from the workspace, this step’s undo fetches the caller's pet SA, not the removed user’s pet, which breaks the undo.
This bug could affect real users, but it’s difficult to trigger, as the RemoveUserFromWorkspace flight would need to fail on or after the second-to-last step. This functionality is also not available in any WSM environments above dev, so it's unlikely this has affected any real users yet. If it affected a real user, I think they could fix it by calling the enablePet endpoint, though it would be pretty hard for them to know to do that.
> [PF-1672] Fix broken RevokePetUsagePermissionStep undo

- service/src/main/java/bio/terra/workspace/app/controller/GlobalExceptionHandler.java
Currently WSM will respond with a 500 error (generated by the catchall error handler) if a user calls a valid endpoint with an invalid HTTP method (e.g. `DELETE /status`). I think a 400 is a more appropriate response here.
> [PF-1690] Handle invalid http methods better

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCreateReferenceResourceFlightStep.java
Previously I was overwriting the description with something like `Clone of referenced resource <id>`. This is a change to not do that.
> [PF-1701] Clone reference names and descriptions

- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
In #676, it looks like an un-spotlessed change was pulled in during the final merge. Post-commit linter test [failed](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2468989326) on this file. Fix is simply to run `spotlessApply` on head.
> fix missed spotless application

- .github/workflows/test.yml
- DEVELOPMENT.md
- buildSrc/src/main/groovy/terra-workspace-manager.java-conventions.gradle
- service/build.gradle
- service/gradle/testing.gradle
Currently, we only generate a Jacoco report showing coverage for the most recently run task. Instead, when running multiple tasks (such as `unitTest` + `connectedTest` like we do for PRs), this should now give us the combined coverage from all test types we've run.
This also creates and documents a new `jacocoBootRun` task which runs the server instrumented by Jacoco. This is useful for integration tests which run against a local server, but I think there's a moderate performance hit so it's better to keep using `bootRun` for live environments.
Incidentally I think removing `dependsOn test` from the jacoco test report task also fixes the bug where running `unitTest` would run the unit tests twice! Previously the `unitTest` task triggered the `jacocoTestReport` which depended on the `test` …
> [PF-1519] Create a single combined jacoco report

- openapi/src/parts/alpha1.yaml
- service/src/main/java/bio/terra/workspace/app/controller/Alpha1ApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneAllResourcesFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/FindResourcesToCloneStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneAllResourcesFlightStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneControlledGcpBigQueryDatasetResourceFlightStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneGcsBucketResourceFlightStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCreateReferenceResourceFlightStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/ResourceCloneInputs.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/ReferencedResourceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/FindResourcesToCloneStepTest.java
In order to inform the UI about the resources being created by cloning, we need to give it the destination resource ID via the Enumerate Jobs API. This involves pre-computing all the IDs and passing them through a couple levels of flights so that they're available in the flight input parameters later when the enumeration happens and we hydrate all the extra goodies like resource metadata and attributes.
My original thought was to include a key-value map instead of an individual parameter, but that's inviting abuse. We can tolerate a null value for destination resource id on the non-clone jobs.
> [PF-1476] Include destination resource ID on job enumerate object

- integration/src/main/resources/configs/integration/ControlledGcsBucketLifecycle.json
gcs bucket update sometimes run long and thread keeps getting killed before the test finish.
> [PF-1801] ControlledGcsbucketLifecycle keeps timing out

- service/src/main/java/bio/terra/workspace/common/utils/GcpUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/BucketCloneRolesService.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/BucketCloneRolesComponentTest.java
The waiting code in BucketCloneRolesService introduced for PF-1500 did not work as intended. An `equals` comparison on two `Policy` objects compares the `etag`. The `etag` on the input to `setIamPolicy` is (by semantics of etags) never the same as the `etag` resulting from the call.
The new version of the code implements a specific comparison for the added/removed roles showing up/disappearing. The code change required a change to the unit tests.
I removed the `GcpUtils.pollUntilEqual` since it was unused and slightly broken. We can write such a thing again if the case comes up.
All of that done, I am not sure either the old code or this new code is actually needed. Do we know that there is a case where a `getIamPolicy` following a successful `setIamPolicy` will return something other …
> PF-1826 - fix policy change waiting code

- integration/src/main/java/scripts/testscripts/ControlledAzureVmNoPublicIpLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledAzureVmWithCustomScriptExtensionNoPublicIpLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledAzureVmWithPublicIpLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledAzureVmWithWrongCredentialsLifecycle.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- integration/src/main/java/scripts/utils/CloudContextMaker.java
- integration/src/main/java/scripts/utils/ControlledAzureTestScriptBase.java
- integration/src/main/java/scripts/utils/ControlledAzureVmTestScriptBase.java
- integration/src/main/resources/configs/integration/ControlledAzureVmNoPublicIpLifecycle.json
- integration/src/main/resources/configs/integration/ControlledAzureVmWithCustomScriptExtensionNoPublicIpLifecycle.json
- integration/src/main/resources/configs/integration/ControlledAzureVmWithPublicIpLifecycle.json
- integration/src/main/resources/configs/integration/ControlledAzureVmWithWrongCredentialsLifecycle.json
- integration/src/main/resources/suites/FullIntegration.json
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
TOAZ-118 [WSM] Add integration test for createVM API
-create vm with private ip and custom script extension (main scenario for Jupyter VM)
-create vm with private ip
-create vm with public ip
-create vm with incorrect credentials. Expected failure.
> TOAZ-118 [WSM] Add integration test for createVM API

- service/src/main/java/bio/terra/workspace/common/logging/model/ActivityFlight.java
it's not used anywhere or stored in the database yet.
> [PF-1800] Correct the name of this enum

- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- service/src/main/java/bio/terra/workspace/app/controller/ControllerBase.java
Have the controller return an error if the PrivateResourceUser is sent when creating private resources. Update tests to account for this.
> PF-1218: Disallow PrivateResourceUser on user-private resources

- integration/src/main/resources/suites/FullIntegration.json
Need to temporarily remove Azure tests from WSM nightly run. The issue is not related directly to functionality but related to cleanup procedure which TestRunner runs. It looks like VM deletion procedure takes more time than expected (while deleting workspace). It causes retry operation to run clean up again and start deleting workspace again. Thanks @ddietterich for finding the root cause!
> Temporarily remove Azure VM tests

- integration/src/main/java/scripts/testscripts/WorkspaceLifecycle.java
- openapi/src/common/parameters.yaml
- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
- service/src/test/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHookTest.java
- service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/ControllerValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/connected/WorkspaceConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureControlledStorageResourceServiceTest.java
For the 1000 Genomes workspaces, I'd like userFacing id to be 1000-genomes instead of a-1000-genomes.
@cbookg I can take a stab at corresponding UI PR.
> [PF-1747] Allow userFacingId to start with number

- service/src/main/java/bio/terra/workspace/app/configuration/spring/BeanConfig.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
Does not break CLI
```
Title:			
Short description:	
Version:		
Created:		2022-07-22
Last updated:		2022-07-22
Resources:
NAME                            RESOURCE TYPE         DESCRIPTION     
```
swagger:
```
{
"workspaces": [
{
"id": "4650baba-8a52-46c8-bb02-ba9423ad4dff",
"userFacingId": "workspace1",
"displayName": "",
"description": "",
"highestRole": "OWNER",
"spendProfile": "wm-default-spend-profile",
"stage": "MC_WORKSPACE",
"gcpContext": {
"projectId": "terra-wsm-t-clever-apple-9738"
},
"properties": [],
"createdDate": "2022-07-22T19:14:42.787477Z",
"lastUpdatedDate": "2022-07-22T19:15:07.941062Z"
},
{
"id": "f9ca20a6-b845-41cf-914a-36c65aa8591a",
"userFacingId": "gcpworkspace",
"displayName": "",
"description": "",
"highestRole": "OWNER",
"spendProfile": …
```
> PF-1855: disable WRITE_DATE_AS_TIMESTAMPS so they keep the RFC3339 format.

- integration/src/main/java/scripts/testscripts/ControlledApplicationPrivateGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- openapi/src/common/schemas.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControllerBase.java
Changes the input from a list of roles to a single role. UI and CLI should also be updated to account for this, but they aren't sending anything for this field now anyway.
> PF-1218: Change the resource role list to a single role

- service/build.gradle
- service/gradle/testing.gradle
For GHA runs, retry failing tests. If 2nd time passes, workflow will still fail and oncall will still be notified. This way, oncall doesn't have to rerun workflow in GHA. Note that this is faster because only the tests that failed are rerun.
In CLI repo, @zloery found that adding to `test` block didn't work, he had to add to `runTestsWithTag`. So unfortunately I have to duplicate. (And this can't go in terra-gradle-plugin repo.)
I didn't do integration tests, since integration tests don't use junit (QA-1764). [Retry plugin requires junit.](https://github.com/gradle/test-retry-gradle-plugin#supported-test-frameworks)
> Gradle retry for non-integration tests

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
[Previous PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/733) broke startup script:
With conda, must be `pandas-gbq` (this is why [previous PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/733) broke). With pip, can be `pandas-gbq` or `pandas_gbq`.
conda took 17 minutes (!!). pip takes less than 1 minute, so changed to pip.
> In post-startup script, use pip instead of conda

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
- service/src/test/java/bio/terra/workspace/service/iam/WsmIamRoleTest.java
Currently when WSM encounters unknown Sam roles, it throws an exception. However, this can happen when reading the roles from a RAWLS_WORKSPACE stage workspaces, as Rawls may have set a role that WSM doesn't understand. Instead of throwing an exception WSM should silently ignore these roles.
> [PF-1882] Handle unknown roles from Sam

- .github/workflows/nightly-tests.yml
- .gitignore
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
[Last night's nightly test failed.](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2794805592)
Yesterday, with a local WSM, I added discoverer policy to some workspaces in broad-dev SAM. The test's ListWorkspaces picked those up. Nightly test WSM (`https://workspace.wsmtest.integ.envs.broadinstitute.org/`) didn't know about discoverer role. It threw an exception when a workspace didn't have any SAM permissions.
In this PR, if a workspace doesn't have any SAM permission, ListWorkspaces doesn't return it.
> [PF-1882] Handle roles that WSM doesn't know about yet

- .github/workflows/nightly-tests.yml
- .github/workflows/pr-integration.yml
- .github/workflows/release-promotion-tests.yml
- .github/workflows/test.yml
- .github/workflows/workflow-tester.yml
Fixes vault tokens being leaked in GHA logs when debug logging is enabled.
See [this thread](https://broadinstitute.slack.com/archives/CADU7L0SZ/p1659646210275089) for more context.
> Fix Debug Logs in GHA leaking vault tokens

- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- openapi/src/common/schemas.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControllerBase.java
This is the last phase of the API update - where we stop accepting a list of roles. We also require both the user + single role to be sent if the PrivateResourceUser is sent.
> PF-1218: Stop accepting a list of roles on the private resource user

- integration/src/main/java/scripts/testscripts/ListWorkspaces.java
- openapi/src/common/parameters.yaml
- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/model/WorkspaceConstants.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Also delete test from WorkspaceServiceTest.listWorkspacesAndHighestRoles_existing because same functionality is now tested in WorkspaceApiControllerConnectedTest.
Manually tested
- Configured workspace where second user only has discoverer role
- Second user runs ListWorkspaces with minimumHighestRole unset, no workspace returned
- Second user runs ListWorkspaces with minimumHighestRole set to DISCOVERER, subset of workspace is returned ([screenshot](https://screenshot.googleplex.com/6xYX7V9GiFkQz3T))
- Workspace owner calls ListWorkspace with minimumHighestRole set to DISCOVERER, full workspace is returned
> [PF-1875] Add minimumHighestRole to ListWorkspaces request 

- service/src/main/java/bio/terra/workspace/service/workspace/flight/GrantWsmRoleAdminStep.java
Not retrying a timeout here failed the nightly tests on 8/12. This step already has an associated retry rule in the flight, so no changes are required there.
> [PF-1904] Retry GCP errors in GrantWsmRoleAdminStep

- srcclr.yml
Veracode SCA, aka srcclr, is used to scan for vulnerable 3rd party components. In WSM, srcclr was failing to find any code with default scope. Adding a configuration file to specify the productionRuntimeClasspath scope fixes the scan. 
The scan will still be run in a separate appsec repo on a weekly basis for now. If the team wants to set up a github action or gradle configuration to scan it on every PR, we in appsec can help make that happen, but that is neither urgent nor required.
> [DSEC-404] fix srcclr scans by specifying scope in srcclr.yml

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
Changes - 
Check if java 17 is installed. If not: install JDK17 and set it as the default version to be used
Verifying java upgrade on notebook 
```
(base) jupyter@dexamundsen-20220819-215419:~$ java --version
java 17.0.4.1 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
(base) jupyter@dexamundsen-20220819-215419:~$ update-alternatives --list java
/usr/lib/jvm/java-11-openjdk-amd64/bin/java
/usr/lib/jvm/jdk-17/bin/java
(base) jupyter@dexamundsen-20220819-215419:~$ 
```
Logs from post_startup script 
```
(base) jupyter@dexamundsen-20220819-215419:~$ grep java  /home/jupyter/.terra/post-startup-output.txt 
++ which java
+ [[ -n /usr/bin/java ]]
++ java -version
+ echo 'current java …
```
> [PF-1921] Install java 17 in jupyter notebooks

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneGcpWorkspaceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/ClonePolicyAttributesStep.java
Not all environments will have TPS enabled. We don't need to attempt to clone policies if the feature is not turned on.
> PF-1871 - Clone policy step will return right away if TPS is not enabled

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/utils/WorkspaceAllocateTestScriptBase.java
- integration/src/main/java/scripts/utils/WorkspaceAllocateWithPolicyTestScriptBase.java
Part of #766 modified `WorkspaceAllocateTestScriptBase` to include policy information, but I forgot that several tests using this base run in environments which don't have TPS enabled. As a result, the basic integration tests are broken when they run against environments > dev (as WSM rejects requests including policy information if TPS is disabled). However, the service itself is fine, so I don't think we need to roll #766 back entirely.
This splits the policy into a separate base class for now, with the expectation that we'll delete this class once TPS is enabled in all environments.
> [PF-1871] Stop sending policy information for most integration tests

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDefinitionStep.java
Clean up an unused method `randomDatasetName`. Also if destination dataset name is specified, we should respect that.
> PF-1956: clean up dead code.

- service/src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationConfigurationTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationUnitTest.java
- service/src/test/resources/application-test.yml
This change to the test configuration minimizes the number of connections held open by the connection pooling.
It seems to solve hitting the connection limit. Clearly more work is needed to manage this better in the tests, but
I think this will get us by for now.
Of course, we'll see when the GHA tests run whether it fixes things more generally.
> [no ticket] Minimize idle connections

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStep.java
this bucket name generation does not follow the new standard way. So removing this. at line 100, we are also checking for bucketname null and using the right way to generate one.
> PF-1956: Clean up dead code-ish

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
Variables now show in Jupyter notebooks and terminals:
Here is the .bash_profile:
```
(base) jupyter@mbookman-20220831-223034:~$ cat ~/.bash_profile
export GOOGLE_PROJECT='terra-<stuff>'
export OWNER_EMAIL='<stuff>'
export PET_SA_EMAIL='pet-<stuff>@terra-<stuff>.iam.gserviceaccount.com'
eval "$(ssh-agent -s)"
```
Here's the relevant bits of the environment in a terminal in Jupyterlab:
```
(base) jupyter@mbookman-20220831-223034:~$ env | grep EMAIL
OWNER_EMAIL=<stuff>
PET_SA_EMAIL=pet-<stuff>@terra-<stuff>.iam.gserviceaccount.com
(base) jupyter@mbookman-20220831-223034:~$ env | grep GOOGLE
GOOGLE_PROJECT=terra-<stuff>
```
Added some small cleanup to the post_startup.sh where code was a little inconsistent.
> [PF-1955] Add GOOGLE_PROJECT, OWNER_EMAIL, PET_SA_EMAIL environment variables.

- service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
The local config here is configured with a service account named `leo` but Verily environments are not, which breaks connected tests. This switches the WorkspaceServiceTest to use `TestWsmApp`, which is specified in the `app-test` profile. Unlike integration tests this will only ever use local configuration, so it's safe to test with this application without worrying about what apps are enabled in live environments.
(tested via verily-src submodule)
> [PF-1041] Fixes for WorkspaceServiceTest

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandler.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandlerTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandlerTest.java
In this ticket, we are focusing correcting 2 bugs on the previous ticket for [autogeneration the cloud name](https://github.com/DataBiosphere/terra-workspace-manager/pull/764). 
For the AI notebook cloud instance id, we do not have the official document in gcp like the old code mentioned. I just add a corner case which not allow the cloud instance id starts with numbers, if it does, we strip the numbers until it satisfied the requirement.
For the controlled gcs bucket, the official doc is [here](https://cloud.google.com/storage/docs/naming-buckets). In order to improve the suggestion name, I add the bad case start with `goog` prefix, then, strip it. 
Also add the comments on bq dataset to make consistence.
> [PF-1954] bucket cloud names do not allow "goog" prefix; notebook cloud instance ids do not allow numbers start

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/ClonePolicyAttributesStep.java
If we're cloning a workspace that doesn't have a policy attached - IE it was created before TPS was turned on - then create an empty policy on the source workspace before cloning it.
> PF-1966: Unable to clone pre-policy workspace

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This PR comes from the ticket [PF-1961](https://broadworkbench.atlassian.net/browse/PF-1961).
The logic follows UI logic which is 
1. if user specifies a displayName on the new workspace, we should use the user specified displayName firstly.
2.  If user does not specify, We will generate the name as the "[clonedWorkspace's displayname]" + " (Copy)"
3.  If the clonedWorkspace's displayname is null, we will use "[clonedWorkspace's userfacingId]" + " (Copy)"
These are the 3 scenarios
**Scenario 1, use user specified name** 
```
ginay-macbookpro:terra-cli ginay$ terra workspace clone --new-id=clonenew1 --name=clonenewname
Workspace successfully cloned.
Source Workspace:
ID:                913cromwell
Name:              clonenamecheck
Description:       
Google project: …
```
> [PF-1961] Clone workspace displayname follow the "[cloneWorkspace displayName]" + " (Copy)"

- service/src/main/java/bio/terra/workspace/service/datarepo/DataRepoService.java
In https://github.com/DataBiosphere/jade-data-repo/pull/1343, TDR began returning 403 responses when a user does not have permission, rather than 401, so WSM needs to handle the new response. This broke the `ReferencedDataRepoSnapshotLifecycle` integration test.
This is the only spot WSM calls TDR, so I don't think we need to update anywhere else
> [DC-534] Handle updated TDR forbidden response

- service/src/main/java/bio/terra/workspace/service/status/BaseStatusService.java
This upgrades the log message for stale status to fire an alert in any environment with log-based alerting configured, instead of just logging a warning. This should also be a more informative message for oncall engineers.
> [PF-2013] Add log based alert for stale status

- service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
- service/src/main/java/bio/terra/workspace/common/utils/FlightBeanBag.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/ControlledAzureStorageResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStep.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStepTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-503)
We need to set CORS allowed origins, methods and headers on Azure storage containers so calls from the browser succeed.
* Wires up the call to Azure to set the needed values on the owning storage account at the time of creation. The allowed origins are config'ed out and default to none (these will be set via a subsequent terra-helmfile PR).
> First cut at adding optional CORS support for azure storage accounts

- openapi/src/common/schemas.yaml
workspaceId, resourceId, name and types should always be populated.
> Mark some resource metadata as required.

- .github/workflows/test.yml
- service/gradle/testing.gradle
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/BaseAzureUnitTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/CreateAzureDiskStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/GetAzureDiskStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/CreateAzureIpStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/GetAzureIpStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/CreateAzureNetworkStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/GetAzureNetworkStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/CreateAzureRelayNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/GetAzureRelayNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/BaseStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/CreateAzureStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/GetAzureStorageStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/CreateAzureStorageContainerStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/VerifyAzureStorageContainerCanBeCreatedStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
- service/src/test/resources/application-azure-unit-test.yml
The new controller test Doug added showed up a problem with the test categories. The new test needs the MockMvc to test the REST API interface. The `azure` tag is set up for a _connected_ test, so it does not support the MockMvc.
The default for `azure-enabled` is true, but we still need support for `azure-enabled` as false. So we still need to segregate the Azure tests.
My solution in this PR is:
1. Add a new tag `azure-unit`
2. Add a new profile `azure-unit-test`
3. Add a new property file that sets `azure-enabled`:  `application-azure-unit-test`
4. Added a fourth entry to the test matrix so these tests run as part of PR qualification as well as overnight.
I removed all of the `@ActiveProfiles("azure")` from a bunch of Azure tests. There is no profile-based code or configuration. The …
> [PF-2025] Add azure-unit-test; remove unusaed 'azure' profile

- service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ControlledGcpResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/FolderApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/BaseTest.java
- service/src/test/java/bio/terra/workspace/common/BaseUnitTest.java
- service/src/test/java/bio/terra/workspace/common/StairwayTestUtils.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/TestUtils.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/CreateGcsBucketStepTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationConfigurationTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Existing "Clone controlled GCS bucket" connected/integration tests use `CloningInstructions.COPY_RESOURCE`. In `ControlledGcpResourceApiControllerConnectedTest.java`, add tests for other `CloningInstructions` enum values, in preparation for implementing `CloningInstructions.COPY_REFERENCE`.
Also make `MockMvcUtils` a spring Component. This way, users don't have to pass in `mockMvc`, `objectMapper`. In order to make `MovkMvcUtils` a spring Component, I had to add `@AutoConfigureMockMvc` to `BaseTest`. I also removed `@AutoConfigureMockMvc` from individual tests.
> [PF-1930] Add tests for cloning controlled GCS bucket with different cloning instructions

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedBigQueryResourceLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedDataRepoSnapshotLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedGcsResourceLifecycle.java
- integration/src/main/java/scripts/utils/BqDatasetUtils.java
- integration/src/main/java/scripts/utils/CommonResourceFieldsUtil.java
- integration/src/main/java/scripts/utils/DataRepoUtils.java
- integration/src/main/java/scripts/utils/GcsBucketObjectUtils.java
- integration/src/main/java/scripts/utils/GcsBucketUtils.java
- integration/src/main/java/scripts/utils/GitRepoUtils.java
- integration/src/main/java/scripts/utils/NotebookUtils.java
- openapi/src/common/schemas.yaml
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/utils/MapperUtils.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledResourceControllerBase.java
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/model/ResourceLineageEntry.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/datareposnapshot/ReferencedDataRepoSnapshotResource.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ControlledGcpResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ReferencedGcpResourceControllerTest.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ReferenceResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/TestUtils.java
Mostly added test coverages.
There is no unit test at the referenced resource controller level so I added referenced resource creation test for each type of resources. I also unified the commonFields construction for referenced resources; this is to eliminate risk of accidentally missing one of the referenced resources when adding new fields. 
I also added controllerConnectedTest for gcp resources creation. the code path is the same for azure and gcp so that should be somewhat sufficient. 
i didn't add much to the integration test because of the thorough test coverage on the unit test level. 
`spotbugsMain` has a couple non-blocking complains so I addresses them as well.
> PF-1965: Add properties fields on resource creation

- openapi/src/parts/folder.yaml
- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/FolderApiController.java
- service/src/main/java/bio/terra/workspace/db/FolderDao.java
- service/src/main/java/bio/terra/workspace/service/folder/FolderService.java
- service/src/main/java/bio/terra/workspace/service/folder/model/Folder.java
- service/src/main/resources/db/changelog.xml
- service/src/main/resources/db/changesets/20220920_add_folder_properties_column.yaml
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/FolderApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/db/FolderDaoTest.java
This is to support use case such as short descriptions. In the future, they can support version, tags, etc, similar to workspace.
on folder creation with terra-short-description -> this is a monkey
```
{
"id": "4cca6642-fb3a-450f-8fb9-1f4299dc5a08",
"displayName": "foo",
"properties": [
{
"key": "terra-short-description",
"value": "this is a monkey"
}
]
}
```
after update properties with haha -> yoyo
```
{
"folders": [
{
"id": "4cca6642-fb3a-450f-8fb9-1f4299dc5a08",
"displayName": "foo",
"properties": [
{
"key": "haha",
"value": "yoyo"
},
{
"key": "terra-short-description",
"value": "this is a monkey"
}
]
}
]
}
```
after delete properties "haha"
```
{
"folders": [
{
"id": "4cca6642-fb3a-450f-8fb9-1f4299dc5a08",
"displayName": "foo",
"properties": [
{
"key": "short-description",
"value": …
```
> PF-1984: add folder properties

- DEVELOPMENT.md
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CreateStorageTransferServiceJobStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/StorageTransferServiceUtils.java
- service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ControlledGcpResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/TestUtils.java
- service/src/test/java/bio/terra/workspace/connected/ResourceConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/connected/WorkspaceConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlightTest.java
While working on implementing cloning controlled bucket -> referenced, I wrote a test for CloneControlledGcsBucketResourceFlight undo. (There is no existing test for undo.) It turns out that existing undo fails with dismal exception:
```
2022-09-21 13:33:20.472  ERROR 87902 --- [pool-8-thread-2] bio.terra.stairway.StepResult            : Step Result exception
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://storagetransfer.googleapis.com/v1/transferJobs/wsm-owfmSCImSDe8CFS3Aai_8w
{
"code": 400,
"errors": [
{
"domain": "global",
"message": "Updating a deleted transfer job is not allowed.",
"reason": "failedPrecondition"
}
],
"message": "Updating a deleted transfer job is not allowed.",
"status": "FAILED_PRECONDITION"
}
DISMAL FAILURE: …
```
> [PF-1930] Fix dismal failure with CreateStorageTransferServiceJobStep undo

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/GrantPetUsagePermissionStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
This undo step failed (causing dismal Stairway failures) if the `CreateControlledResourceFlight` creating an AI Notebook was triggered via pet SA credentials instead of end-user credentials, which frequently happened for users working from a notebook.
The root cause was that Sam's `getUserIds` endpoint throws a 404 if it's called with a pet SA email. This fix works by fetching the end-user email from Sam, similar to what we do in the `do` step. In the future (PF-1001) this would be a good spot for a `SamUser` object instead of an `AuthenticatedUserRequest` to save some extra calls to Sam.
> [PF-1980] Fix GrantPetUsagePermissionStep undo

- openapi/src/common/parameters.yaml
- openapi/src/parts/controlled_azure_storage_container.yaml
- scripts/write-config.sh
- service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/ControllerValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
Allows specification of the SAS token duration (not including the padding we add to the beginning of the time to account for clock drift) in seconds. Maximum allowable value is set in configuration, currently 24 hours per devsecops recommendation.
> [WOR-502] Allow specification of SAS token expiration.

- integration/src/main/java/scripts/testscripts/ReferencedBigQueryResourceLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedGcsResourceLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedGitRepoLifecycle.java
- integration/src/main/java/scripts/utils/BqDataTableUtils.java
- integration/src/main/java/scripts/utils/BqDatasetUtils.java
- integration/src/main/java/scripts/utils/GcsBucketUtils.java
- integration/src/main/java/scripts/utils/GitRepoUtils.java
- openapi/src/parts/referenced_gcp_big_query_data_table.yaml
- openapi/src/parts/referenced_gcp_big_query_dataset.yaml
- openapi/src/parts/referenced_gcp_gcs_bucket.yaml
- openapi/src/parts/referenced_gcp_gcs_bucket_object.yaml
- openapi/src/parts/referenced_git_repo.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
Since the controlled (gcp) resources have the same behavior, it avoids having to manually retrieve the updated information when dealing with referenced resources.
> [PF-1987] Return resource information when updating referenced resources.

- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstancePostStartup.java
- integration/src/main/java/scripts/utils/NotebookUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/CustomGcpIamRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
- service/src/test/java/bio/terra/workspace/service/folder/FolderServiceTest.java
example log for the cloud console: 
```
Sep 29 18:22:46 testnotebook4 c2d-startup[431]: Registering with Proxy...
Sep 29 18:22:46 testnotebook4 c2d-startup[431]: Proxy URL from the config: https://us-central1.notebooks.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14
Sep 29 18:23:08 testnotebook4 c2d-startup[431]: ERROR: (gcloud.compute.instances.describe) Could not fetch resource:
Sep 29 18:23:08 testnotebook4 c2d-startup[431]:  - Required 'compute.instances.get' permission for 'projects/terra-vdevel-clean-celery-1754/zones/us-central1-a/instances/testnotebook4'
Sep 29 18:23:08 testnotebook4 c2d-startup[431]: Proxy Registration failed. Unable to get Service Account from VM
```
Missing permission `compute.instances.get`. I tried adding it at the resource level but it didn't …
> PF-2060: Add missing permission that has broken notebook creation.

- openapi/src/common/schemas.yaml
- openapi/src/parts/controlled_gcp_gcs_bucket.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/SetReferencedDestinationGcsBucketInWorkingMapStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/SetReferencedDestinationGcsBucketResponseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/model/CloningInstructions.java
- service/src/main/java/bio/terra/workspace/service/resource/model/ResourceLineageEntry.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/create/CreateReferenceMetadataStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/serdes/ControlledGcsBucketResourceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtilsTest.java
Manually tested:
```
{
"resources": [
{
"metadata": {
"workspaceId": "53f383ba-c91c-4b86-935f-b52f0bd1688b",
"resourceId": "46bd7f0a-f4cb-4118-83ef-0b5be07343b6",
"name": "dest-bucket",
"resourceType": "GCS_BUCKET",
"stewardshipType": "REFERENCED",
"cloudPlatform": "GCP",
"cloningInstructions": "COPY_REFERENCE",
"resourceLineage": [
{
"sourceWorkspaceId": "53f383ba-c91c-4b86-935f-b52f0bd1688b",
"sourceResourceId": "a7895e05-61ba-40a1-b235-28d52d6ac435"
}
],
"properties": []
},
"resourceAttributes": {
"gcpGcsBucket": {
"bucketName": "source-bucket-terra-wsm-t-rapid-walnut-999"
}
}
},
{
"metadata": {
"workspaceId": "53f383ba-c91c-4b86-935f-b52f0bd1688b",
"resourceId": "a7895e05-61ba-40a1-b235-28d52d6ac435",
"name": "source-bucket",
"resourceType": "GCS_BUCKET",
"stewardshipType": …
```
> [PF-1930] Implement cloning controlled bucket to referenced

- openapi/src/parts/controlled_gcp_big_query_dataset.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/SetReferencedDestinationGcsBucketInWorkingMapStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/SetReferencedDestinationGcsBucketWorkingMapStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/SetReferencedDestinationBigQueryDatasetInWorkingMapStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/SetReferencedDestinationBigQueryDatasetResponseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/UpdateBigQueryDatasetStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextUnitTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlightTest.java
Similar to #835. Manually tested:
```
{
"resources": [
{
"metadata": {
"workspaceId": "4613d18c-555c-489e-bd54-5918e95b8947",
"resourceId": "b33afd14-7d50-4a76-a6f7-4e058c852909",
"name": "dest-dataset",
"resourceType": "BIG_QUERY_DATASET",
"stewardshipType": "REFERENCED",
"cloudPlatform": "GCP",
"cloningInstructions": "COPY_REFERENCE",
"resourceLineage": [
{
"sourceWorkspaceId": "4613d18c-555c-489e-bd54-5918e95b8947",
"sourceResourceId": "b6a09f7f-7851-4d69-8279-e640e5f6a87a"
}
],
"properties": []
},
"resourceAttributes": {
"gcpBqDataset": {
"projectId": "terra-wsm-t-sparkly-lime-5340",
"datasetId": "melchang202210101732"
}
}
},
{
"metadata": {
"workspaceId": "4613d18c-555c-489e-bd54-5918e95b8947",
"resourceId": "b6a09f7f-7851-4d69-8279-e640e5f6a87a",
"name": "source-dataset", …
```
> [PF-1930] Implement cloning controlled dataset to referenced

- integration/README.md
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
From the discussion https://github.com/DataBiosphere/terra-workspace-manager/pull/758#discussion_r942645004. This PR is for illustrative purposes, if it's useful then someone from the WSM should take on the task of creating a ticket for the work and fixing it up for merging. If not, feel free to close the PR and delete the branch.
You can use the lambda solution, but since the enum members aren't valid at enum declaration time, you need to use a method instead. Since there aren't unit tests for this code I'm not 100% sure I copied everything over correctly.
Also there was a bug with a `log` message using `%s` when it should use `{}`. There is an IntelliJ warning that will catch this error for you.
And there were many unnecessary calls to `toString()` which I removed.
> [PF-2039] Implement the higher role concept in the `WsmIamRole` enum

- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneGcpWorkspaceFlight.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
This change set allows Rawls stage workspaces to be cloned.
- The clone method now accepts a destination workspace id. That id will be used to create the workspace, in the same way the regular create workspace endpoint works.
- The restriction against cloning Rawls workspaces is removed.
- We take the workspace stage from the source and use that as the destination stage.
- We only create a GCP cloud context in the destination if there was a context in the source workspace
- I did not wire in policy service interaction for Rawls workspaces
The hardest part of the change was writing the test :)
----
Based on Melissa's comments I did some test cleanup:
1. Make a common create workspace path for MC and RAWLS
2. Make a common clone workspace method for MC and RAWLS
3. Do not always run a …
> [PF-2096] Enable clone of Rawls workspaces

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
- service/src/main/resources/db/changelog.xml
- service/src/main/resources/db/changesets/20221014_workspace_activity_log_add_index.yaml
I didn't include change_date in index. I figure, having 2 rows with same change_date is extremely rare, so it's ok to sort in those cases.
Thanks for your help Dan, I haven't had much experience with DB slowness. :)
> [PF-2104] Add workspace_id index to workspace_activity_log

- openapi/src/parts/controlled_azure_storage_container.yaml
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/ControlledAzureStorageContainerResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/CreateAzureStorageContainerStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/DeleteAzureStorageContainerStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/VerifyAzureStorageContainerCanBeCreatedStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/resourcemanager/data/BaseStorageContainerRequestData.java
- service/src/test/java/bio/terra/workspace/connected/LandingZoneTestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/TestLandingZoneManager.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/DeleteAzureStorageContainerStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/VerifyAzureStorageContainerCanBeCreatedStepTest.java
- service/src/test/resources/application-azure-test.yml
- service/src/test/resources/application-connected-test.yml
This PR addresses new requirements for Azure storage container creation process. Now it is possible to reuse shared storage account from landing zone to create associated container.
Changes:
-Storage container REST API: storageAccountId is not required
-Update logic for Verify step within azure storage container creation flight
-Update logic for Delete step within azure storage container deletion flight
> Retrofit storage container operations in WSM with LZ integration

- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
This way, if people copy WorkspaceApiControllerTest, they'll copy the cleaned-up version.
The workspace property tests weren't working as expected. Changed them to actually test workspace properties.
> Clean up WorkspaceApiControllerTest

- service/src/main/java/bio/terra/workspace/service/workspace/CloudSyncRoleMapping.java
GCP rolled back their change that requires `compute.instances.get` on  notebook creation.
> PF-2060: Revert back the change

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
For overall using the whole post-startup script test:
Manual test shows below:  
- The cromwell-81.jar is installed in /usr/share/java  
- The cromwell.config is created in home directory
- Remove the cromwell folder
- Also for writing the ${CROMWLL_JAR} into the bash file successful.
> [PF-1839] [PF-2106] add the cromwell generation command line and install the cromwell.jar in usr/shared/java 

- service/src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileBpmConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileServiceTest.java
BPM isn't deployed at Verily yet, so these tests (which assume a valid BPM server is available) break, regardless of flag values. We should remove these annotations once one is available, which should be within a week or two.
> [PF-2074] Disable BPM connected tests if BPM is not configured

- service/src/main/java/bio/terra/workspace/db/FolderDao.java
- service/src/main/java/bio/terra/workspace/service/folder/flights/DeleteFolderRecursiveStep.java
- service/src/test/java/bio/terra/workspace/db/FolderDaoTest.java
needed as an undo step for https://github.com/DataBiosphere/terra-workspace-manager/pull/853.
Without this method, we need to iterate through all the top level folders.
> [PF-2059] add deleteFolders to FolderDao

- service/src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileBpmConnectedTest.java
In #874 I disabled `SpendProfileBpmConnectedTest` methods individually in environments where BPM is disabled, but I forgot that `@Before/AfterAll` will still run (and make calls to BPM) even if no test methods are enabled.
> [PF-2074] Fix disabled SpendProfileBpmConnectedTest

- service/src/main/java/bio/terra/workspace/app/configuration/external/FeatureConfiguration.java
- service/src/main/resources/application.yml
The BPM enabled config values in the YAML do not line up with what the `FeatureConfiguration` class is looking for.
> Use correct config value names for BPM flagging

- integration/src/main/java/scripts/testscripts/FolderLifecycle.java
- openapi/src/common/responses.yaml
- openapi/src/common/schemas.yaml
- openapi/src/parts/admin.yaml
- openapi/src/parts/folder.yaml
- service/src/main/java/bio/terra/workspace/app/controller/AdminApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/FolderApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/shared/JobApiUtils.java
- service/src/main/java/bio/terra/workspace/service/folder/FolderService.java
- service/src/main/java/bio/terra/workspace/service/folder/flights/DeleteFolderRecursiveStep.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/test/java/bio/terra/workspace/app/controller/FolderApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/folder/FolderServiceTest.java
DELETE /api/workspaces/v1/{workspaceId}/folders/{folderId}:
{
"jobReport": {
"id": "fc6d2ff2-f421-4f3c-8e19-11fe443a2ad9",
"description": "Delete folder 6839d139-8bb6-4f78-99d3-1852203f06cd in workspace 52ee1aea-9bbe-430b-892e-e524c3b92c8d",
"status": "RUNNING",
"statusCode": 202,
"submitted": "2022-10-27T19:31:29.823243Z",
"resultURL": "http://localhost:8080"
}
}
GET /api/job/v1/jobs/{jobId}
{
"id": "fc6d2ff2-f421-4f3c-8e19-11fe443a2ad9",
"description": "Delete folder 6839d139-8bb6-4f78-99d3-1852203f06cd in workspace 52ee1aea-9bbe-430b-892e-e524c3b92c8d",
"status": "SUCCEEDED",
"statusCode": 200,
"submitted": "2022-10-27T19:31:29.823243Z",
"completed": "2022-10-27T19:31:31.775950Z",
"resultURL": "http://localhost:8080"
}
> PF-2159: change delete folder endpoint to async

- integration/src/main/java/scripts/testscripts/FolderLifecycle.java
- openapi/src/parts/folder.yaml
- service/src/main/java/bio/terra/workspace/app/controller/FolderApiController.java
- service/src/test/java/bio/terra/workspace/app/controller/FolderApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
@rogerwangcs pointed this out that the rest of the async endpoint are using POST.
> PF-2159: add a post endpoint for delete async.

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
- service/src/main/java/bio/terra/workspace/db/model/DbWorkspaceActivityLog.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/connected/UserAccessUtils.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/resources/application-connected-test.yml
Reverts DataBiosphere/terra-workspace-manager#892
PF-2176 hard-coded some subject IDs specific to broad-dev. Verily downstream tests failed.
> Revert "PF-2176: Log workspace update policies endpoint"

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/BlobCopier.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/SasTokenOptions.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CloneControlledAzureStorageContainerResourceFlight.java
- service/src/test/java/bio/terra/workspace/app/controller/CreateAzureStorageContainerSasTokenTest.java
- service/src/test/java/bio/terra/workspace/common/BaseAzureUnitTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
https://broadworkbench.atlassian.net/browse/TOAZ-264
-Fix issue: handle situation when storage container belongs to shared storage account from landing zone
-Refactoring
> SAS token API does not work with storage containers created in Landing Zone storage accounts

- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
For workspaces that are created before the logging exists, there are no entries of them in the log table. So we arbitrarily returns unknown for actor email and a MIN timestamp for the date.
> PF-1968: make created_by and last_changed_by required field

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/RetrieveDestinationStorageAccountResourceIdStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/RetrieveDestinationStorageAccountResourceIdStepTest.java
When we go to pull the storage account for the destination workspace, we are not resilient when the landing zone is not found. We need to catch the resulting `LandingZoneNotFoundException` and fall back to the workspace's storage account if present. [This](https://github.com/DataBiosphere/terra-landing-zone-service/blob/7f39f4e0eca3a48b4bb348366bd2bcc40d2a74ed/service/src/main/java/bio/terra/landingzone/db/LandingZoneDao.java#L180) is the line in the LZ code we're bumping into.
> [WOR-624] Handle landing zone not found when cloning a container

- service/src/test/java/bio/terra/workspace/service/folder/FolderServiceTest.java
The set up is run @beforeEach and it create controlled and referenced resources so it takes a long time.
It used to take 13 m, now it takes 3 min.
> [PF-2245] shorten FolderServiceTest

- service/src/test/java/bio/terra/workspace/service/admin/AdminServiceTest.java
This connected test has a long set up and tear down (creating and deleting workspace with GCP context). So I merged some tests and remove the setUp from running @beforeEach. One of the test is testing what happens if there are no workspaces and it doesn't need to wait for the set up. 
taking 7 min to finish now.
> PF-2249: make adminservicetest shorter

- service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
- service/src/test/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHookTest.java
- service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
- service/src/test/java/bio/terra/workspace/connected/WorkspaceConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/StoreControlledResourceMetadataStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/ApplicationServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AzureWorkspaceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/DeleteAzureContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/DeleteGcpContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromWorkspaceFlightTest.java
When i add a new required fields in Workspace, i have to go to all the test files and update them. So I created this method to centralize the creation of default workspace.
> PF-2250: Introduce a new method createWorkspace in WorkspaceFixtures

- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/GcsBucketCloneTestFixtures.java
this is so that when I add a new required field for WsmResources, I don't need to go find all the random places that create resource and update them all.
Most of them are calling the write method with only two exceptions.
> PF-2250: When creating a common field in a resource, use the helper method

- service/src/test/java/bio/terra/workspace/common/utils/TestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
Avoid name conflicts for Azure storage account name during parallel test run
> Randomize storage account name to avoid conflicts

- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
It's just too painful to get PR pass all tests in this repo ATM. since the ticket is actively working on, I'm disabling this test.
> TOAZ-286: disable the test with a todo

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneAllFoldersStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneAllFoldersStepTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
DESTINATION_WORKSPACE_ID value is never set for CloneGcpWorkspaceFlight. So if we undo here, we will throws exception.
> PF-2260: undo should read WORKSPACE_ID value

- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
The test are all read-only (GET and LIST) so we don't need to create and delete the workspace per test.
From local run, the test now takes 18 sec. It took 58 sec before.
> PF-2294: change the set up to beforeAll and afterAll

- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ReferenceResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
Tests uncovered issue:
- We allowed cloning referenced resource where request had COPY_DEFINITION, COPY_RESOURCE. Changed to throw 400.
Also:
- Increased # retries for `createAiNotebookInstanceDo()`. After Dan's fix (#937), test still flaked after exhausting all ten retries ([build scan](https://scans.gradle.com/s/ymg4fcqexjy46/tests/:service:connectedTest/bio.terra.workspace.service.resource.controlled.ControlledResourceServiceTest/createAiNotebookInstanceDo()?top-execution=1)).
> [PF-819] Flesh out tests for cloning referenced BQ dataset

- .github/workflows/tag-publish.yml
Remove usage of the old update-service from terra-helmfile and instead use our new tooling directly, courtesy of the "client" reusable workflows from Sherlock's repo.
The first one just tells us that the version exists, and lets us ingest a bunch of info about the git branch and commit. This is super useful for BEEs and our mechanisms to generate changelogs.
The second one puts the version into our dev environment. The improvement here is that it actually will directly sync the dev environment (which didn't happen in the old mechanism, the version would only get applied overnight). If WSM fails to become healthy after the change, this action will error--should help catch issues sooner.
> [DDO-2520] Report WSM versions to Broad DevOps "the new way"

- integration/src/main/java/scripts/utils/NotebookUtils.java
`PrivateControlledAiNotebookInstancePostStartup` has been failing due to IAM propagation delay, this adds retry support.
> [PF-2320] Retry 403 on nightly tests

- service/src/main/java/bio/terra/workspace/amalgam/tps/TpsApiDispatch.java
Policy merge wasn't writing to the target policy.
Probably should have an integration test for this which we can add after the separate service is available.
> PF-2217: policy merge saves to target

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
I'm no longer seeing the CloneWorkspace failure from https://github.com/DataBiosphere/terra-workspace-manager/pull/950 . Now I'm seeing a flaky failure that is fixable.
Example flake:
https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/3679977850/jobs/6225047800
Relevant error:
```
2022-12-12T21:40:34.6177620Z com.google.cloud.bigquery.BigQueryException: Access Denied: Project terra-wsm-t-snappy-gourd-637: User does not have bigquery.jobs.create permission in project terra-wsm-t-snappy-gourd-637.
2022-12-12T21:40:34.6179398Z 	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
2022-12-12T21:40:34.6180273Z 2022-12-12 21:40:34.587   INFO   --- [pool-3-thread-1] bio.terra.testrunner.runner.RetryLogic   : Retry attempt 1. …
```
> Fix CloneWorkspace integration test flakiness

- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
It is constantly broken, so get it out of the way while we debug it.
> [PF-2350] Ignore createAiNotebookDo test

- .github/workflows/release-promotion-tests.yml
The information that used to be tracked in terra-helmfile's `versions/` files is now tracked in an API service called Sherlock.
We recently [deleted](https://github.com/broadinstitute/terra-helmfile/commit/07c49af3562e0c3355f2f1185ade4609e655e10f) those files from terra-helmfile, but that seems have broken TestRunner.
This PR adds a new step to WSM's alpha promotion tests that will generate fake versions files based on the information in Sherlock, for backwards compatibility. Ideally TestRunner should be updated to pull information directly from Sherlock.
> DDO-2528 Add shim to generate fake terra-helmfile versions file

- .github/workflows/tag-publish.yml
- HOTFIX.md
- service/local-dev/skaffold.yaml.template
This needs to be merged (and a new image needs to be published) before the equivalent helmfile change can merge
> [PF-2168] Move from terra-kernel-k8s to broad-dsp-gcr-public

- service/src/test/java/bio/terra/workspace/service/workspace/AzureWorkspaceTest.java
The hardcoded LZ is broken, so disable the test. Ticket TOAZ-286 is tracking the problem.
> [PF-2360] Disable cloneAzureWorkspaceWithContainer test

- openapi/src/parts/controlled_aws_bucket.yaml
- openapi/src/parts/controlled_aws_sagemaker_notebook.yaml
Current endpoint - 
- /api/workspaces/v1/{workspaceId}/resources/controlled/aws/buckets/{resourceId}/getConsoleLink
- /api/workspaces/v1/{workspaceId}/resources/controlled/aws/buckets/{resourceId}/getCredential
- /api/workspaces/v1/{workspaceId}/resources/controlled/aws/sagemaker-notebooks/{resourceId}/getConsoleLink
- /api/workspaces/v1/{workspaceId}/resources/controlled/aws/sagemaker-notebooks/{resourceId}/getCredential
- /api/workspaces/v1/{workspaceId}/resources/controlled/aws/sagemaker-notebooks/{resourceId}/getProxyUrl
Reason for change - 
- https://restfulapi.net/
- https://blog.dreamfactory.com/best-practices-for-naming-rest-api-endpoints/
Recommended to omit the operation name ‘get’
No other changes in java code are needed since operationId remain the same
> [TERRA-192] Update 'GET' endpoint names from 'get*' to '*"

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
The CloneWorkspace integration test was using TPS, even in environments where TPS was disabled. That led to failures.
This change removes the use of policy in that test.
> [no ticket] No policy usage in integration tests

- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateGcpContextFlightV2.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreatePetSaStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WaitForProjectPermissionsStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
Currently, creating a GCP cloud context involves polling GCP using the user's credentials to determine when cloud permissions are fully synchronized. However, this means that the user provided credentials must have the `cloud-platform` OAuth scope. This breaks the CLI, which intentionally does not include this scope for user auth tokens (as it gives broader permissions than we want for Terra).
I've switched this polling to use the calling user's pet SA instead, as we always generate pet tokens with cloud-platform scope. There was already a step in the flight to create the pet SA for the calling user, so the account is guaranteed to exist.
> [PF-2333] Remove cloud-platform requirement for creating context

- integration/src/main/resources/suites/FullIntegration.json
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
This PR removes/disables failing tests. We will add them back in as we make the fixes in epic [PF-2429](https://broadworkbench.atlassian.net/browse/PF-2429).
By disabling them, if the remaining tests do fail, we likely have a regression.
[PF-2429]: https://broadworkbench.atlassian.net/browse/PF-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PF-2408] Disable failing tests until fixed

- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/gcsbucket/ReferencedGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/gcsobject/ReferencedGcsObjectResource.java
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferenceValidationUtilsTest.java
Our current database has bucket with name that has underscore in it. It is *allowed* in gcp so they likely has a gcs bucket cloud instance associated with. However, we imposed a rule to not allow underscore for some nextflow reason. that change is *not* backward compatible and makes all those previous workspace with underscore bucket unusable.
Now when those workspaces are not able to be get, delete, update because of this validation error. 
I don't want to just clean up the row in the db because the cloud bucket is still there.
> Use the right validation for existing bucket name

- service/src/main/java/bio/terra/workspace/app/controller/FolderApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/logging/WorkspaceActivityLogService.java
- service/src/test/java/bio/terra/workspace/app/controller/FolderApiControllerTest.java
We backfilled the create date already.
> PF-2445: use the create date when there's no log for an old resource in terra

- .github/workflows/run-integration-suite.yml
- .github/workflows/workflow-tester.yml
- integration/src/main/java/scripts/testscripts/ControlledApplicationPrivateGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledApplicationSharedGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- integration/src/main/java/scripts/utils/GcsBucketAccessTester.java
- integration/src/main/resources/suites/TempTestSuite.json
This PR takes a stab at fixing up the access tester.
I changed the check code so that it would just check and not assert. Split out the wait and nowait cases, so instead of setting the boolean, we just call `doNoWait` for the "cannot XXX" cases. (h/t Yu).
I renamed the check methods to assertXXX and put the assert at the top level. A little hacky using the String to determine error or not, but it works.
I added a method that I plan to use in remove-user testing. Kicking off the PR now so you can review it and find out if it breaks any existing PR tests. In the meantime, I am locally running broken tests that use the tester to see if they behave better.
> [PF-2442] fix access tester

- openapi/src/parts/folder.yaml
- service/src/main/java/bio/terra/workspace/app/controller/AdminApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/Alpha1ApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/FolderApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/JobsApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/PolicyApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
- service/src/main/java/bio/terra/workspace/app/controller/ResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApplicationApiController.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
- service/src/main/java/bio/terra/workspace/service/logging/WorkspaceActivityLogService.java
Also delete a deprecated endpoint.
@rogerwangcs confirmed that Axon UI has stopped using that endpoint.
> PF-1953: Add trace to all controller method

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
CloneWorkspace flaked twice last night:
https://github.com/verily-src/terra-service-ws-manager/actions/runs/4061783399/jobs/6992138839
In both cases, this [call to getWorkspace()](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/integration/src/main/java/scripts/testscripts/CloneWorkspace.java#L376) failed with `java.io.IOException: Connection timed out`. Test logs hang for ~15 mins:
```
2023-02-01T07:15:48.5275230Z 2023-02-01 07:15:48.413   INFO   --- [pool-3-thread-1] scripts.utils.ClientTestUtils            : Operation Clone Workspace succeeded
2023-02-01T07:31:44.6188029Z javax.ws.rs.ProcessingException: java.io.IOException: Connection timed out
2023-02-01T07:31:44.6189105Z 	at org.glassfish.jersey.jdk.connector.internal.JdkConnector.apply(JdkConnector.java:74) …
```
> [PF-2079] Add retry to CloneWorkspace test getWorkspace()

- service/src/main/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHook.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHookTest.java
So the log is written on the destination workspace id. But the change_subject_id should be the source because that is what is cloned.
> PF-2468: Correct clone log

- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/GcpUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/ControlledAzureDiskResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/ip/ControlledAzureIpResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/network/ControlledAzureNetworkResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceResource.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureVmTest.java
- service/src/test/java/bio/terra/workspace/common/utils/GcpUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
The previous commit broke 2 things and was reverted.
1) Creating Azure workspaces - since they don't pass a region to validate
2) Working with GCP workspaces created without policies - caused policy not found exceptions.
This PR re-introduces the changes to support regional policy checks, but also fixes those two pieces.
This is like the previous PR with a couple small changes I'll call out.
> PF-2172: Integrate regional policy check to controlled resource create (re-add)

- .github/workflows/test.yml
We didn't run tests or Codacy checks for bump builds. But we missed adding that condition when we switched to sonarqube.
> Skip sonarqube for bump builds

- openapi/src/parts/controlled_azure_batch_pool.yaml
- service/src/main/java/bio/terra/workspace/common/utils/MapperUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/ControlledAzureBatchPoolResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/CreateAzureBatchPoolStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/model/BatchPoolUserAssignedManagedIdentity.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/exception/UserAssignedManagedIdentityNotFoundException.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerBatchPoolTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/BaseBatchPoolTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/BatchPoolFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/CreateAzureBatchPoolStepTest.java
Adjust payload for user assigned identities for batch pool:
-make resourceGroupName parameter optional
-add clientId parameter. Batch pool API required UAMI name, but when this parameter is set UAMI and it's name will be found using clientId.
-make name and clientId parameters mutually exclusive
> TOAZ-314 Adjust uami payload for azure batch pool creation endpoint

- service/src/main/java/bio/terra/workspace/service/workspace/flight/DeleteAzureContextFlight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/DeleteControlledAzureResourcesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/DeleteControlledAzureResourcesStepTest.java
Ticket: [WOR-757](https://broadworkbench.atlassian.net/browse/WOR-757)
- Users cannot delete controlled application resources in their workspace. We need to check that a user can actually delete all controlled resources in their workspace _before_ we start deleting the cloud objects, not after.
[WOR-757]: https://broadworkbench.atlassian.net/browse/WOR-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WOR-757] Fail Azure workspace/cloud context deletion if there are controlled resources that user cannot delete

- .github/workflows/linter-tests.yml
- .github/workflows/pr-integration.yml
- .github/workflows/test.yml
Only run PR checks when the PR targets main/master branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
> [PF-2478] Only run checks when PR targets 'main' branch

- service/src/main/java/bio/terra/workspace/service/petserviceaccount/PetSaUtils.java
I added a short-cut exit from PetSaUtils.addSaMember that was wrong.
Removing one line fixes the problem.
> PF-2479 Small logic fix in setting actas

- .github/workflows/full-integration-tests.yml
- .github/workflows/full-service-tests.yml
After watching this for a week or so, I'm thinking we are not getting a lot of value running the full suites during the day.
Further, they take github action slots for a long time, causing queue delays. This PR runs them nightly.
> [no ticket] Only run full suites overnight

- client/src/main/resources/swaggercodegen/libraries/jersey2/ApiClient.mustache
This bumps the client's default idle pool timeout from 30s -> 2m, so idle thread pools are not cleaned up while we're still using them. The existing timeout can cause infrequent `Connection Reset` errors for clients who poll slower than once per 30s. See [documentation](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/jdk/connector/JdkConnectorProperties.html#CONTAINER_IDLE_TIMEOUT) for additional param info.
> [PF-2333] Increase default idle pool timeout in client

- service/src/main/java/bio/terra/workspace/service/grant/flight/RevokeStep.java
There are a bunch of revokeGrant flights churning in devel + autopush caused by test workspaces which have been deleted before the grants can be revoked, this should handle them. The `revokeProject` and `revokeResource` methods already check whether the GCP context has been deleted so they don't need any changes.
> [PF-2514] Handle deleted projects in revokeActAs

- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/PolicyFixtures.java
Tests were disabled due to other merge issues. Those have been fixed and these tests should be re-enabled.
> PF-2217: Re-enable merge tests

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
I recently updated this command to require a bucket path parameter. The expectation is that this config file includes a workspace bucket. A user needs to specify the bucket when calling this command. 
I don't think the startup script should have called this command in the first place. Before my change, it produced a config file that wouldn't work because there is no workspace bucket.
> Remove `terra cromwell generate-config` command from post-startup script

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneReferencedResourceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/clone/CloneReferenceResourceStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
Clone referenced resources is now a flight so log will be written in the WorkspaceActivityLogHook instead. `createReferenceResourceForClone` doesn't need to log the activity anymore.
All the clone test in the *controllerTest now also assert that a clone activity is logged in the destination workspace with the source resource id as the changeSubjectId.
i.e. foo is cloned from workspace 1 to workspace 2 by yu.
The log should be: in workspace 2, foo is cloned by yu at <timestamp>.
> PF-2468: Remove redundant logging

- service/src/main/java/bio/terra/workspace/service/workspace/flight/ReleasePrivateResourceCleanupClaimsStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/ResourceRolePair.java
there were two problems.
First, for mysterious reasons of its own, Jackson Json stopped being able to deserialize the `ResourceRolePair`. I added an explicit `@JsonCreator` and properties and it works fine now.
Second, the claim flight undo was failing because a full resource compare was coming up not equal. Apparently the `privateResourceState` was not included in the `equals` method. When I factored that into `WsmControlledResourceFields` I generated a new (comprehensive) equals.
I fixed the code to do the check on resource ID and not the resource contents.
> [PF-2524] Fix ResourceRolePair deser and claims undo compare

- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
Adding group constraint breaks some tests. I also added a ticket for creating new/better tests for group constraint.
This is a quick fix to allow WSM to progress.
> [PF-2548] Disable group policy tests for milestone 1

- .github/workflows/test-env-refresh.yml
This PR works in two parts:
- This actual workflow here will "refresh" the wsmtest-eng BEE and sync the entire environment in ArgoCD
- That "refresh" will actually do something because over in Beehive, tps-wsmtest-eng is configured to get it's app version from tps-dev. The refresh will get the latest tps-dev version and the sync will deploy it.
This action also tries to curl TPS's version endpoint and print it to the GitHub Actions summary so it should be visible without going through logs.
> [DDO-2694] Automatically update TPS in wsmtest-eng BEE

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
Issue came up where we were marking a conflict if a workspace had an existing resource with a region that didn't match exactly one of the regions from TPS. Checking existing resources should be a case-insensitive comparison.
> PF-2533: Case insensitive check for existing resources when performing the merge check

- integration/src/main/java/scripts/testscripts/ImportDataCollection.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
These tests account for the m1 limitations - in that group constraints can only merge if source and destination are equal, or source does not have a group constraint.
Some connected tests needed to be updated for the same logic.
> PF-2498 - Integration tests for group policy merges

- service/src/main/java/bio/terra/workspace/common/utils/ManagementExceptionUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-804)
When a bad file URI is passed as an argument to the azure create VM step, azure will fail out with a `VMExtensionProvisioningError`. 
This error comes back with an HTTP status code of 200. The generic `ManagementException` error [handling logic](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/main/java/bio/terra/workspace/common/utils/ManagementExceptionUtils.java#L39) only treats `4xx` errors as FATAL. 
So, WSM goes to retry the VM creation and then gets a 409 conflict as the moribund VM is still being destroyed. This has the undesirable effect of masking the root cause.
* Adds explicit handling for the `VMExtensionProvisioningError` and immediately fails out the flight, which should make …
> [WOR-804] Handle VM extension provisioning errors

- integration/src/main/java/scripts/testscripts/ImportDataCollection.java
Problem was that the test was creating a workspace with a region policy and then updating the policy to have a group policy. Our update method used to do a replace so the group policy was taken out, but that was a bug that was fixed so now that update leaves the group policy in place and adds a region policy. The rest of the verification was only expecting the group policy to exist.
> Fix for ImportDataCollection test

- service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
When the TPS feature is disabled, WSM's `createWorkspace` requests to Sam have `null` as the auth domain list. This leads to the required field not being serialized, making the request invalid. Instead, WSM should pass an empty list.
> Use an empty list of auth domains instead of null when tps is disabled

- integration/src/main/java/scripts/testscripts/ImportDataCollection.java
- integration/src/main/java/scripts/utils/WorkspaceAllocateTestScriptBase.java
- integration/src/main/java/scripts/utils/WorkspaceAllocateWithPolicyTestScriptBase.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/PolicyFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
In milestone 1, we aren't able to modify auth domains, so TPS won't allow updating group policies. Group policies need to be set during workspace create and can't be changed afterward. The pattern in many of our tests was to create a workspace and then update the policies on the workspace. Those tests need to be updated.
> PF-2563 update tests to not update group policies

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/backfill/RetrieveControlledBigQueryDatasetsLifetimeStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/backfill/UpdateControlledBigQueryDatasetsLifetimeStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
Previously, if the BigQuery datasets had one or two null lifetimes on the cloud, this would cause the flight to crash.
In retrieval:
- Now the `Pair<Long,Long>` can contain nulls in the coordinates,
In update:
- If the coordinate is null, then update with null (instead of throwing a null error upon conversion).
Tests:
- Added two tests to ensure the flight won't crash in both cases.
Re: #1041 (PF-2269).
> [PF-2566] Handle null case in BigQuery lifetime backfill.

- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
> [PF-2571] Use partialEquals instead of equals; cannot repro the  failure

- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
The BQ lifetime backfill picks up more datasets now, which leads to flakiness.
- Cleaned up a few more stray BQ datasets with undefined lifetime
- Removed deep equals comparison (when checking if the created dataset matches the original)
> [PF-2566] Fix BigQuery backfill lifetime test flakiness.

- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
We added input validation in TPS for regions. One of the connected tests used an invalid region and so the test started failing when the input was validated.
> PF-2527: Fix connected test when regions are validated

- service/src/main/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/any/flexibleresource/FlexResourceCreationParameters.java
Adds internal class `FlexResourceCreationParameters` which will be used in creation / cloning flights.
#1133 will be merged on top of this change.
> [PF-2572] Use internal class for flex resource creation parameters.

- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/PolicyFixtures.java
One of the tests was using "eu" as the region for "europe". That test is updated and using the PolicyFixtures instead of a hard coded string.
TPS will also need an update to validate during PAO create.
> Fix tests containing invalid regions

- service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneTest.java
This caused a failure in Verily devel. Oddly enough it's passing in Broad dev, I think it's due to slightly different versions of WSM + TPS
> Fix an invalid region in WSM connected test

- .github/workflows/nightly-tests.yml
- .github/workflows/release-promotion-tests.yml
Replace deprecated commands in GH actions & workflows.
- use actions/setup-java@v3 instead of v2
- use actions/checkout@v3 instead of v2
- use actions/cache@v3 instead of v2
- use actions/upload-artifact@v3 instead of v2
- use setup-node@v3 instead of v2
- use google-github-actions/auth@v1 instead of v0
- use google-github-actions/get-gke-credentials@v1 instead of v0
- use actions/github-script@v6 instead of v5
- replace 'set-output' command
> [TERRA-434] Replace deprecated commands in GH actions & workflows

- .run/Main.run.xml
- integration/src/main/java/scripts/testscripts/MergeGroupPolicies.java
- integration/src/main/resources/configs/integration/MergeGroupPolicies.json
- integration/src/main/resources/suites/FullIntegration.json
- service/src/main/java/bio/terra/workspace/service/policy/TpsUtilities.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/ValidateGroupPolicyAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/flight/clone/CloneReferencedResourceFlight.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneTest.java
A lot of the logic has to happen inside of WSM because there are cases where we should allow groups to merge (like when we are cloning a workspace and adding additional group policies). Other cases - like cloning a reference from a data collection into a workspace should not allow group merge to change the group list. TPS won't know the difference so WSM needs to do that logic.
I also split the Group merging tests from the ImportDataCollection tests into its own set of integration tests.
> PF-2563: Disallow updating of group policies

- service/src/main/java/bio/terra/workspace/service/policy/flight/ValidateGroupPolicyAttributesStep.java
This triggered the `dismal failure` alerts in Verily devel + autopush tests last night. This is a validation-only step, so it can always be "undone" successfully.
> [PF-2616] Stop throwing dismal failure in ValidateGroupPolicyAttributesStep

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
See https://broadworkbench.atlassian.net/browse/WOR-830 for details.
As far as I can tell (searching in repos and posting on [Slack](https://broadinstitute.slack.com/archives/C02GJ782BAA/p1679513399512369)), nobody is currently using the current URL format and injecting the blob name into it. I thought terra-ui was because it generates URLs with blob names in them, but the SAS token it uses (and URL modifies) is actually returned by a call to get the SAS token for the entire container.
> Fix bug with missing blob name in URL (WOR-830).

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
Reverts DataBiosphere/terra-workspace-manager#1165
It turns out that TES is using the URL and injecting the blobName into it. Therefore I am going to revert this change until next week to give them more time to respond to the change (which will also require running Cromwells to be updated).
Slack thread: https://broadinstitute.slack.com/archives/C02GJ782BAA/p1679513399512369
> Revert "Fix bug with missing blob name in URL (WOR-830)."

- integration/src/main/java/scripts/utils/CloudContextMaker.java
- openapi/src/parts/workspace_cloudcontext.yaml
- service/src/main/java/bio/terra/workspace/app/configuration/external/FeatureConfiguration.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCreateCloudContextFlightStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/CreateAzureContextFlight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/CreateDbAzureCloudContextFinishStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/ValidateMRGStep.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/common/utils/ControllerValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/azure/CreateAzureContextFlightTest.java
- service/src/test/resources/application-test.yml
Ticket:  https://broadworkbench.atlassian.net/browse/WOR-743
We previously minimized the usage of Azure workspaces with BPM disabled in https://github.com/DataBiosphere/terra-workspace-manager/pull/1010. The original hope was to remove the feature flag with that PR, but Azure VM integration tests that relied on creating a CloudContext without BPM prevented complete removal of the feature flag.
However, https://github.com/DataBiosphere/terra-workspace-manager/pull/1166 deleted the problematic integration test code, so we can now change Azure CloudContext creation to unconditionally pull MRG coordinates from the BPM spend profile.
> Always run with BPM enabled for Azure (WOR-743).

- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/ValidateWorkspaceAgainstPolicyStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
This test was disabled due to permission propagation insanity. I rewrote it so there are no dynamic grant/revokes.
> [PF-2436] fix ControlledGcpResourceApiControllerBqDatasetTest

- openapi/src/parts/controlled_azure_storage_container.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/BlobCopier.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerBlobsStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/BlobCopierConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerBlobsStepUnitTest.java
Ticket: https://broadworkbench.atlassian.net/browse/WOR-544
Allows passing an array of prefixes that limit which blobs to clone. If the array is not present or is of zero length, all blobs will be cloned.
> Support limiting which blobs to clone (WOR-544).

- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerBlobsStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerBlobsStepUnitTest.java
Follow-up PR from https://github.com/DataBiosphere/terra-workspace-manager/pull/1188.
I confess that my manual testing of this (since we have no full integration test) is pretty sketchy-- I ended up commenting out a ton of code along the path to where I made this fix so that I could verify that the expected value is in the inputParameters map (without properly setting up a billing profile attached to an actual landing zone and creating a storage container in it). I feel like the risk here is low though because in the absence of the prefixes cloning continues to copy everything over.
> Get the resource from the correct map (WOR-544).

- integration/src/main/java/scripts/testscripts/ImportDataCollection.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/ValidateWorkspaceAgainstPolicyStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
PR fixing the two tests I broke.
Integration test: ImportDataCollection depended on a specific error message. I changed the error. This is a compensating change to the test.
ConnectedPlus test: ControlledGcpResourceApiControllerBqDatasetTest needed to use the proper default lifetimes, since that TODO got implemented.
> [PF-2668] test fixes

- service/src/main/java/bio/terra/workspace/service/workspace/flight/RemoveUserFromSamStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/ValidateUserRoleStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/gcp/RemoveUserFromWorkspaceFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/RemoveUserFromWorkspaceFlightTest.java
In #1196 I moved some validation inside `RemoveUserFromSamStep`. However, removing the user's role in the later part of the step means that validation no longer succeeds on rerun, and the step is no longer idempotent. This pulls the validation into a different step first.
This does introduce slightly more time between the validation and role removal, but I think that's worthwhile given the alternative of failing on step retry.
> [PF-2581] Make RemoveUserFromSamStep idempotent

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
The mergeCheck is called in the UI before the actual merge workspace call. That allows us to give users before-hand info about why a merge will not be allowed. However, the mergeCheck API isn't handling group merging.
The merge workspace api does error out in the backend with a policy conflict as expected, but the mergeCheck should also provide the same info in order to be more user friendly.
Added a connected test since the enforcement of group merges needs to happen on the WSM side, so we can't rely on TPS tests to provide coverage for this.
> PF-2689: mergeCheck doesn't note conflicting group policies

- service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
before, if environmentDiscovery is not null and aws is enabled, we reset it to null, oops :)
> TERRA_520: initialize environmentDiscovery if needed and do not reset to null

- openapi/src/common/schemas_aws.yaml
- openapi/src/parts/controlled_aws_s3_storage_folder.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledResourceControllerBase.java
- service/src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/AwsResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/AwsResourceConstant.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/AwsResourceConstants.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3storageFolder/ControlledAwsS3StorageFolderHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/GcpResourceConstants.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandler.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResourceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/CreateGcsBucketStepTest.java
Use the workspace default region (from properties) if the region is not provided in create s3 folder request
```
// create workdpace
{
"id": "feae1f8e-3b00-4dd0-875a-341c9df90ce4",
"stage": "MC_WORKSPACE",
"properties": [
{
"key": "terra-default-location",
"value": "us-east-1"
}
]
}
// create storage
{
"common": { ... },
"AwsS3StorageFolder": {
"region": ""
}
}
// successfully created
{
"resourceId": "feae1f8e-3b00-4dd0-875a-341c9df90ce5",
"AwsS3StorageFolder": {
"metadata": { ...
"controlledResourceMetadata": { ...
"region": "us-east-1"
}, ...
},
"attributes": {
"bucketName": "v0-saas-devel-us-east-1-terra",
"prefix": "dex-s3-425-1"
}
}
}
{
"common": { ... },
"AwsS3StorageFolder": {  }
}
// created successfully
```
Add API for generateClouldName
``` …
```
> [TERRA-504], [TERRA-525] Use default region in S3 creation, add generateCloudName

- openapi/src/common/schemas_aws.yaml
- openapi/src/parts/controlled_aws_s3_storage_folder.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/AwsResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- Add S3CreationParams.folderName. If this is not provided in the input, generate a cloud-compatible name via handler.generateCloudName
Test: without folderName
```
{
"common": {
"name": "dex_s3_425_3-resourceName",
"cloningInstructions": "COPY_NOTHING",
"accessScope": "SHARED_ACCESS",
"managedBy": "USER",
"resourceId": "feae1f8e-3b00-4dd0-875a-341c9df90ce2"
},
"AwsS3StorageFolder": {}
}
// successfully created, resource have storageFolder.folderName populated as well 
{
"resourceId": "feae1f8e-3b00-4dd0-875a-341c9df90ce2",
"AwsS3StorageFolder": {
"metadata": {
"workspaceId": "feae1f8e-3b00-4dd0-875a-341c9df90ce4",
"resourceId": "feae1f8e-3b00-4dd0-875a-341c9df90ce2",
"name": "dex_s3_425_3-resourceName",
"resourceType": "AWS_S3_STORAGE_FOLDER",
"stewardshipType": "CONTROLLED",
... …
```
> [TERRA-523] Add S3CreationParams.folderName

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/RetrieveNetworkNameStep.java
subnetwork item can be null if there's simply no subnet in that location
This is irrelevant to the recent failure in notebook creation as I suspect this issue is always there but we just didn't catch it as no one is creating notebook in tokyo.
> add another null checker

- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetTest.java
This points local and test runs to use the `workspace_manager_v10` RBS pool for GCP projects. This is the same as v9 with the additional BQ Data Transfer API enabled. Now that this API is enabled, I'm also re-enabling tests that require it.
> [PF-2639] Move to v10 RBS pool, re-enable tests using BQ transfer API

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
To mount workspace resources automatically on every vm bootup, we create a systemd service `terra-setup-environment` to run the mount command along with future commands or scripts that we need to run on startup/restart.
> [PF-2656] Create a vm startup script and associated systemd service in post startup script

- service/src/test/java/bio/terra/workspace/service/folder/FolderServiceTest.java
Not share the same FOO_FOLDER_ID because it might not be deleted successfully when the other test fails.
> PF-2728: Fix one of the failing tests

- service/src/main/java/bio/terra/workspace/app/StartupInitializer.java
- service/src/main/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHook.java
- service/src/main/java/bio/terra/workspace/common/logging/model/ActivityFlight.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/service/workspace/gcpcontextbackfill/GcpCloudContextBackfill.java
- service/src/main/java/bio/terra/workspace/service/workspace/gcpcontextbackfill/GcpContextBackfillFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/gcpcontextbackfill/GcpContextBackFillTest.java
When I put in GCP cloud context V2, I made an in-line fixer instead of a backfill. That meant I could never remove the V1.
This adds a backfill for GCP cloud context so I can then remove the V1 cloud context code and the in-line fixer.
> [PF-2725] Backfill GCP cloud context so we can remove V1

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
We want to allow users to modify the instance boot script to turn off behaviors they don't want.
> Set permissions of instance-boot script so the user can edit the file without sudo

- openapi/src/parts/controlled_azure_vm.yaml
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
Before, we were validating the user-specified Azure machine type against this enum: https://learn.microsoft.com/en-us/java/api/com.azure.resourcemanager.compute.models.virtualmachinesizetypes?view=azure-java-stable
However, according to Azure the enum is deprecated and incomplete:
```
The enum data type is currently deprecated and will be removed by December 23rd 2023.
Recommended way to get the list of available sizes is using these APIs:
[List all available virtual machine sizes in an availability set]([https://docs.microsoft.com/rest/api/compute/availabilitysets/listavailablesizes](https://learn.microsoft.com/en-us/rest/api/compute/availabilitysets/listavailablesizes))
[List all available virtual machine sizes in a region]( [https://docs.microsoft.com/rest/api/compute/resourceskus/list] …
```
> [IA-4065] Remove Azure VM size validation

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureSasBundle.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/test/java/bio/terra/workspace/app/controller/CreateAzureStorageContainerSasTokenTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
We will need to be able to correlate container logs stored in Azure with SAS creation requests from the Terra control plane. Azure container logs do not directly capture the SAS for security reasons, instead capturing a sha256 of the SAS's signature. MSFT's [guidance](https://learn.microsoft.com/en-us/azure/storage/blobs/blob-storage-monitoring-scenarios#identifying-the-sas-token-used-to-authorize-a-request) is to compute a sha256 when  minting the token and use that for correlation between sources. 
I tested this locally by minting a token, firing an `azcopy list` request using the token and observing the logged sha256 matches the value from the Azure storage container logs.
* Extracts the signature from the minted token, URL decodes it and computes a sha256 of the value and then logs it
> [WOR-990] Compute and log a sha256 for Azure SAS signature

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
* Sets several file path variables used through
* Emits messages to the log prior to major operations
* Removes a directory change mid-script (in SSH setup)
* Minor logical reordering of a few steps
Biggest changes are to SSH setup
* Uses best practices around directory and file permissions
* Sets the private key without the key showing up in the post-startup log file
* Removes an "ssh-add" that has always been quietly failing
> post-startup.sh code cleanup

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
We are relying on the email from the AuthenticatedUserRequest when logging the user email as we go through the process of minting a SAS token. This leads to inconsistent results as not all request tokens possess an email. We should use sam as the source of truth for the user's email.
* Adds a call to Sam to fetch the user's email and threads it through into the relevant logging statements
> [WOR-993] Get user email from sam rather than relying on email from token for Azure SAS's

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/CustomGcpIamRoleMapping.java
- service/src/main/java/bio/terra/workspace/service/workspace/GcpCloudSyncRoleMapping.java
To enable the CLI to properly display bucket resource metadata when listed or described, and allow mounting referenced buckets where the user only has read access.
> Move storage.bucket.get permission from bucket editor to workspace reader

- openapi/src/parts/controlled_aws_sagemaker_notebook.yaml
- openapi/src/resources/aws_sagemaker_notebook.yaml
- openapi/src/resources/resource_type.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/AwsResourceConstants.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakerNotebook/ControlledAwsSagemakerNotebookAttributes.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakerNotebook/ControlledAwsSagemakerNotebookHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakerNotebook/ControlledAwsSagemakerNotebookResource.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceFamily.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceType.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakerNotebook/ControlledAwsSagemakerNotebookHandlerTest.java
The original AWS sagemaker support PR got over 1.5K line, hence making smaller PRs. 
- Add AWS sagemaker notebook resource, attributes to WSM. 
- Also add the controller and basic plumbing to support the resource & resource.generateCloudName
UT - added
Manual testing - 
Workspace User facing Id | Resource name | Generated name
-- | -- | --
“ws-ufid” | “simple” | "simple-ws-ufid"
“ws-ufid” | "-simp_le&8%$#(){}[]+=_s" | "simp-le8-s-ws-ufid"
ws-ufid_underscore" | “simple” | "simple-ws-ufid-underscore"
> [TERRA-312] Add Sagemaker notebook resource, generateCloudName endpoint

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandler.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandler.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandlerTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketHandlerTest.java
CLI tests relying on name generation are occasionally failing due to invalid names being returned, e.g. `gcsbucketwithoutspecifyingbucketname-terra-wsm-d-genial-orange-` which does not end in an alphanumeric character.
> [PF-2742] Stop generating names ending in dashes

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
Fixes:
- [PF-2705](https://broadworkbench.atlassian.net/browse/PF-2705): Creating cloud environment from Docker image fails in post-startup.sh (restarting Jupyter service)
- [PF-2625](https://broadworkbench.atlassian.net/browse/PF-2625): WSM: Avoid creating many ssh-agent instances on cloud environment
[PF-2705]: https://broadworkbench.atlassian.net/browse/PF-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PF-2625]: https://broadworkbench.atlassian.net/browse/PF-2625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> post-startup.sh: Don't start multiple ssh-agents, don't restart jupyter service for container launches

- integration/src/main/java/scripts/testscripts/EnumerateJobs.java
- integration/src/main/java/scripts/testscripts/EnumerateResources.java
- integration/src/main/java/scripts/testscripts/ImportDataCollection.java
- integration/src/main/java/scripts/testscripts/MergeGroupPolicies.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/utils/TestUtils.java
The `ImportDataCollection` test was re-using a resource name. The sequence of checks changes and the name conflict appeared instead of the policy merge conflict. I made two changes:
1. Generated unique resource names in the test
2. Wrote `TestUtils.assertContains` that does the contains test and logs the contents if there is a mismatch. I replaced current usage with calls to that method in several tests.
> [PF-2743] Fix resource name issue; add logging contain assert

- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotTest.java
Snapshot ids are UUIDs and we are now using them for policy. (TPS requires UUID for an object id)
The `ReferencedGcpResourceControllerDataRepoSnapshotTest` was using a name for the snapshot and that failed.
This PR is a one line change to use a generated UUID instead of a string for the snapshot id.
> [PF-2765] Use UUID for snapshot id in test

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceHandler.java
- AWS sagemaker should use the Workspace.userfacingid and not workspace.uuid
- Add Nullable annotation to generateCloudName(String,String) function, similar to generateCloudName(Uuid,String)
- update resource.validate() method to only allow private notebooks
- leverage validationUtils for resource.validate steps
> Minor fixes to Sagemaker creation

- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/service/admin/AdminService.java
- service/src/main/java/bio/terra/workspace/service/workspace/GcpCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/model/GcpCloudContext.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/admin/AdminServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextUnitTest.java
Currently, calling `createCloudContextStart` puts a placeholder value in the cloud_context DB. This is important for state management, but it does not have any GCP context information (policy groups, project ID) and so deserialization on this placeholder object will fail. IMO we should hide this placeholder as it will not have the fields most callers expect.
This is currently calling `getWorkspace` calls immediately after `createGcpCloudContext` calls to fail with a 400. After the context creation finishes, the `getWorkspace` calls start working again.
> [PF-2768] Handle deserializing placeholder gcp contexts

- service/src/main/java/bio/terra/workspace/service/spendprofile/SpendProfileService.java
Integration tests expect a spend profile named "wm-default-spend-profile" to be present. Now that we have the BPM flag enabled in all environments, this check fails as BPM does not know about that profile. This PR checks the configured map of hardcoded spend profiles prior to reaching out to BPM.
> [WOR-1013] Check for hardcoded spend profile first

- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateAwsSageMakerNotebookStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
The wrong role is attached to SageMaker notebook instances, so they do not have permission to log or access tags.
> TERRA-575: Attach correct role to SageMaker notebook.

- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/WorkspaceDeleteFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
Fixes fir three connectedPlus tests:
1. Disabled `cloneGcpWorkspaceUndoSteps`. It is not testing what it should and we have a test case for create workspace undo, so it is of no use right now.
2. `createMcWorkspaceUndoSteps` is properly triggering the undo now
3. Retry of a step without a retry rule doesn't retry
> [PF-2787] Fix connectedPlus tests to be happy with workspace state

- service/src/main/resources/application.yml
We should retain these longer for better diagnostic visibility.
> [WOR-1027] Retain LZ stairway flights for 90 days

- service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/db/StateDao.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/db/exception/GeneralErrorReportException.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/DeleteWorkspaceStartStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/MakeFlightIdsStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/RunDeleteCloudContextFlightStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/WorkspaceDeleteFlight.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceUnitTest.java
My code to serialize and deserialize exceptions on state changes didn't work. This change adds a method of normalizing the exceptions stored. Added another method that tolerate column contents that cannot be deserialized, rather than breaking workspace retrieval altogether.
Also, this removes the ability to set any exception on a workspace delete failure. That shouldn't have been there in the first place.
> [PF-2791] Change serdes for state exceptions; remove exception from DeleteFailure

- service/src/main/java/bio/terra/workspace/service/policy/PolicyValidator.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
The current validation fails if any groups are set - even if they already exist and aren't being added. This update checks for a change in group policies.
> PF-2793 - updatePolicy should detect if groups change

- service/src/main/resources/application.yml
We need the apptraces table present in long term storage for compliance.
> [WOR-1031] Add AppTraces table for long term storage

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
[Relevant ticket ](https://broadworkbench.atlassian.net/browse/WOR-1006)
We would like to more easily tie the storage access logs in Azure together with the WSM logs as captured in GCP. Today that requires a SHA256 from the SAS request (or the corresponding blob log entry in Azure). This works, but is cumbersome. We are going to start including the Sam subject ID in the SAS so we can more easily search for logs related to a particular user in both systems.
* Pulls the request user's subject ID from Sam and sets it as the [content disposition value](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.sas.sasqueryparameters.contentdisposition?view=azure-dotnet) when minting a SAS token. This is technically not what the header is for, but given that we do not serve files directly in …
> Add content disposition parameter to SAS

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
[`plotnine`](https://pypi.org/project/plotnine/) is installed by default in CWB. Its absence in VWB makes it difficult to port workspaces from CWB.
Confirmed this works in VWB Primary Clarifier workspace environments.
Fixes [PF-2798](https://broadworkbench.atlassian.net/browse/PF-2798)
[PF-2798]: https://broadworkbench.atlassian.net/browse/PF-2798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Install plotnine library in post-startup script

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
Includes a small fix where we were writing the "END: Terra-specific customizations" comment twice to the `~/.bash_profile` (instead of once to the notebook config file).
> [PF-2820] post-startup: write to the .bashrc instead of .bash_profile

- openapi/src/parts/controlled_aws_s3_storage_folder.yaml
- openapi/src/parts/controlled_aws_sagemaker_notebook.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResource.java
For s3 storage folders and sagemaker notebook resources:
- Add update endpoints to swagger
- Add update controller method that calls update resource flights with just common update parameters (name, description)
- Remove error throw from s3 folder and sagemaker resource `updateSteps`
- leaving `updateSteps` todos up if/when we need to add cloud resource update steps.
Since these endpoints only call the shared update resource flight without any additional steps, how would we test?
Tested locally:
PATCH `/api/workspaces/v1/[workspaceId]/resources/controlled/aws/storageFolder/[resourceid]`
```
request body:
{
"name": "new-aws-storage-folder",
"description": "testing description"
}
response body:
{
"metadata": {
"workspaceId": "0d9d305a-bb09-4da0-a3d6-95d0d448a810",
"resourceId": …
```
> Add update endpoints for aws s3 storage folder + sagemaker notebook

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/model/CommonUpdateParameters.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResource.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceBucketTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/AzureResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/GcpResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/StateTestUtils.java
FullIntegration failed because my new workspace/cloud context state check was requiring a cloud context for the target of a clone, even if the clone was making a reference.
This fix adds a new validation method that uses the cloning instructions to decide how much to check.
A couple of consequences of this change. Previously, the effective cloning instructions were calculated in the service layer. Now I need it in the controller. To compute it, I need to fetch the actual resource. What I found was that another validation was already returning the resource, but it was not received in a variable. So the code went and retrieved it **again** in the service layer. So I changes service APIs to take the whole resource and the computed cloning instructions.
A couple of unit tests failed, because …
> [PF-2825] Fix resource clone state checks and test

- service/src/main/java/bio/terra/workspace/app/controller/AdminApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControllerBase.java
- service/src/main/java/bio/terra/workspace/app/controller/PolicyApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/shared/WorkspaceApiUtils.java
- service/src/main/java/bio/terra/workspace/common/utils/Rethrow.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/logging/WorkspaceActivityLogService.java
- service/src/main/java/bio/terra/workspace/service/petserviceaccount/PetSaService.java
- service/src/main/java/bio/terra/workspace/service/policy/PolicyValidator.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsRetry.java
- service/src/main/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupService.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/AssignManagedIdentityAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDifferentRegionStep.java
- service/src/main/java/bio/terra/workspace/service/spendprofile/SpendProfileService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/service/policy/PolicyValidatorTest.java
- service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/ResourceValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceUnitTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/CreateGcpContextFlightTest.java
This PR adds retries to `TpsApiDispatch`. I considered re-implementing `SamRetry` to use the `RetryUtils`, but decided it wasn't a good fit. Also, `SamRetry` has been working well - it ain't broken, so don't "fix" it.
I looked for a way to share retry code between Sam and TPS. Both are doing exactly the same thing to different instances of `ApiException`. I decided the complexity wasn't worth the effort. So...
- Copied `SamRetry` into `TpsRetry` and cleaned up naming and typing of the `ApiException`.
- Implemented the retry inside of `TpsApiDispatch`
- Copied `SamRethrow` into `Rethrow` and moved it to common utils.
- Global replace of `SamRethrow` with `Rethrow`
- Add `Rethrow` wrapping around all the places where we use TPS that are not in flights. I considered putting the `Rethrow` …
> [PF-2784] Add retries to TpsApiDispatch

- openapi/src/parts/controlled_gcp_ai_notebook_instance.yaml
- openapi/src/parts/controlled_gcp_big_query_dataset.yaml
- openapi/src/parts/controlled_gcp_gcs_bucket.yaml
- openapi/src/parts/referenced_datarepo_snapshots.yaml
- openapi/src/parts/referenced_gcp_big_query_data_table.yaml
- openapi/src/parts/referenced_gcp_big_query_dataset.yaml
- openapi/src/parts/referenced_gcp_gcs_bucket.yaml
- openapi/src/parts/referenced_gcp_gcs_bucket_object.yaml
- openapi/src/parts/referenced_git_repo.yaml
- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
Ran connectedPlus test locally.
> PF-2831: throw 409 when we have a conflicted resource name

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/AwsResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/AzureResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/GcpResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/ControlledAzureBatchPoolResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/ControlledAzureDiskResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/ControlledAzureStorageContainerResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/ControlledBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/model/ControlledResourceFields.java
- service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceFields.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/bqdataset/ReferencedBigQueryDatasetResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/bqdatatable/ReferencedBigQueryDataTableResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/gcsbucket/ReferencedGcsBucketResource.java
- service/src/main/java/bio/terra/workspace/service/resource/referenced/cloud/gcp/gcsobject/ReferencedGcsObjectResource.java
- service/src/test/java/bio/terra/workspace/service/resource/ResourceValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferenceValidationUtilsTest.java
Move Cloud specific functions to separate file ResourceValidationUtils
New files created - AzureResourceValidationUtils & GcpResourceValidationUtils
Add new validation util function - checkStringNonEmpty and use it where appropriate
Remove wrapper function checkFieldNonNull to add more meaningful error message
No other functional changes
> [BENCH-114] Move Cloud specific functions to separate file ResourceValidationUtils

- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/DeleteCloudContextStartStep.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextUnitTest.java
This is a similar error to https://github.com/DataBiosphere/terra-workspace-manager/pull/1290 but for cloud contexts instead of workspaces. Errors cannot be deserialized directly to `ErrorReportException` so this uses a utility instead.
Like #1290 this also removes storing errors on cloud context deletion failure, as my understanding is that's only for the `BROKEN` state.
> [BENCH-703] Fix cloud context error deserialization

- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteMetadataStep.java
I missed the flightId check on the delete success case in resources. Noticed it when doing cloud context.
This is a small fix to properly check the flight id.
> [PF-2740] Ensure flight id check on delete success

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDefinitionStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/flexibleresource/CloneFlexibleResourceStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/AzureCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/CloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/GcpCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/DeleteResourcesStep.java
- service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceBqTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceBucketTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceNotebookTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/container/CopyAzureStorageContainerDefinitionStepTest.java
Current implementation - during AWS cloud context deletion, resources are not force deleted. The wrong overloaded function is being called. Hence Workspace deletion fails if the notebook is not stopped prior to delete attempt
Fix - 
- call the correct overloaded deletion job submit function which forces notebook stop prior to delete attempt.
- To avoid future such errors (wrong function being called), the overloaded function is removed
- Individual resources are forceDeleted when cloud context is being deleted (i.e. deletion triggered from top)
-  Individual resources are NOT forceDeleted during stand alone deletion
- rename function launchDeleteFlight to launchDeleteResourceFlight to reflect that resource is being deleted (not cloud context)
> [BENCH-712] Force delete AWS Notebooks - stop & delete

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
Git didn't notice the merge conflict between #1332 and #1325, and now main is broken
> [BENCH-712] Fix compile error

- service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/DeleteGcsBucketStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/AwaitCreateCloudContextFlightStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/GcpCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/cloud/gcp/DeleteCloudContextResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/DeleteResourcesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/workspace/RunDeleteCloudContextFlightStep.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceStateUnitTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceUnitTest.java
I missed a step in the new workspace/cloud-context delete and it was deleting the GCP resources.
I had written the flight, but didn't use it...
Anyway, there a few independent changes here:
1. Use the DeleteCloudContextResourceFlight for the GCP cloud context delete.
2. Centralize and share code for waiting for flights and put it in FlightUtils
3. Small code cleanup in DeleteGcsBucketStep
> [PF-2843] Stop deleting GCP resources as part of cloud context delete

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/BuildAndValidateResourceListStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/DeleteResourcesStep.java
A quick follow-on to PF-2843. The new delete flight had a flake. I cannot reproduce it.
This code adds some logging and dumps Sam children if it seems the "children" error on workspace delete.
> [PF-2843] Add diagnostics to catch a flaky test

- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/app/controller/shared/WorkspaceApiUtils.java
- service/src/main/java/bio/terra/workspace/common/logging/model/ActivityLogChangeDetails.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/db/model/DbWorkspaceContextPair.java
- service/src/main/java/bio/terra/workspace/db/model/DbWorkspaceDescription.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/AccessibleWorkspace.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/MergePolicyAttributesDryRunStep.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/MergePolicyAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/model/WorkspaceDescription.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHookTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
This PR should improve workspace performance. At a high level, there are two changes:
1. Change the TPS method for creating a PAO if it doesn't exist. This reduces the calls to TPS by half.
2. Move all of the code to gather workspace, cloud context, and activity log information into the WorkspaceDao. This reduces the number of Postgres transactions to 1 from (5 * N) + 1 transactions, where N is the number of workspaces.
In order to put the work into the DAO, I added DbWorkspaceContextPair as an intermediate structure to hold the result of an outer join of workspace and cloud_context tables. I added DbWorkspaceDescription to hold the combined data from workspace, cloud_context, and workspace_activity_log (last update by and last update date).
I added a batch retrieval to the activity log …
> [PF-2710] list workspace performance

- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureVmTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerBatchPoolTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAzureResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledGcpResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ReferenceResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
- service/src/test/java/bio/terra/workspace/common/logging/WorkspaceActivityLogHookTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/db/FolderDaoTest.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/folder/FolderServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/ResourceLineageUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java
Move workspaceId, userEmail, user subjectId to workspaceFixtures so that they can be used in other tests
Remove duplicate declaration of referenceResourceFixtures.default_Resource_Properties
> [BENCH-471] Move test values to appropriate fixtures classes

- service/src/main/resources/application.yml
This moves WSM's connected and local integration tests to use the newest RBS pool without the deprecated genomics API enabled. Live deployments are handled separately in https://github.com/broadinstitute/terra-helmfile/pull/4317
> [PF-2782] Use new RBS pool for testing and local deployment

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStep.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledGcpResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStepTest.java
The machine type requires a zone, but the final zone is not computed until during the create flight, so we should build it there. It also makes it more consistent with the ai notebooks api. This is technically a breaking api change but nobody is using this yet.
> [PF-2876] Build GCE machineType string in flight

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteSamResourceStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
In the `ReferencedGcpResourceController*` tests, variables like resource name had been made class-final. That immediately hit duplicate resource name errors. I moved the dynamic strings back to the `@BeforeEach` per-test method.
The re-arranged delete workspace code needed one more SamService mock in a WorkspaceServiceTest.
I saw a weird case where it looked like we ran a step, but it didn't do what it was supposed to. Then we got a Sam error for "workspace still has children". I fixed the diagnostic I had added (that didn't work), and added a little more logging. Very puzzling.
> [PF-2875] Fixes for connectedPlus test

- service/src/main/java/bio/terra/workspace/service/grant/flight/RevokeStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneAllResourcesFlight.java
A handful of grant revoke flights are failing in devel as WSM was missing the logic for cleaning up GCE instance temporary grants. These are the only two places I found that switch on `WsmResourceType`, so hopefully we won't hit other cases like this.
> [PF-2833] Support revoking temporary grants for GCE instances

- service/src/main/java/bio/terra/workspace/common/utils/GcpUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStepTest.java
Similar to machine types, guest accelerators (gpus) take a url which we should build ourselves. Also, instances with a GPU attached need their maintenance behavior set to TERMINATE
> [PF-2882] Fixes to instance GPU configs

- service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/AwsUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateDeleteAwsSageMakerNotebookStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStepTest.java
- Delete flight and steps are already idempotent
- Adding option in the implementation function to not error out with NotFound during delete
- Refactored AWS notebook UT class to a abstract base class + 2 concrete test classes. This prevents base class tests from executing twice
> [BENCH-727] Ignore NotFound error in Delete functions

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteSamResourceStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerAiNotebookConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/TempGrantConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
New delete code is taking long enough in some cases that the synchronous delete request times out. Converting to the new async delete workspace call fixes the problem.
I have been unable to locally reproduce, debug, or analyze my way to a fix for the flake in RemoveUserFromWorkspaceFlightTest. This PR adds ridiculous logging to the code path in the hopes of catching the point of failure.
> [PF-2884] Deflake tests

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDifferentRegionStep.java
The `ControlledResourceKeys.DESTINATION_DATASET_NAME` key is placed in the working map in a previous step, where the value gets pulled from the source resource if it isn't explicitly provided. As-is, cross-region COPY_RESOURCE clones will fail with a 500 error if this isn't explicitly set.
> [PF-2902] Fix BigQuery cross-region COPY_RESOURCE clone

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/DeleteAzureDiskStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/DeleteAzureDiskStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1093. 
Main issue with this is that corresponding WSM resource stays in "DELETING" state and requires manual intervention since disk isn't deleted and still exists.
This PR improves resilience of disk deletion operation:
-returns fatal error instead of retrying in case disk is still attached to a virtual machine
-when undo step identify that do operation failed with "OperationNotAllowed" error (disk is attached to VM) it returns Success (disk is still working). Returning Success allows "DeleteMetadataStartStep" to successfully finish undo operation and move corresponding WSM resource into Ready state. 
The flight still completes with dismal failure. Dismal failure usually happens when undo operation failed. In the context of disk deletion …
> WOR-1093 Azure disk step should be resilient to OperationNotAllowed exceptions

- openapi/src/parts/controlled_azure_database.yaml
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/AzureManagedIdentityGuardStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/ControlledAzureManagedIdentityResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateAzureManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetFederatedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetPetManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/ManagedIdentityStep.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAzureResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDatabaseConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResourceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/AzureManagedIdentityGuardStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetPetManagedIdentityStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1108
The gist of the change is that the lookup of the managed identity was removed from within the created federated identity and database steps and performed in its own step ahead of time. There are now 2 different ways to lookup the managed identity which is reflected by 2 different step implementations. For shared databases, a step is used that looks up a workspace managed identity. For private databases, a step is used that looks up the assigned user's pet managed identity.
> WOR-1108 private azure db

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/CreateDataprocClusterStep.java
Made a last minute change in the dataproc cluster PR that causes cluster creation to fail. The presubmit checks did not catch it since they only run in nightlies. This change removes duplicate code that tries to set the user provided initialization script that is already being done safely below in L227.
> Remove bad initialization script config in cluster creation

- service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManagerTest.java
Fixes bug https://broadworkbench.atlassian.net/browse/WOR-1102, following Dan's [recommendation](https://broadinstitute.slack.com/archives/C01JVP0MLLX/p1688655016319019):
"That is a bug. The philosophy we are trying to implement is that everyone who is a reader (or above) on the workspace can see all of the resources in a workspace. Since enumeration shows the complete resource details there is no use "hiding" requests for specific resources.
I think we need to change the permission check on the get resource to check the workspace permission and not the resource permission."
I tested that this fixes the bug by:
1. Deploying this branch to a bee
2. Creating an Azure workspace on the bee
3. Sharing the workspace with a second user
4. Creating a Jupyter instance as the second user
5. And …
> [WOR-1102] Anyone with read access to a workspace should be able to read all resources in the workspace.

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
The Azure database creation step is failing due to an underscore present in the pod name, which violates their naming convention.
> [WOR-1134] Fix pod name when creating DB

- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureVmTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerBatchPoolTest.java
- service/src/test/java/bio/terra/workspace/app/controller/CreateAzureStorageContainerSasTokenTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockAwsApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockAzureApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/WorkspaceUnitTestUtils.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/AwsResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/AzureResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AwsWorkspaceV2ConnectedTest.java
- Part 1 of: Split MockMvcUtils to platform based components -> MockAzureApi (new) with Azure path formats
- Rename Path formats in MockAzureApi to keep them consistent.
- Renamed MvcAwsApi to MockAwsApi
- Add cloudPlatform param to deleteGcpCloudContextInDatabase (renamed to deleteCloudContextInDatabase)
Part 2 will contain GCP changes (MockGcpApi) in next PR
> [BENCH-826] Split Azure path formats from MockMvcUtils

- service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
- service/src/main/resources/application.yml
https://broadworkbench.atlassian.net/browse/WOR-1148
Example logs from a successful test run
```
2023-07-21 10:27:00.763   INFO 38214 --- [pool-8-thread-4] .t.w.s.r.c.c.a.d.CreateAzureDatabaseStep : Pod ecb5155d-e8ca-4390-9de4-b72f363583a8azdb534ec42a224f485e9feb482597e61cc0azuami8e63fe66b50d40ee8fee1621db25d17b final status: class V1PodStatus {
conditions: [class V1PodCondition {
lastProbeTime: null
lastTransitionTime: 2023-07-21T14:26:30Z
message: null
reason: PodCompleted
status: True
type: Initialized
}, class V1PodCondition {
lastProbeTime: null
lastTransitionTime: 2023-07-21T14:26:49Z
message: null
reason: PodCompleted
status: False
type: Ready
}, class V1PodCondition {
lastProbeTime: null
lastTransitionTime: 2023-07-21T14:26:49Z
message: null
reason: PodCompleted
status: False …
```
> WOR-1148 capture pod logs

- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerAiNotebookConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerDataprocClusterConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDataTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/TempGrantConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockGcpApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/AnyResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/GcpResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextConnectedTest.java
- Part 2 of: Split MockMvcUtils to platform based components -> MockGcpApi (new) with Gcp path formats 
- moves functions of AiNotebooks, GCE Instance, DataProc cluster, BQ tables and BQ datasets
- Rename Path formats in MockGcpApi to keep them consistent
- Move few util functions to specific test files
Part 3 will move functions of objects and buckets in next PR
> [BENCH-826] Split GCP path formats / functions from MockMvcUtils (pr 1)

- service/src/main/java/bio/terra/workspace/service/crl/CrlService.java
- service/src/test/java/bio/terra/workspace/service/danglingresource/DanglingResourceCleanupServiceTest.java
Currently, if the `azure.customer.usage-attribute` config value is not defined, Spring will fail to construct the CrlService component, which will crash WSM. This change will default it to an empty String instead, which seems like the right value per earlier comments: https://github.com/DataBiosphere/terra-workspace-manager/pull/1384#discussion_r1265939340
This also fixes a `mockMvcUtils` merge conflict between https://github.com/DataBiosphere/terra-workspace-manager/pull/1394 and https://github.com/DataBiosphere/terra-workspace-manager/pull/1387 that git didn't notice
> [PF-2925] Default to empty string when azure.customer.usage-attribute is not defined

- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerDataprocClusterConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/TempGrantConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/utils/MockGcpApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/danglingresource/DanglingResourceCleanupServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/GcpResourceStateFailureTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/GcpCloudContextConnectedTest.java
Rebase and merge after - https://github.com/DataBiosphere/terra-workspace-manager/pull/1394
- Part 3 of: Split MockMvcUtils to platform based components -> MockGcpApi (updated)
- moves functions of GCS Objects and GCS Buckets to MockGcpApi from MockMvcUtils
- Move few util functions to specific test files
Part 4 will move functions of DataRepo , Folder etc in next PR
> [BENCH-826] Split GCP path formats / functions from MockMvcUtils (pr 2)

- service/src/test/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/FolderApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDataTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockDataRepoApi.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockFlexibleResourceApi.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockFolderApi.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockGitRepoApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockGcpApi.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/iam/SamServiceTest.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/AnyResourceStateFailureTest.java
Followup on https://github.com/DataBiosphere/terra-workspace-manager/pull/1397
- Part 4 of: Split MockMvcUtils to platform based components -> GitRepo, DatRepo, Folder, FlexibleResource
Part 5 will update mocks package
Part 6 will cleanup the remaining functions in MockMvcUtils
> [BENCH-826] Split GitRepo, DataRepo, Folder, FlexibleResource APIs from MockMvcUtils

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
As reported in [PF-2918](https://broadworkbench.atlassian.net/browse/PF-2918), bucket mounting in workspaces with referenced resources that the mounting user does not have access to causes the `terra-instance-boot.service` to fail. This results the gcsfuse mount points for already mounted resources to die and result in `Transport endpoint is not connected` errors.
The startup script internal runs `terra resource mount`, which returns an exit code of 1 even if any of the resources do not mount due to permissions errors or 404 bucket errrors. This behavior is intentional and useful when the command is used in scripting. ~Instead of modifying the behavior of the CLI, we address the issue by adding a `-` to the terra startup service systemd unit, which tells systemd to ignore nonzero return …
> [PF-2918] - Ignore boot service child command exit codes and log its stdout, stderr

- service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiControllerTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerAiNotebookConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerDataprocClusterConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/PolicyApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDataTableConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/TempGrantConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockWorkspaceV2Api.java
- service/src/test/java/bio/terra/workspace/common/utils/AwsConnectedTestUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/GcpTestUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderFlightTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AwsWorkspaceV2ConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceV2ApiTest.java
- Ongoing cleanup of MockMvcUtils
- Move Workspace V2 apis to mocks package
- Remove duplicate definitions of V2 workspace APIs in MockMvcUtils
- Use AddAuth util function in LandingZoneApiControllerTest
- Move gcp test utils to GcpTestUtils
> [BENCH-826] Move Workspace V2 apis to mocks package

- openapi/src/parts/controlled_azure_database.yaml
- openapi/src/parts/controlled_azure_disk.yaml
- openapi/src/parts/controlled_azure_managed_identity.yaml
- openapi/src/parts/controlled_azure_vm.yaml
golang's oapi-codegen was failing to parse the malformed URIs.
> [PF-2930] Fix component URIs in Azure spec

- service/src/main/java/bio/terra/workspace/db/ResourceDao.java
- service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/SetCreateResponseStep.java
- service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
- service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceBqTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceBucketTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceGceInstanceConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceNotebookTest.java
Previously, workspace/cloud context/resource creation flights would always delete DB records on undo with the `DELETE_ON_FAILURE` rule, even if the flight was not the one which created those objects originally. 
This change adds a state transition to validate that the object was created by the calling flight. The method does not throw an error if this validation fails (as I believe we just want to return the 400 response from the `do` step), but no longer deletes the DB row.
Several controlled resource tests inadvertently depended on this behavior and had to be modified. Additionally, I changed the createControlledResource flight to throw a dismal failure if the flight fails between releasing the resource state lock (the last step) and flight completion to keep resource state in line with …
> Stop deleting workspace records on duplicate create request

- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/BuildAndValidateResourceListStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/DeleteResourcesStep.java
error: cloud context delete fails
root cause: previous delete is still running and conflicts with cloud context delete
fix: don't create duplicate delete resource flights
sample flow:
- User calls resource delete, which times out but is still running on server
- User now calls Workspace delete (internally calls cloud context delete)
- Cloud context delete created a new delete flight for the resource (since the previous delete is running)
- Flight flight completes and resource entries are deleted in DB
- Second flight attempts to update DB entry for resource (to start delete) and fails with 'resource not found'
with above fix:
- Cloud context delete will create a new resource delete flight only if there is no existing delete flight for that resource
- If there exists a flight, add it to …
> [BENCH-859] Handle duplicate delete requests from applications

- service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java
Handle "does not exist" exception message from aws
Sample message - 
software.amazon.awssdk.services.sagemaker.model.SageMakerException: Notebook Instance <arn> does not exist (Service: SageMaker, Status Code: 400, Request ID: <id)
> [BENCH-875] Handle "does not exist" exception message from aws

- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockFlexibleResourceApi.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockGcpApi.java
- service/src/test/java/bio/terra/workspace/service/resource/statetests/GcpResourceStateFailureTest.java
fixed connected plus tests -
> Task :service:connectedPlusTest
ControlledFlexibleResourceApiControllerConnectedTest > clone_copyResource_undo() STARTED
ControlledFlexibleResourceApiControllerConnectedTest > clone_copyResource_undo() PASSED
> [BENCH-888] fix gcp connected plus test errors

- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/policy/PolicyValidator.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsUtilities.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/ValidateGroupPolicyAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/service/policy/TpsUtilitiesTest.java
We have an endpoint for updating policies on workspaces, but it didn't appropriately handle adding groups. This update will let that endpoint also call Sam if the group policies on the workspace change.
> BENCH-892: Patch workspace policies should allow updating groups

- openapi/src/parts/controlled_gcp_dataproc_cluster.yaml
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/CreateDataprocClusterStep.java
Dataproc clusters support passing in a list of startup scripts. The wsm api should also support it to allow users to provide their own custom startup scripts to install any software they need.
> Support multiple dataproc initialization scripts

- service/build.gradle
- service/src/test/java/bio/terra/workspace/pact/TpsApiTest.java
[WOR-1157](https://broadworkbench.atlassian.net/browse/WOR-1157)
Adds consumer-side contract tests from WSM to TPS.
The changes in this PR don't include changes to publish all pacts to pact broker, yet. 
[WOR-1157]: https://broadworkbench.atlassian.net/browse/WOR-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WOR-1157 Add consumer pact for TPS

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/SetNoOpDatasetCloneResponseStep.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledFlexibleResourceApiControllerConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockGcpApi.java
- service/src/test/java/bio/terra/workspace/service/admin/AdminServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/CreateGcpContextFlightTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/RemoveUserFromWorkspaceFlightTest.java
WSM's nightly connectedPlus tests have been failing for a few weeks, there were a few independent fixes required:
- `WorkspaceServiceTest` was a connected test which injected a mock SamService using `@MockBean`, which replaces the bean in the Spring context with the mock. However, it seems like the context wasn't restarted after this injection, so other connectedPlus tests which expected a real SamService were actually calling this mock. This would only appear if the test was run in the same context as `WorkspaceServiceTest`, which made it hard to reproduce.
- Given that `WorkspaceServiceTest` used a mock Sam and never called GCP, I've moved it to a unit test instead.
- I've also re-enabled `RemoveUserFromWorkspaceFlightTest` now that the SamService issue is resolved.
- The  MockGcpApi …
> [PF-2884] Fix broken connectedPlus tests

- integration/src/main/resources/testusers/README.md
- scripts/write-config.sh
- service/src/main/java/bio/terra/workspace/service/workspace/flight/delete/cloudcontext/BuildAndValidateResourceListStep.java
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-978)
[Related one-pager](https://docs.google.com/document/d/1uLT4VcIdqjo_RPZzAP0D6FsGzUbviUbnW1OtZ_k0iPc/edit)
Application controlled resources may be orphaned by their stewarding application prior to workspace deletion. When this happens, the workspace becomes undelete-able due to the Sam checks against the application controlled resources. 
* Removes the checks in the `BuildAndValidateResourceListStep` class that is run at the start of cloud context deletion. The premise is that the principal running the deletion flight has DELETE on the workspace, and all resources should be deleted regardless of their stewardship. 
* I had originally planned on making modifications to the `SamService` to delete the related resource Sam entries …
> [WOR-978] Remove check for DELETE on workspace resources during cloud context deletion

- openapi/src/parts/controlled_gcp_dataproc_cluster.yaml
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/CreateDataprocClusterStep.java
With this change, the cli/ui can specify the set of installed software versions for (spark/hadoop/etc). The default debian image that's used has older versions incompatible with the latest version of [hail](https://hail.is/).
> Allow configuring dataproc image version

- integration/src/main/java/scripts/utils/DataprocUtils.java
- openapi/src/parts/controlled_gcp_dataproc_cluster.yaml
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/CreateDataprocClusterStep.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledGcpResourceFixtures.java
Single node clusters require passing null for primary and secondary worker configs to the dataproc api. This is not possible with the current wsm create api. This change changes primary worker config to an optional property. Also removes the logic of setting secondary worker config be the same as primary worker config, the UI/CLI is already doing this.
> Do not require primary worker config in dataproc cluster creation

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/RetrieveDataprocClusterResourceAttributesStep.java
Dataproc cluster get api doesn't return any worker configuration value like machine-type or machine uri if its node count has been created or updated to 0... Unclear why they chose this behavior but it's causing an error when updating a cluster worker count size from 0 to any value.
> Add null checks to cluster metadata check

- service/src/main/resources/application.yml
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1194)
Large access tokens exceed the default configured spring boot header size limit of 8k. I have verified this behavior with a token borrowed from a dev who was encountering this issue. A similar [fix](https://github.com/DataBiosphere/terra-billing-profile-manager/pulls?q=is%3Apr+is%3Aclosed) in BPM mitigated the issue, this ports it to WSM where we are also seeing errors.
> [WOR-1194] Set max header size to 32KB

- service/src/test/java/bio/terra/workspace/common/GcsBucketUtils.java
The bucket test `clone_copyDefinition` has been flaky on and off. I think I figured out that it is a permission setting delay:
- WSM sets permissions on the bucket resource from Sam sync'd groups
- (My hypothesis is there is a propagation delay of some sort here)
- Test calls GCP immediately to check for files. Sometimes we see 403.
I added a retry on the file check. If things are actually broken, it will slow the test down by 5 minutes. But for the normal case, it will allow us to wait for propagation, the check will pass, and the test won't flake out.
> [PF-2951] Add retry on assertBucketHasNoFiles to handle permission propagation

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
Currently, the dataproc startup script is set by providing the cluster with the gce instance metadata `startup-script-url`. This script is executed by the `google-startup-script` systemd service. But because the default dataproc startup script that installs software components including the jupyter component is further down in the systemd startup dependency chain, the call to restart jupyter service fails due to missing packages.
This change removes the call to restart `jupyer.service` so that the startup script completes successfully and `jupyter.service` is started by dataproc's jupyter component with the desired terra env vars exported from this script.
This change needed is to unblock UI work on displaying the startup script completion status.
> Do not restart jupyter service

- openapi/src/parts/azure_landing_zone.yaml
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java
- service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatchTest.java
When listing the resources inside a landing zone, return the tags for those resources.
This will help with inspecting the landing zone to understand its configuration. The current use case is preparing to enable PgBouncer for the LZ Postgres server - we can set a tag on the Postgres resource if PgBouncer is enabled, and then Leo can read the tag (via WSM) and tell WDS and CBAS to connect to PgBouncer on port 6432 instead of Postgres on port 5432.
I am aware this will cause some duplication between tag values and elsewhere in the response, such as the WLZ-PURPOSE and WLZ-ID.
Slack discussion: https://broadinstitute.slack.com/archives/C02LMB1PQ6R/p1692376111128999
This is an additive change to an existing API. Will this cause any problems for services that use the WSM client? Are additive …
> AJ-1270: return tags from LZ resource listing

- integration/src/main/java/scripts/testscripts/PrivateControlledDataprocClusterLifeCycle.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/RetrieveDataprocClusterResourceAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/UpdateDataprocClusterStep.java
This change includes the following fixes:
- Fix a bad property set on cluster secondary workers.
- Add a check to to skip the update call if there are no parameters to update. This caused a dismal failure in the update undo step when there were no previous parameters to update to, resulting in an empty update call error.
- Add a null check on `idleDeleteTtl`, though it should never be null if its parent `lifecycleConfig` exists.
Note: I intentional rely on the gcp api to handle validation errors. There are a few parameters that cannot be fully validated locally:
- num secondary workers have dynamic constraints depending on the autoscaling policy attached to the cluster
- the autoscaling policy provided may or may not exist in the project.
Ideally these validation errors cause the flight …
> Dataproc Update Fixes

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
This changes adds a hail install script to the dataproc startup script. Since this startup script executes before dataproc installs its optional components onto the cluster, the hail scripts breaks the dataproc install scripts causing the cluster to fail to launch jupyter correctly and report an error status. Therefore we poll for the dataproc component gateway service to become active before executing the hail install script.
Notes:
- I've tried creating a separate hail systemd service that is configured to run after the component gateway service, but I don't think its possible to create a systemd unit during startup trigger it to execute at the correct time without doing a reboot.
> [PF-2776] - Add hail install script to cluster startup script

- openapi/src/parts/controlled_aws_sagemaker_notebook.yaml
This is recommended by AWS support to improve notebook startup times
ml.t3.medium is of newer generation, comparison for reference - https://www.cloudzero.com/advisor/t2-vs-t3
the cost difference is 1/3 of one cent per hour ($0.0036).
note: VWB ui already using this in UI / integration tests. This may be the reason we have mostly seen the delay in WSM tests
> [BENCH-822] Switch default notebook instance type to ml.t3.medium

- service/src/main/java/bio/terra/workspace/service/resource/GcpFlightExceptionUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/CreateAiNotebookInstanceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/CreateDataprocClusterStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/UpdateDataprocClusterStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStep.java
Fix the create compute resource flights to throw `BadRequestException` instead of a 500 `InternalServerException` if there are issues with parameters in the flight's gcp request.
`GoogleJsonResponseException` returns 400 if a parameter was incorrectly formatted and 404 if a parameter value was not found, such as a gce machine type or cluster autoscaling policy uri. For both, surface the gcp error message and return a 400.
This also fixes a case where creating vertex ai notebooks with a bad machine type or vm image family will hang for all 10 flight retries before finally failing due to the 404 being retried.
Before:
```
{
"jobReport": {
"id": "e73805d7-a09f-47de-a27b-450d97a71857",
"description": "Create controlled resource CONTROLLED_GCP_AI_NOTEBOOK_INSTANCE; id …
```
> PF-1040: Surface google json exception errors

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/AwsResourceConstants.java
This helps us better monitor recent changes to the instance type
> [BENCH-999] Change notebook waiter timeout to 30 min

- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/shared/ControllerUtils.java
- service/src/main/java/bio/terra/workspace/app/controller/shared/WorkspaceApiUtils.java
- service/src/main/java/bio/terra/workspace/service/workspace/model/CloudContextCommonFields.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceV2ApiTest.java
The operation state was populated in the internal workspace structure, but not in the API return.
> [BENCH-1016] Populate operation state on workspace description

- service/src/main/java/bio/terra/workspace/app/controller/shared/JobApiUtils.java
A small piece of code that mapped Stairway flight status to async job state had a bug. It was categorizing 
QUEUED, WAITING, READY, and READY_TO_RESTART as FAILED states. Those are actually RUNNING states - the flight is not complete so wouldn't have a complete time.
In this particular case, the flight enters the QUEUED state. In this case, I think the QUEUED state happened because the Stairway thread pool had too many pending flights in its queue. At that point, Stairway pushes flights to its pubsub queue for other pods to deal with. Even though we don't have that properly configured, the state changes still happen.
> [BENCH-992] Incorrect categorization of flight states

- service/src/test/java/bio/terra/workspace/common/GcsBucketUtils.java
This test utility method makes a call directly to GCS, which sometimes fails due to permissions propagation issues or files not being loaded into the bucket. We should retry this call briefly.
This is currently causing the `loadSignedUrlList_succeedsAndFileLoadedIntoBucket` to flake intermittently, as there can be a very short delay between the job loading files into the bucket and GCS acknowledging those files exist.
> [PF-2967] Add retries for assertBucketFiles cloud call

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
This change contains fixes for the following dataproc cluster issues:
- Enable sudo with no password prompt - https://verily.atlassian.net/browse/BENCH-1048
- Startup script not setting env vars such as `OWNER_EMAIL`, `PET_SA_EMAIL`, etc.
- Sets jupyter notebook file tree root to `/home/dataproc` (aligned with vertex ai notebooks, also users can access their staging bucket via `/workspace/staging-bucket-name/notebooks/jupyter/`
- "Read only-dir.." error when creating a new notebook in root dir. (no longer the case since we changed root dir)
- ggplot hail notebooks figures are not correctly rendered in cell output ( plot.ly figures being read from invalid dir path)
> Add various fixes for dataproc cluster startup

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateNamespaceRoleStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteNamespaceRoleStep.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAzureResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateNamespaceRoleStepTest.java
I was using more human readable values for pod names that execute db commands but those are too long. This switches to just use the resource id.
https://broadworkbench.atlassian.net/browse/WOR-1242
> WOR-1242 fix too long pod names

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
Change the dataproc startup script to wait for the start of `jupyter.service` instead of `google-dataproc-component-gateway.service`. As is, there seems to be a race condition where dataproc scripts are still executing set up scripts, including jupyter, causing the startup script's call to restart `jupyer.service` to fail. This failure didn't occur for hail clusters, likely due to the additional time needed in the startup script to install hail before restarting jupyter.
This change ensures that we wait until the jupyter service itself has started before modifying it's configuration and restarting it.
Fixes: https://verily.atlassian.net/browse/BENCH-1080
> BENCH-1080: Fix non hail startup script

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
Due to package version incompatibilities with jupyter, [hail's spark monitor](https://github.com/hail-is/sparkmonitor) doesn't work out of the box. This change remove the default hail installation script installs the `sparkmonitor` nbextension.  For now, we expect users rely on the inline text based spark job output logs rendered in cell output. Users can further monitor larger jobs in cloud console.
Removing spark monitor fixes also fixes the spark monitor initialization error with `hl.init()` when using the hail kernel.
> BENCH-1063: Remove spark monitor

- service/gradle/testing.gradle
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
- service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/CreateAwsS3StorageFolderStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/DeleteAwsS3StorageFolderStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ValidateAwsS3StorageFolderCreateStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateAwsSageMakerNotebookStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/DeleteAwsSageMakerNotebookStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ValidateAwsSageMakerNotebookDeleteStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/cloud/aws/MakeAwsCloudContextStep.java
- service/src/test/java/bio/terra/workspace/common/BaseAwsConnectedTest.java
- service/src/test/java/bio/terra/workspace/common/BaseAwsUnitTest.java
- service/src/test/java/bio/terra/workspace/common/utils/AwsTestUtils.java
- service/src/test/java/bio/terra/workspace/common/utils/AwsUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderFlightTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookFlightTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateDeleteAwsSageMakerNotebookStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStepTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AwsCloudContextConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AwsCloudContextUnitTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/AwsWorkspaceV2UnitTest.java
discoverEnvironment performs a AWS_ENBALED check, which requires userEmail
1. Pass user email to awsCloudContextService.discoverEnvironment. 
2. Aws resource steps: add samService as a parameter to the step. this is used to fetch the user email
3. Rename flightBeanbag variable from appContext to flightBeanbag to avoid confusion
4. Add new test to check aws feature enabled / disabled for a user
5. Test updates 
AWS connected (failure in first image fixed, see second image)
manual run of connected test successful https://github.com/verily-src/terra-service-ws-manager/actions/runs/6155267643
--
Pending / in progress: manual testing in autopush
> [BENCH-970] Pass user email to awsCloudContextService.discoverEnvironment

- openapi/src/parts/controlled_azure_database.yaml
- openapi/src/parts/controlled_azure_kubernetes_namespace.yaml
- openapi/src/resources/azure_database.yaml
- openapi/src/resources/azure_kubernetesNamespace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java
- service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAzureResourceFixtures.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResourceTest.java
this is prep for https://broadworkbench.atlassian.net/browse/WOR-1250 so that we can roll out a new client lib that does not actually change anything but is forward compatible with the real change
> update client lib to allow non-uuids in prep for allowing names

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/StorageAccountCoordinates.java
We're bumping into Azure throttling under load to the getSasToken endpoint. This is because we are making a live call to Azure to get storage account information for workspaces, from which we mint a sas token locally. 
This PR introduces a basic cache keyed on workspaceId and storageContainerUuid.
> Cache storage data per workspace and container

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
Previously, this wasn't set up correctly.
> BENCH-1223: Only run startup script on first boot

- openapi/tools/requirements.txt
Fixes OpenAPI Python `venv` configuration, which is currently failing for fresh checkouts due to https://github.com/yaml/pyyaml/issues/736.
> PF-2973: Get fixed PyYAML when setting up OpenAPI code gen venv.

- integration/src/main/java/scripts/testscripts/CloneWorkspace.java
- integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
- integration/src/main/java/scripts/testscripts/EnablePet.java
- integration/src/main/java/scripts/testscripts/EnumerateResources.java
- integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstancePostStartup.java
- integration/src/main/java/scripts/testscripts/PrivateControlledDataprocClusterLifeCycle.java
- integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
- integration/src/main/java/scripts/testscripts/ReferencedTerraWorkspaceLifecycle.java
- integration/src/main/java/scripts/testscripts/RemoveUser.java
- integration/src/main/java/scripts/utils/BqDatasetUtils.java
- integration/src/main/java/scripts/utils/ClientTestUtils.java
- integration/src/main/java/scripts/utils/GcsBucketAccessTester.java
- integration/src/main/java/scripts/utils/GcsBucketObjectUtils.java
- integration/src/main/java/scripts/utils/GcsBucketUtils.java
- integration/src/main/java/scripts/utils/GitRepoUtils.java
- integration/src/main/java/scripts/utils/RetryUtils.java
This change:
- Add a check that the dataproc resource user has access to the created cluster before directly querying it. This catches the occaisonal `Not authorized for requested resource` permission flake.
- Wraps `userHasProxyAccess()` with retry to address the integration test sometimes failing at that step.
- Adds logic to properly test stop / start.
- Move `getWithRetryOnException` from `ClientTestUtils` to `RetryUtils`.
Note: The dataproc integration test suite not enabled in the broad environment (this repo's test config). This only applies to the downstream verily integration test suite.
> Fix dataproc integration test flake

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
Read the `terra-server` metadata and install the CLI from the appropriate broad/verily distribution url. For verily, fetch the distribution path from afs, for broad, install from the open source repo.
> [BENCH-1202]  - Support installing CLI version based on environment

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh
Resolves error when running `post-startup.sh` on newly created environments in dev:
```
E: Repository 'http://packages.cloud.google.com/apt gcsfuse-buster InRelease' changed its 'Origin' value from 'gcsfuse-jessie' to 'namespaces/gcs-fuse-prod/repositories/gcsfuse-buster'
E: Repository 'http://packages.cloud.google.com/apt gcsfuse-buster InRelease' changed its 'Label' value from 'gcsfuse-jessie' to 'namespaces/gcs-fuse-prod/repositories/gcsfuse-buster'
```
> [BENCH-1270] - Added --allow-releaseinfo-change to apt-get update

- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java
TES expects the batch subnet as a full resource id.
Related PR: https://github.com/DataBiosphere/leonardo/pull/3432 is blocked until we can return the resource id. 
https://broadworkbench.atlassian.net/browse/TOAZ-335
> Return resource id for subnets

- .github/workflows/server-startup-test.yaml
- .github/workflows/workflow-tester.yml
- service/src/main/java/bio/terra/workspace/app/Main.java
- service/src/main/java/bio/terra/workspace/app/StartupInitializer.java
- service/src/main/java/bio/terra/workspace/app/configuration/external/StartupConfiguration.java
- service/src/main/resources/application.yml
When we start the WSM server for integration tests, it is done in a subprocess and the output is not available in the github log. If something goes wrong, it is hard to debug. Also, if something is slow, we cannot see where the delay is.
This PR includes two things:
1. StartupConfiguration that allows requesting immediate exit after the service is up and running
2. A manually dispatched github workflow that sets that config and simply starts the service.
I put the new workflow into workflow-tester so I could test ahead of commit. You can ignore that file.
> [BENCH-958] Service startup tester

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1282
There are a couple dozen k8s namespaces in production that have the managed identity resource id stored in the database instead of the resource name. This change allows us to tolerate that case.
> WOR-1282 Fix error deleting old namespaces

- openapi/src/common/parameters.yaml
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/SasPermissionsHelper.java
- service/src/test/java/bio/terra/workspace/app/controller/CreateAzureStorageContainerSasTokenTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
In this PR:
- Added the `t` (tag) permission to the API that generates SAS tokens.
- The `t` permission is allowed when the user has write access to the workspace.
> [WOR-1294] Add tag permissions to the get SAS token API

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/CustomGcpIamRoleMapping.java
addresses test failure
https://scans.gradle.com/s/34se3srg6swvu/tests/task/:service:connectedPlusTest/details/bio.terra.workspace.service.workspace.flight.gcp.CreateGcpContextFlightTest/successCreatesProjectAndContext()?expanded-stacktrace=WyIwIl0&top-execution=1 
Expected: iterable with items ["compute.instances.get", "compute.instances.list", "iap.tunnelInstances.accessViaIAP", "compute.instances.get", "compute.instances.list", "compute.projects.get", "compute.instances.setMetadata", "compute.projects.setCommonInstanceMetadata", "compute.globalOperations.get", "compute.instances.start", "compute.instances.stop", "compute.instances.use", "compute.instances.reset", "compute.instances.setMachineType"] in any order     but: no item matches: "compute.instances.get", "compute.instances.list" …
> [BENCH-1359] Remove duplicates from GCE_INSTANCE_WRITER_PERMISSIONS

- openapi/src/parts/controlled_gcp_dataproc_cluster.yaml
The UI and CLI are applying the metadata + properties to do what WSM initially intended to do with this param.
> Remove unused cluster create param

- openapi/src/parts/azure_landing_zone.yaml
- openapi/src/parts/controlled_azure_resource.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1296)
Users should be able to query resource quota for landing zone resources if they have permissions on the workspace.
* Introduces two new endpoints:
* ```/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone```
* ```/api/workspaces/v1/{workspaceId}/resources/controlled/azure/landingzone/quota```
* These endpoints will assert that user is a WRITER and proxy the call to the landing zone service as the WSM SA. 
* Deprecates the old LZ versions of these endpoints.
> [WOR-1296] Azure workspace quota endpoint

- .github/workflows/consumer_contract_tests.yml
- service/src/test/java/bio/terra/workspace/pact/ProfileApiTest.java
- service/src/test/java/bio/terra/workspace/pact/TpsApiTest.java
Rename the pacticipant names to the recommended convention.
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698068076950019) discussing the `-consumer` and `-provider` suffix anti-pattern.
* See [thread](https://broadinstitute.slack.com/archives/C043YJ40719/p1698241095600099) discussing the recommendation to use the helmchart name.
* This must be paired with corresponding changes in [BPM](https://github.com/DataBiosphere/terra-billing-profile-manager) maintain existing contract verification coverage.
* There are not currently any [TPS](https://github.com/DataBiosphere/terra-policy-service) contract verification tests, so no updates needed there.
This is prerequesite work for https://github.com/DataBiosphere/terra-workspace-manager/pull/1511, which introduces a new …
> AJ-1235: Use helmchart names for pact identifiers.

- foundation.yaml
This is a functional no-op PR that just adds a metadata file to the WSM repo that is used to ingest bpm into [DSP's backstage instance](https://backstage.dsp-devops.broadinstitute.org/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned). Backstage is an internal platform tool that can be used for a lot of SDLC processes and improving Dev experience. DevOps is just starting to experiment with this as a means to make getting a new service stood up in the terra environments and through the prod readiness checklist easier.
But we also want all our existing services to be in the system so they can get any benefits.
> DDO-3198 Add Metadata Yaml File to to ingest WSM into DSP backstage

- .github/workflows/verify_consumer_pacts.yaml
- README.md
- service/gradle/testing.gradle
- service/src/test/java/bio/terra/workspace/pact/WdsContractVerificationTest.java
- service/src/test/render-pact-configs.sh
- service/src/test/resources/application-pact-test.properties
- service/src/test/resources/application-test.yml
Ticket: [AJ-1451](https://broadworkbench.atlassian.net/browse/AJ-1451)
Inspired by https://github.com/DataBiosphere/jade-data-repo/pull/1528, this is intended to improve the documentation and first time experience for running pact tests locally in the wsm codebase.
[AJ-1451]: https://broadworkbench.atlassian.net/browse/AJ-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AJ-1451: Simplify and improve pact boilerplate.

- service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
- service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceUnitTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-1353)
We are not setting the auth domain on a workspace when a data repo snapshot is imported with a TPS group-constraint policy. This PR updates the linkPoilcies method to add the group from the constraint to the workspace's auth domain, similar to what we're doing on policy updates.
> [WOR-1353] Update the workspace's auth domain on PAO link

- service/src/main/java/bio/terra/workspace/service/policy/flight/LinkSpendProfilePolicyAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/policy/flight/MergeBillingProfilePolicyAttributesStep.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/create/workspace/CreateWorkspaceV2Flight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/create/workspace/WorkspaceCreateFlight.java
- service/src/test/java/bio/terra/workspace/service/policy/flight/LinkSpendProfilePolicyAttributesStepTest.java
Ticket: [WOR-1336](https://broadworkbench.atlassian.net/browse/WOR-1336)
* When a workspace is created, WSM will attempt to link its PAO to its spend profile's PAO. Non-BPM spend profiles are ignored.
[WOR-1336]: https://broadworkbench.atlassian.net/browse/WOR-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WOR-1336] Link workspace PAO to spend profile PAO 

- service/src/main/java/bio/terra/workspace/service/policy/TpsRetry.java
We are getting intermittent 403s from TPS, originating from the oidc-proxy. The cause is unclear, but we should retry in these instances.
> [WOR-1332] Retry on 403 from TPS

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/EnableVmLoggingStep.java
While trying to re-try creating the Azure Monitor Agent, the re-try fails because an extension with the same name exists.
This code attempts to delete the failed extension with the same name before retrying.
Tests are coming - 😅 
https://broadworkbench.atlassian.net/browse/IA-4718
> fix(IA-4718): delete vm extension before retrying to create it

- service/src/test/java/bio/terra/workspace/common/BaseAzureConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/azure/DeleteAzureContextFlightTest.java
The `DeleteAzureContextFlightTest` test has been failing consistently the past few days. I am able to reproduce the issue locally as well:
```
bio.terra.landingzone.db.exception.LandingZoneNotFoundException: Landing Zone with billing profile 4a5afeaa-b3b2-fa51-8e4e-9dbf294b7837 not found.	
at bio.terra.landingzone.db.LandingZoneDao.lambda$getLandingZoneByBillingProfileId$1(LandingZoneDao.java:181)	
at java.base/java.util.Optional.orElseThrow(Optional.java:403)	
at bio.terra.landingzone.db.LandingZoneDao.getLandingZoneByBillingProfileId(LandingZoneDao.java:178)
```
My hunch is that these tests were only passing previously because they were running after another connected test had setup the landing zone. I've adjusted the test to always create a landing zone instead. 
[Successful …
> [WOR-1396] Always create a landing zone during DeleteAzureCloudContextFlightTest

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ExtensionStatus.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/InstallCustomVmExtension.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/VmExtensionHelper.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/VmExtensionInstallInProgressException.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/InstallCustomVmExtensionTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/VmExtensionHelperTest.java
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1397)
VM provisioning occasionally fails due to script extension installation issues with the AzureMonitorLinuxAgent. The hypothesis is that installing the Terra custom script extension inline during VM provisioning is locking up the package manager unnecessarily, leading to downstream effects with the AzureMonitorLinuxAgent installation. 
Reproducing this issue is difficult so this is more of a speculative fix. Concurrent to this PR, I'm going through a series of tests against a BEE where I will spin up many VMs and observe the rate of success before and after this PR prior to merge.
* Extracts the custom script installation to a separate step during the provisioning flight and adds more thorough test coverage.
> [WOR-1397] Move custom script installation to a separate step

- .github/workflows/consumer_contract_tests.yml
- .github/workflows/tag-publish.yml
- .github/workflows/tag.yml
- .github/workflows/verify_consumer_pacts.yaml
No ticket needed because this does not impact any production code (github workflows only).
This is to fix the problem that dependabot PRs trigger a new version to be created.
> [NO TICKET] Fix bumper.

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/CloneControlledAzureDatabaseResourceFlight.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/DumpAzureDatabaseStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/DumpAzureDatabaseStepTest.java
fixes a bug in workflow cloning when trying to clone a workspace across MRGs
this has been tested in a BEE
> [WM-2420] use source workspace's cloud context in pgdump pod

- azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/database/DatabaseService.java
- azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/runners/PgRestoreDatabaseRunner.java
Makes sure the pgrestore command finishes before we try to update table ownership.
Otherwise in the worst case (for very small dumps being restored), we can end up running the table reassignment before the table creation command has run.
> WM-2418: Wait for database table to exist before reassigning

- azureDatabaseUtils/build.gradle
- azureDatabaseUtils/gradle/deploy.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- service/build.gradle
- service/gradle/deploy.gradle
Originally https://github.com/DataBiosphere/terra-workspace-manager/pull/1560.
> [WOR-1416] Update gradle, jib, and two other libraries required by JShell.

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/DeleteFederatedCredentialStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/ManagedIdentityHelper.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/MissingIdentityBehavior.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/ManagedIdentityHelperTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-1418)
Clients can delete the managed identity an Azure kubernetes namespace uses out of band. This causes the k8s namespace deletion flight to fail as it expects the managed identity resource to be present.
This is an attempt at making the namespace deletion flight resilient to these situations.
This PR:
* Modifies the logic in the GetWorkspaceManagedIdentityStep to allow the identity resource to be missing.
* Refactors the azure logic to a separate helper to ease testability.
> Do not fail out azure k8s namespace deletion when managed identity resource is not present

- .github/dependabot.yml
Let's try out the grouping feature. It seems like it will be particularly useful in this repo given that dependabot PRs currently require some hand-holding (as dependabot user doesn't have access to all the necessary secrets).
> [NO TICKET] Try grouping dependabot updates.

- .github/CODEOWNERS
https://broadworkbench.atlassian.net/browse/WOR-1444
This matches existing convention in BPM, LZS.  Previously, Verily's ownership of the service kept us from making this change.
We discussed in standup that we'd like to move forward with this change given a preference for consistency between services, but remain open to changing the review requirements in the future if this proves cumbersome for external contributions.  (Maybe do something similar to Terra UI, requiring one Workspaces review and one other review.)
Change flagged in Slack: https://broadinstitute.slack.com/archives/C01JVP0MLLX/p1705421646314409
> [WOR-1444] Add CODEOWNERS file

- .github/dependabot.yml
Follow-up to https://github.com/DataBiosphere/terra-workspace-manager/pull/1611 to exclude problematic upgrades (we have tickets for them), include the long-lived JIRA ticket on dependabot PRs, and make the total number of allowable PRs consistent with other repos.
> [NO TICKET] Add ticket number and prevent problematic updates (dependabot)

- .github/workflows/full-integration-tests.yml
- .github/workflows/full-service-tests.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr-integration.yml
- .github/workflows/release-promotion-tests.yml
- .github/workflows/test.yml
Move notifications from #terra-wsm-alerts to the Workspaces team channel. The older Slack channel will be archived.
> [NO TICKET] Route failures to Workspaces test alert channel.

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/DumpAzureDatabaseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/RestoreAzureDatabaseStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/DumpAzureDatabaseStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/azure/database/RestoreAzureDatabaseStepTest.java
Tested the changes in BEE by cloning a workspace
Before
The pod name would be (from logs)
```
INFO 2024-01-26T20:46:50.130Z Creating pod class V1Pod {.... name: dump-db-560241a2-81b4-414e-9a83-cf5765fa9050 namespace: null  …
INFO 2024-01-26T20:46:50.303Z Status = Optional[Pending] for azure database utils pod = dump-db-560241a2-81b4-414e-9a83-cf5765fa9050
INFO 2024-01-26T20:47:00.344Z Status = Optional[Succeeded] for azure database utils pod = dump-db-560241a2-81b4-414e-9a83-cf5765fa9050
```
After the changes
Pod name includes name of source database being cloned and the destination container resource ID (from logs)
```
INFO 2024-01-26T21:26:23.474Z Creating pod class V1Pod { ... name: dump-db-cbas-jkw18e-b4f91713-6f14-47f8-ad26-6a4b6633687a namespace: null …
INFO 2024-01-26T21:26:23.646Z …
```
> [WM-2459] DB dump & restore pod should be named based on destination resource during cloning

- .github/workflows/full-integration-tests.yml
- .github/workflows/full-service-tests.yml
The nightly full integration test run includes ITs that are not typically included in PR integration tests. One that is consistently failing requires TPS to be enabled. [WOR-1441](https://broadworkbench.atlassian.net/browse/WOR-1441) should mitigate that; until then I'm flipping the flag on by rendering a config file similar to what write-config.sh does ([here is a successful run](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/7699274333)).
The nightly full service test flow requires Azure credentials to be in place (here is a link to failing [run](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/7708081149/job/21006451627), note the failing Azure tests). This will require [WOR-1463](https://broadworkbench.atlassian.net/browse/WOR-1463) to …
> [WOR-1426] Fix full integration tests and service test workflows

- .github/workflows/tag-publish.yml
We need an azureDatabaseUtils image built for ITs to run successfully against a given SHA. This un-ignores changes to .github so changes to workflows in this repo always get the needed image built as we iterate on CI modifications.
> Do not ignore changes to .github when publishing

- service/src/main/java/bio/terra/workspace/common/utils/MdcHook.java
- service/src/test/java/bio/terra/workspace/common/utils/MdcHookTest.java
https://broadworkbench.atlassian.net/browse/WOR-1454
**Problem**
We've had a hard time debugging the dismal failures of our services' Stairway flights when [alerts](https://console.cloud.google.com/monitoring/alerting/incidents/0.n8b4q18pyjgu?channelType=slack&project=broad-dsde-staging) are emitted to #dsp-workspaces-alerts.  We'd resort to searching across fields for the flight ID, roughly around the time of the failure, which is a fuzzy process liable to miss relevant logs.
Previously, we tried to propagate the calling thread's MDC to each Stairway step.  At present, this only contains the `requestId` set via TCL's [RequestIdFilter](https://github.com/DataBiosphere/terra-common-lib/blob/develop/src/main/java/bio/terra/common/logging/RequestIdFilter.java).
But this left a few gaps in …
> [WOR-1454] Populate MDC for Stairway flight and its steps

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/AwaitCloneAllResourcesFlightStep.java
An Azure workspace clone can take > 6 minutes due to AKS pod creation and postgres dumps + restores. This PR is bumping the timeout by 2x to 12 minutes.
> [WOR-1499] Increase job polling timeout when awaiting a clone of all workspace resources

- .github/workflows/tag-publish.yml
- .github/workflows/test.yml
`version` is not a supported input to `google-github-actions/auth`:
https://github.com/google-github-actions/auth?tab=readme-ov-file#inputs
This shows up as a warning but seems to be otherwise ignored.  (I originally thought it might be causing failures in https://github.com/DataBiosphere/terra-workspace-manager/pull/1632 but that wasn't the case on further investigation).
Removed it anyways to clean up.
> [NO TICKET] google-github-actions/auth doesn't support version input

- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/AwaitCloneAllResourcesFlightStep.java
This [PR](https://github.com/DataBiosphere/terra-workspace-manager/commits/main/) transposed the cycles and seconds arguments, so it shifted the await to a minimum of 720 seconds. The [correct](https://github.com/DataBiosphere/stairway/blob/develop/stairway/src/main/java/bio/terra/stairway/Stairway.java#L201) order is # of seconds per cycle (1), # of cycles (720).
> [WOR-1099] Fix transposition of flight poll seconds vs cycles

- service/src/main/java/bio/terra/workspace/service/resource/AzureResourceValidationUtils.java
[WX-1472](https://broadworkbench.atlassian.net/browse/WX-1472?atlOrigin=eyJpIjoiYzA2MGI4MjRmZGVjNGFmZGJjZGQ1NTE4ZTk3YTkxYTgiLCJwIjoiaiJ9)
Changed Azure Batch Pool regex to match strings of length 1-64, rather than 0-63. This was likely the intention of the original author (judging by comments and error messages already present) and matches the [Azure Batch API](https://learn.microsoft.com/en-us/rest/api/batchservice/pool/add?view=rest-batchservice-2023-11-01&tabs=HTTP#:~:text=Description-,id,-True) requirements. 
[WX-1472]: https://broadworkbench.atlassian.net/browse/WX-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WX-1472] Batch Pool Regex Fix

- service/src/main/resources/application.yml
https://broadworkbench.atlassian.net/browse/TOAZ-340
M42 will likely try to install the Terra managed app fairly soon. Enable both UAE regions in the LZ service.
* `UAE North` is the one they'll probably use
* ~`UAE Central` is restricted in Azure and generally just used for disaster recovery. Enabling that too though with the same settings.~
I validated on a BEE that these compute SKUs work.
> TOAZ-340: Add UAE regions to LZ service

- openapi/src/common/responses_azure.yaml
- openapi/src/common/schemas_azure.yaml
- openapi/src/parts/controlled_azure_disk.yaml
- openapi/src/parts/controlled_azure_vm.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/ControlledAzureDiskResource.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureDiskTest.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockAzureApi.java
- service/src/test/java/bio/terra/workspace/service/policy/PolicyValidatorTest.java
- service/src/test/java/bio/terra/workspace/service/resource/ResourceValidationUtilsTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/AzureDiskValidationTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateNamespaceRoleStepTest.java
Hey all, not super familiar with WSM.
I added this code then ran then ran all gradle tasks to `generateSwagger[xxx]`, and they all succeeded and I see all the parallel constructs to what appears for other `create-result` endpoints in the generated code directories. I figure its better to post here to see if I'm missing anything obvious while attempting to verify with a locally running WSM in parallel (which is proving to be a bit of a learning curve and something I think would go smoother to pair on).
Seems a bit fishy this was so straight forward, but the resource itself already exists. There's nothing I have to do to make WSM actually track the result, does it do this already for controlled resources and just wasn't exposing it?
> [IA-4632] Add disk create-result

- .github/workflows/release-promotion-tests.yml
Sherlock's v2 endpoints are deprecated in favor of the v3 ones. For the purposes of this repo's workflows, they're equivalent (they have `chart`, `appVersionExact` and `chartVersionExact` in the same structure).
This PR also passes the GHA workflow's OIDC token to Sherlock, which is a best practice that allows Sherlock to understand more about the call (it can log what workflow the request came from, for example). For more examples of this, see any of the client-* reusable workflows in Sherlock's own repository ([example](https://github.com/broadinstitute/sherlock/blob/main/.github/workflows/client-report-app-version.yaml#L253)).
> [DDO-3470] Use Sherlock v3 in GitHub Actions

- .github/workflows/test.yml
We need to move away from pulling from vault directly in github actions as we move away from vault.
* Shifts the "test" workflow over to vault; the needed azure secrets are now present and rendered to a config file
> [WOR-1463] Remove vault token from Test workflow

- service/src/main/java/bio/terra/workspace/service/iam/model/SamConstants.java
- service/src/main/java/bio/terra/workspace/service/job/JobService.java
[Related Sam PR](https://github.com/broadinstitute/sam/pull/1351)
We want to shift to using a non-auth-domain-constrainable action for the purposes of pulling job results. This is because leo polls using it's SA which will likely not be in auth domains, ever.
* Change the job service verification methods to check `read_job_result`
> [WOR-1518] Shift to READ_JOB_RESULT when verifying access to job results

- openapi/src/parts/controlled_azure_database.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureDatabaseTest.java
- service/src/test/java/bio/terra/workspace/common/mocks/MockAzureApi.java
JIRA Ticket: https://broadworkbench.atlassian.net/browse/IA-4633
This PR adds the following endpoints:
- An async delete database post to rerun the job ID
- A get delete-result database endpoint to retrieve the status of the delete database job
We are doing this so that Leonardo can properly poll for the status of the database deletion job, instead of assuming that the operation is really done sync (e.g. Leo marks the database as `deleted` immediately, but something goes wrong with the deletion on the WSM side)
Tested on a BEE with the following steps:
- Create a database
- Delete the database using the new async endpoint and make sure a job id is in the response body
- Use the get delete-result endpoint with this job id until the status is `SUCCESS`
> [IA-4584] Add a delete database result endpoint

- .github/workflows/release-promotion-tests.yml
The `Release promotion tests` workflow still has a vault dependency. This needs to be shifted to using github secrets. In my testing, I observed that this flow runs only in the staging environment so I've removed the parameterization as well. We should reflect on the need and contents of these promo tests going forward, but this is not that PR.
[Successful run](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/8142150720/job/22251055856)
> [WOR-1463] Remove vault dependency from staging promotion workflow

- integration/build.gradle
- service/gradle/dependencies.gradle
https://broadworkbench.atlassian.net/browse/DC-839
___
With the [Spring boot upgrade](https://github.com/DataBiosphere/jade-data-repo/pull/1581) for data repo, we're switching back to only publishing to one Jakarta backed client. This PR moves your references to the jakarta client back to the main data repo client and bumps to the latest version. This is an effort to alleviate any confusion around upgrading past the last supported datarepo-jakarta-client version.
> DC-839: Move references back to datarepo-client; Upgrade to latest

- openapi/src/common/schemas_azure.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/test/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiControllerAzureDiskTest.java
I copied code inappropriately here, and the if statement was causing `resource` to be null on the initial create call. 
We need to delete resourceId from the payload that can be returned from a `-result` API here, since there is no way to retrieve a `resourceId` from a `jobId` if the job is not completed, only the `jobReport`.
> [IA-4592] fix NPE

- openapi/src/parts/workspace.yaml
- service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneWorkspaceFlight.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/create/workspace/WorkspaceCreateFlight.java
- service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java
Ticket: [WOR-1561](https://broadworkbench.atlassian.net/browse/WOR-1561)
- make spend profile id an optional parameter when cloning a workspace
- move policy-specific steps in `CreateWorkspaceFlight` out of `MC_WORKSPACE` case so cloned Rawls stage workspaces will inherit policy from their source workspace
[WOR-1561]: https://broadworkbench.atlassian.net/browse/WOR-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WOR-1561] Modifications to cloneWorkspace to support Rawls stage workspaces

- service/gradle/dependencies.gradle
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunner.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateKubernetesNamespaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteKubernetesNamespaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/KubernetesNamespaceGuardStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetFederatedIdentityStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDatabaseConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunnerTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateKubernetesNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteKubernetesNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/KubernetesNamespaceGuardStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1566
This change was motivated by a desire to address a security vulnerability with jose4j, a transitive dependency of the Kubernetes client. Upgrading the client brought this dependency past its vulnerability without needing to explicitly pin it.
Breaking changes were introduced in v20.0.0: optional parameters are now consolidated into a single object, and we must explicitly execute our requests (the client now supports different flavors of execution such as async).
> [WOR-1566] Upgrade io.kubernetes:client-java to 20.0.1

- service/gradle/dependencies.gradle
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunner.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateKubernetesNamespaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteKubernetesNamespaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/KubernetesNamespaceGuardStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetFederatedIdentityStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDatabaseConnectedTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunnerTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/CreateKubernetesNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteKubernetesNamespaceStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/KubernetesNamespaceGuardStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/CreateFederatedIdentityStepTest.java
This reverts commit cb970d93a4bb88ae29cea452bcaee34d483ac832 resulting from merging https://github.com/DataBiosphere/terra-workspace-manager/pull/1675.
https://github.com/DataBiosphere/terra-workspace-manager/pull/1676#issuecomment-2012861271
> Update on order of operations:
>
> **1. Revert breaking WSM k8s client upgrade**
> 2. Upgrade LZS' TCL from 0.x -> 1.0.9 (to get Stairway's native MDC support but there are some other TCL breaking changes)
> 3. Upgrade LZS' k8s client, TCL from 1.0.9 -> 1.1.0 (smaller TCL version bump)
> 4. Upgrade WSM' k8s client, TCL from 1.0.9 -> 1.1.0, LZS to latest
> Revert "[WOR-1566] Upgrade io.kubernetes:client-java to 20.0.1 (#1675)"

- service/src/main/java/bio/terra/workspace/service/policy/TpsRetry.java
These exceptions can occur when there are low-level IO issues (socket timeout, etc.). They bypass the retry mechanism due to the exception filter on ApiException, causing flakiness with tests (and presumably in actual usage).
> [WOR-1586] Handle processing exception in TpsRetry

- openapi/src/parts/resource.yaml
- service/src/main/java/bio/terra/workspace/app/controller/ResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/WsmResourceService.java
- service/src/test/java/bio/terra/workspace/app/controller/ResourceApiControllerUnitTest.java
[WOR-1519](https://broadworkbench.atlassian.net/browse/WOR-1519)
Adds an endpoint to look up reasources by name, instead of enumerating all the resources in a workspace.
If the user does not have access to the entire workspace, access is checked for the specific resource instead.
Using the new endpoint, I was able to get leo to create apps a workspace with an auth domain, in a BEE.
With the first attempt, the app creation still failed, because of a new call to retrieve the workspace description. After pushing a version that didn't have that call, leo was able to successfully create the apps.
Fixing that call will require a separate solution.
[WOR-1519]: https://broadworkbench.atlassian.net/browse/WOR-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> WOR-1519: add method to retrieve a resource of a workspace by name

- service/src/main/java/bio/terra/workspace/service/policy/PolicyValidator.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsUtilities.java
- service/src/main/java/bio/terra/workspace/service/workspace/flight/cloud/azure/ValidateLandingZoneAgainstPolicyStep.java
- service/src/test/java/bio/terra/workspace/service/policy/PolicyValidatorTest.java
- service/src/test/java/bio/terra/workspace/service/workspace/flight/azure/ValidateLandingZoneAgainstPolicyStepTest.java
[WOR-1594](https://broadworkbench.atlassian.net/browse/WOR-1594)
* Adds a check to require a `protected-data` if the `data-tracking` policy is present.
* Adds unit tests for step that previously had none
* Change existing spring-boot test suite to normal unit test 
[WOR-1594]: https://broadworkbench.atlassian.net/browse/WOR-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WOR-1594: Ensure that PHI workspaces can only be created in protected-data landing zones

- service/src/test/java/bio/terra/workspace/pact/WdsContractVerificationTest.java
Adjusts the pact setup to produce a response that matches the latest pact changes made in https://github.com/DataBiosphere/terra-workspace-data-service/pull/696
> AJ-1705: Adjust verification to match latest pact.

- service/src/test/java/bio/terra/workspace/pact/WdsContractVerificationTest.java
https://broadworkbench.atlassian.net/browse/AJ-1705
Trying to get the WDS / WSM Pact verified...
We're seeing errors like:
```
"mismatches": [
{
"attribute": "body",
"description": "Expected [{\"key\":\"key\",\"value\":\"purpose\"}, {\"key\":\"value\",\"value\":\"policy\"}] to have maximum 1",
"diff": null,
"identifier": "$.resources.0.metadata.properties"
},
{
"attribute": "body",
"description": "Expected [{\"key\":\"key\",\"value\":\"purpose\"}, {\"key\":\"value\",\"value\":\"policy\"}] to have maximum 1",
"diff": null,
"identifier": "$.resources.1.metadata.properties"
},
{
"attribute": "body",
"description": "Expected [{\"key\":\"key\",\"value\":\"purpose\"}, {\"key\":\"value\",\"value\":\"policy\"}] to have maximum 1",
"diff": null,
"identifier": "$.resources.2.metadata.properties"
} …
```
> [AJ-1705] Fix enumerate snapshots response for WDS Pact

- service/dependencies.gradle
- service/src/main/java/bio/terra/workspace/amalgam/AMALGAM_README.md
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/AmalgamatedLandingZoneService.java
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingApiClientTypeAdapter.java
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java
- service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/WorkspaceLandingZoneService.java
- service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiControllerTest.java
- service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatchTest.java
We want to be able to replace our calls to the "amalgamated" landing zone library with HTTP calls to a live landing zone service API. This is the first in a series of PRs that will allows us to switch between using the amalgamated library and live calls. The size of this change is pushing up on what my limit for what's a digestible change, so I'm PRing this first step.
* Extracts a [common interface](https://github.com/DataBiosphere/terra-workspace-manager/pull/1709/files#diff-b94670fab36c36a4570005adfc7170b0589b5320871e9311ba466358baffcaf6) that abstracts operations against landing zones
* The sole implementation in this PR uses the existing amalgamated library calls
* The interface consumes (mostly) Java primitives for its parameters rather than amalgamated or api client library types. …
> [WOR-1127] Extract an interface for landing zone service operations (step 1)

- service/src/main/java/bio/terra/workspace/app/controller/GlobalExceptionHandler.java
404s in WSM are not handled gracefully; they can either spawn a 500 (due to not handling the generic NoResourceFoundException exception type in the global exception handler when non-api matching requests are made like wsm_host/api/foo) or a 404 which emits a ton of unneeded logging (like when a matching URL is hit but a specific workspace resource is not found)
> [WOR-1637] Handle not found exceptions

- .github/workflows/release-promotion-tests.yml
Unfortunately another instance of this workflow failing (it was also impacted by the Sherlock v3 migration not too long ago) -- this seems to be one of the only IAP/Sherlock-accessors that DevOps doesn't have direct control over. My bad for not preparing a PR here in advance, I always forget that this exists until I'm trying to clean-up after off-hours maintenance. (It seems this repo's automation has automatically @'ed people for review off-hours -- sorry!)
I had a successful run [here](https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/8871845520/job/24355698223) (at least, it got past the IAP change). The first attempt did fail, I tweaked config on our end and re-ran.
> [DDO-3622] Use new IAP and Sherlock URL

- service/src/main/resources/application.yml
We should be up to date with the latest version of the Azure linux monitor [extension](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-extension-versions).
> [WOR-1279] Bump default AzureMonitorLinuxAgent extension version to latest

- service/dependencies.gradle
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
Bump the version of the Sam java client to `v0.0.229`.
Necessary to take advantage of some new endpoints (`actionManagedIdentity`) in a future branch.
> [WX-1593] Update Sam Client

- service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessService.java
- service/src/test/java/bio/terra/workspace/app/controller/CreateAzureStorageContainerSasTokenTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureStorageAccessServiceUnitTest.java
Ticket: [WOR-1667](https://broadworkbench.atlassian.net/browse/WOR-1667)
* The SAS token API receives heavy bursts of traffic that have brought WSM down before. This PR introduces caching for all four Sam calls in this code path to alleviate the load that these heavy bursts of traffic place on WSM and Sam.
* A fix for this performance issue was initially attempted with https://broadworkbench.atlassian.net/browse/WOR-1335, but that was rolled back due to failures in our tests. This PR takes a more targeted approach that will have a smaller impact on upstream services.
[WOR-1667]: https://broadworkbench.atlassian.net/browse/WOR-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WOR-1667] Cache Sam responses when creating SAS tokens

- service/dependencies.gradle
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/iam/model/SamConstants.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/ControlledAzureBatchPoolResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/CreateAzureBatchPoolStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetActionManagedIdentityStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetActionManagedIdentityStepTest.java
When creating a batch pool, WSM will check Sam if the user has access to an 'Action Managed Identity'. If they do, it will be assigned to the Batch Pool. This enables users to pull images from private Azure Container Repositories.
> [WX-1593] Assign Action Managed Identities to Batch Pool

- service/src/test/java/bio/terra/workspace/pact/landingzones/LzJobsApiPactTest.java
- service/src/test/java/bio/terra/workspace/pact/landingzones/LzReadApiTest.java
Webhooks firing into LZS on can-i-deploy are failing. My current hypothesis is that this is related to the provider name being different in lzs and terra-helmfile ("terra-landing-zone-service" vs "landingzone"). I've deleted the pact in the broker so can-i-deploy should pass and updated the provider here. Next step is to update the provider name in LZS and publish a new pact.
> Switch provider name

- service/src/main/java/bio/terra/workspace/app/configuration/external/CrlConfiguration.java
- service/src/main/java/bio/terra/workspace/service/crl/CrlService.java
Friends with: https://github.com/broadinstitute/terra-helmfile/pull/5586/
Make the Janitor resource TTL configurable, instead of hard-coded to 1 hour. We want the ability to have different cleanup TTLs in different BEE environments.
> [DDO-3710] Make janitor ttl configurable

- scripts/build_and_push.sh
- service/src/main/java/bio/terra/workspace/common/logging/FlightMetricsHook.java
- service/src/main/java/bio/terra/workspace/common/logging/TaskMetrics.java
- service/src/main/java/bio/terra/workspace/service/job/StairwayInitializerService.java
- service/src/test/java/bio/terra/workspace/common/logging/FlightMetricsHookTest.java
- service/src/test/java/bio/terra/workspace/common/utils/TestFlightContext.java
- service/src/test/java/bio/terra/workspace/service/job/StairwayInitializerServiceTest.java
We want to capture the success/failure rate of flights. 
Introduces a `FlightMetricsHook` class. This is a stairway lifecycle hook that emits a micrometer timer at the end of steps and flights. The metrics are namespaced in the following manner:
For flight-level data:
```
stairway_flight_<flight_class_name>_duration_seconds_<metric>
```
For step-level data:
```
stairway_flight_<flight_class_name>_step_<step_class_name>_duration_seconds_<metric>
```
The following tags are attached to both types of metrics:
* Status: Final status of the flight
* Resource type: Cloud resource type; this is only emitted in the case of flights with a `RESOURCE_TYPE` value in their input parameters (i.e,. `CreateControlledCloudResourceFlight`). It is omitted otherwise. …
> [WOR-1507] Capture metrics and status for flights and steps

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/ControlledAzureBatchPoolResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/VerifyAzureBatchPoolCanBeCreatedStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/VerifyAzureBatchPoolCanBeCreatedStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1620
Switches batch account validation to use the WSM service account token to retrieve the landing zone, similar to other places.
> WOR-1620 WSM 404s during deployment of batch pool

- service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
[WOR-1772](https://broadworkbench.atlassian.net/browse/WOR-1772)
* If WSM tries to get a PAO and gets a 404, but gets a duplicate exception when it tries to create a new one, then the PAO exists in TPS, but it has been deleted. A workspace's PAO will only be deleted if the workspace itself is in the process of being deleted. To prevent WSM from throwing exceptions if a user tries to get a workspace between when the PAO is deleted and the rest of the workspace is deleted, WSM will catch the duplicate exception thrown when re-creating and return null.
[WOR-1772]: https://broadworkbench.atlassian.net/browse/WOR-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WOR-1772] Catch duplicate PAO exception when trying to create a PAO that has been deleted

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/DeleteAzureControlledResourceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/RemoveManagedIdentitiesAzureVmStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/DeleteAzureDatabaseStepUnitTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/RemoveManagedIdentitiesAzureVmStepUnitTest.java
Fixes two instances of `ManagementException`s that were not being handled:
* Exceptions encountered by LandingZoneService when retrieving resources
* Exceptions being handled in a shared helper class
> WOR-1777 Handle remaining instances of missing azure resources

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/DeleteAzureControlledResourceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/DeleteAzureBatchPoolStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/DeleteAzureDatabaseStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/DeleteAzureDiskStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/DetachAzureDiskFromVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/GetAzureDiskAttachedVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteKubernetesNamespaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/DeleteNamespaceRoleStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/DeleteAzureManagedIdentityStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/DeleteFederatedCredentialStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storageContainer/DeleteAzureStorageContainerStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/DeleteAzureNetworkInterfaceStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/DeleteAzureVmStep.java
- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/RemoveManagedIdentitiesAzureVmStep.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/DeleteAzureDatabaseStepUnitTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/DetachAzureDiskFromVmStepTest.java
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/disk/GetAzureDiskAttachedVmStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1777
* change GetAzureDiskAttachedVmStep to extend DeleteAzureControlledResourceStep for management exception handling
The output of GetAzureDiskAttachedVmStep is only used by `DetachAzureDiskFromVmStep`, which is already set up to handle a missing value.
* change `DetachAzureDiskFromVmStep` to extend `DeleteAzureControlledResourceStep`
* Parameterize DeleteAzureControlledResourceStep, for better/more central logging options: There was only one step that  didn't already have a parameter named `resource`, of the appropriate type, and that was trivial to add.
* Added `LandingZoneNotFoundException` to common error handling
Because this is changing the parameters of the `FlightMap`, it could cause a running flight to log a `NullPointerException` …
> WOR-1777 Handle more instances of ManagementExceptions when deleting resources

- service/src/main/java/bio/terra/workspace/app/StartupInitializer.java
- service/src/main/java/bio/terra/workspace/app/configuration/external/BufferServiceConfiguration.java
- service/src/main/java/bio/terra/workspace/app/configuration/external/PolicyServiceConfiguration.java
- service/src/main/java/bio/terra/workspace/service/buffer/BufferService.java
- service/src/main/java/bio/terra/workspace/service/iam/SamService.java
- service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
- service/src/test/java/bio/terra/workspace/app/StartupInitializerTest.java
In testing Helmfile changes to credentials configuration, it was difficult to tell if WSM external service credentials were configured properly without firing live requests at it (i.e,. the service configuration may be valid yaml, but I may have introduced a typo in the credentials path, which did not manifest until actual live workspace traffic was fired at the application resulting in a 500)
* Verifies that credentials are in the right place during application bootstrap. 
* Register the WSM SA with Sam (if needed) during bootstrap, rather than waiting for the creation of a controlled resource. 
* I considered adding TPS + buffer to the WSM status endpoint checks; I've decided not to as I view those as important but non-critical services for a k8s status check. I've left the status hooks …
> [WOR-1799] Verify policy service and buffer service credentials and register WSM SA at bootstrap

- .github/workflows/full-integration-tests.yml
- .github/workflows/full-service-tests.yml
- .github/workflows/pr-integration.yml
- .github/workflows/release-promotion-tests.yml
- .github/workflows/test.yml
Ticket: [CORE-97](https://broadworkbench.atlassian.net/browse/CORE-97)
- move #dsp-workspaces-test-alerts to #dsp-core-services-alerts
[CORE-97]: https://broadworkbench.atlassian.net/browse/CORE-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CORE-97] Route Workspaces team alerts to Core Services slack channel

- service/dependencies.gradle
https://broadworkbench.atlassian.net/browse/CORE-119
Once this [PR is merged and released](https://github.com/DataBiosphere/terra-aws-resource-discovery/pull/51), This PR bumps the `bio.terra terra-aws-resource-discovery` version to `v0.6.4-SNAPSHOT` to include the recent security fix for Apache Avro ([CVE-2024-47561](https://github.com/advisories/GHSA-r7pg-v2c8-mfg3)), ensuring downstream projects use the secure version.
- Updated to `v0.6.4-SNAPSHOT` to include Apache Avro 1.12.0.
> [CORE-119] Update terra-aws-resource-discovery dependency version

- scripts/write-config.sh
Ticket: [CORE-142](https://broadworkbench.atlassian.net/browse/CORE-142)
* Pull secrets from GSM instead of Vault when writing config
* Remove support for staging
* WSM's staging secrets are available in GSM if we need them, but I don't know any reasons that this script needs to support staging. The script was never updated to pull staging TPS secrets even though TPS has been in staging for >1 year which tells me no one was using this for staging.
* Remove support for alpha and personal environments that no longer exist
[CORE-142]: https://broadworkbench.atlassian.net/browse/CORE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CORE-142] Remove Vault usage and unused environment support from write-config.sh

- service/src/main/resources/application.yml
Ticket: [CORE-142](https://broadworkbench.atlassian.net/browse/CORE-142)
* `workspace_manager_v11` was deleted in RBS. Use the new pool
[CORE-142]: https://broadworkbench.atlassian.net/browse/CORE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CORE-142] Use new RBS pool

- integration/build.gradle
- service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
These two tests have been failing for weeks, but they test unused portions of the code, so I've simply disabled them.
See https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/12127185095 for a successful test run on this branch.
> [CORE-69] Disable irrelevant tests

- integration/build.gradle
Use matching versions for the `bio.terra:terra-test-runner` library and the `bio.terra.test-runner-plugin` plugin.
> CORE-69: update test runner library

- integration/build.gradle
- service/dependencies.gradle
Uses a consistent version of the Sam client across integration tests and runtime; updates that version to latest.
> CORE-69: use latest Sam client

- .github/workflows/server-startup-test.yaml
- .github/workflows/tag-publish.yml
- .github/workflows/workflow-tester.yml
Jira: [\<Link to Jira ticket\>](https://broadworkbench.atlassian.net/browse/CORE-246)
What:
Upgrades all actions/cache to v4
Why:
The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache
How:
This makes all our repos use the same version of actions/cache.
> CORE-246 Upgrading to cache v4

- azureDatabaseUtils/build.gradle
- buildSrc/build.gradle
- integration/build.gradle
- service/build.gradle
- settings.gradle
Copy of #1825, but without the Spring Boot update.
#1825 has test failures; this PR does not. My assumption is that the test failures are caused by one of two things:
1. The Spring Boot update. After this PR merges I will make another one for Spring Boot; we'll see how that one does
2. A difference in secrets used by Dependabot vs. by me (i.e. the "Dependabot" vs. "Actions" distinction in repo secrets). I suspect this is the culprit and will continue to investigate.
---
Bumps the minor-patch-dependencies group with 6 updates in the / directory:
| Package | From | To |
| --- | --- | --- |
| io.swagger.core.v3:swagger-annotations | `2.2.27` | `2.2.28` |
| com.github.ben-manes.versions | `0.51.0` | `0.52.0` |
| org.gradle.test-retry | `1.6.0` | `1.6.1` |
| …
> CORE-69 minor deps no spring boot

- service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunner.java
- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseUtilsRunnerTest.java
After looking into it, the azure unit tests were an isolated issue. Any problems we're seeing in production are not directly related to the test failures. However, this PR has an experiment to try to address production, too.
In this PR:
* fix a test assertion in `AzureDatabaseUtilsRunner` that was broken in #1806
* default to the correct value (`AzureCloud`, not `AZURE`) for the azure environment
> CORE-338: fix Azure unit tests, maybe fix live database utils

- buildSrc/src/main/groovy/terra-workspace-manager.java-spring-conventions.gradle
- integration/build.gradle
- service/dependencies.gradle
- service/src/main/java/bio/terra/workspace/service/spendprofile/SpendProfileService.java
- service/src/main/resources/application.yml
TCL 1.1.38 has the same version of Spring Boot that WSM uses, so I'm hoping to use that. Many test failures.
> CORE-391: upgrade TCL to 1.1.38

- integration/build.gradle
- service/dependencies.gradle
https://broadworkbench.atlassian.net/browse/CORE-376
Update TCL to get its fix for the "failed to export spans" error.
See https://github.com/DataBiosphere/terra-common-lib/pull/229
> CORE-376: turn off double-tracing and 'failed to export spans' error

- .github/workflows/test.yml
https://broadworkbench.atlassian.net/browse/CORE-486
Tests where WSM calls any real google things are failing because permissions are messed up. But we don't care enough to fix it so we are disabling tests that do this. This PR stops call connected tests. Integration tests have been disabled in GitHub.
> CORE-486 don't call connected tests

- service/dependencies.gradle
Ticket: https://broadworkbench.atlassian.net/browse/CORE-540
---
> [CORE-540] Upgrade commons-beanutils to 1.11.0

- .github/workflows/verify_consumer_pacts.yaml
Part of https://broadworkbench.atlassian.net/browse/CORE-504 but does not complete that ticket.
WSM's pacts are all with services that are on their way out, and have been failing recently.  It's not worth fixing, so this PR turns off running the verification unless specifically triggered.
> [CORE-504] Disable pact verification
