DataBiosphere/terra-workspace-manager

src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
src/main/java/bio/terra/workspace/service/create/CreateService.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/workspace/service/create/CreateServiceTest.java
src/test/java/bio/terra/workspace/service/get/GetServiceTest.java

Changing CreateWorkspace to be synchronous, per this week's discussion.

Revert CreateWorkspace to synch instead of async. Still uses stairway

---

src/main/resources/api/service_openapi.yaml

Minor nit that I noticed, just wanted to take care of it before these field names moved down into the rawls and orch portions of the TDR integration

consistent naming scheme

---

README.md

(I updated local-dev documentation, but forgot the main README)

Change swagger-ui location in README

---

build.gradle
src/main/java/bio/terra/workspace/app/configuration/ApiResourceConfig.java
src/main/resources/api/service_openapi.yaml
src/main/resources/api/swagger-ui.html

Hopefully non-controversial. Nothing here requires any java code changes, and I don't believe it would affect what's published.

Some initial OAS cleanup [pre- AS-391]

---

local-dev/skaffold.yaml.template
local-dev/values.yaml.template
src/main/resources/application.properties

[Related PR](https://github.com/broadinstitute/terra-helm/pull/96)

Add variable for DB hostname

---

src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java

Adds an integration test which creates and then deletes a reference to a known snapshot in Data Repo's `dev` instance. This uses the same known snapshot as the `createDataReference` test, though the tests do not share a workspace or reference.

[AS-383] Add deleteDataReference integration test

---

src/main/resources/application.yml
src/test/resources/application-integration-test.yml

Depends on https://github.com/broadinstitute/firecloud-develop/pull/2295

Cleanup after config overhaul [post- AS-396]

---

src/main/java/bio/terra/workspace/service/datareference/exception/DataRepoAuthorizationException.java
src/main/java/bio/terra/workspace/service/datareference/exception/DataRepoInternalServerErrorException.java
src/main/java/bio/terra/workspace/service/datarepo/DataRepoService.java

Add additional error messages for various HTTP status errors when accessing a snapshot in a workspace.

[AS-454] Improve error messaging when creating Data Repo snapshots in a workspace

---

src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
src/main/java/bio/terra/workspace/service/workspace/exceptions/StageDisabledException.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java

Also add check for MC_WORKSPACE stage before creating the google context.
Things not in this PR.
- Jobs API. pending further discussion.
- Integration tests. Need Sam resources and means to use the client library for integration testing. I don't have strong feelings on the ordering of the tests vs this PR.
- Job id idempotency on create google context. Going to wait for Zach's work to add this for creating workspaces.

PF-153 Add endpoints create/delete google context.

---

src/test/java/bio/terra/workspace/connected/UserAccessUtils.java
src/test/java/bio/terra/workspace/service/spendprofile/SpendProfileServiceTest.java
src/test/resources/application-connected-test.yml

Add the first Sam connected test.
I manually created a `spend-profile` resource in dev Sam for Mr. Thunderlord. Details included in comments on `connected-test.yml`.

PF-186 Add Sam connected test for SpendProfileService.

---

src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java

WorkspaceDeleteFlight deletes the cloud project so this comment is no longer accurate

[no-ticket] update deleteWorkspace comment

---

README.md

No ticket, this is a documentation change only.

[no ticket] Add config resolution priority link to readme

---

src/main/java/bio/terra/workspace/service/iam/model/IamRole.java
src/main/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextRBSFlight.java
src/main/java/bio/terra/workspace/service/workspace/flight/DeleteGoogleContextFlight.java
src/main/java/bio/terra/workspace/service/workspace/flight/GenerateResourceIdStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/PullProjectFromPoolStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlight.java
src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextRBSFlightTest.java

Fixing flight structure, per https://docs.google.com/document/d/1qJz0e1zzp28jV_3bVN9zwbu582sfUXDMd4Mw19v66Io/edit?ts=5fdcd66e&resourcekey=0-3gLFZURTsw6zPjLiEs2agA#

Tn pf 301 fix flight structure

---

.github/CODEOWNERS

Starting point for code owners for WM

[PF-352] Create code owners for WM

---

.github/workflows/build.yml

Apparently, `[[ false ]]` is true...

Fix image tag construction

---

src/main/java/bio/terra/workspace/app/configuration/external/BufferServiceConfiguration.java
src/main/resources/application.yml
src/test/resources/application-test.yml

[PF-326] Update Workspace Manager environment variable names to work with Helm

---

.github/CODEOWNERS

PF-398 Remove code owners file

---

src/main/java/bio/terra/workspace/app/configuration/external/BufferServiceConfiguration.java
src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
src/main/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextRBSFlight.java
src/main/java/bio/terra/workspace/service/workspace/flight/PullProjectFromPoolStep.java
src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextRBSFlightTest.java
src/test/resources/application-test.yml

- Adding an enabled field to BufferServiceConfiguration to turn the integration on.
- Factoring EnableServicesStep out of CreateProjectStep (did not fully refactor as CreateProjectStep will be deleted)
- Adding the rest of the flight needed to configure the project.

[PF-325] Add support for WSM connecting to RBS. This includes:

---

README.md
src/main/java/bio/terra/workspace/app/controller/UnauthenticatedApiController.java
src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
src/main/java/bio/terra/workspace/common/utils/BaseStatusService.java
src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
src/main/java/bio/terra/workspace/db/DataReferenceDao.java
src/main/java/bio/terra/workspace/db/WorkspaceDao.java
src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceStep.java
src/main/java/bio/terra/workspace/service/datareference/utils/DataReferenceValidationUtils.java
src/main/java/bio/terra/workspace/service/datarepo/DataRepoService.java
src/main/java/bio/terra/workspace/service/iam/AuthHeaderKeys.java
src/main/java/bio/terra/workspace/service/iam/SamService.java
src/main/java/bio/terra/workspace/service/iam/model/IamRole.java
src/main/java/bio/terra/workspace/service/job/JobBuilder.java
src/main/java/bio/terra/workspace/service/job/JobMapKeys.java
src/main/java/bio/terra/workspace/service/job/JobService.java
src/main/java/bio/terra/workspace/service/migrate/MigrateService.java
src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceAuthzStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/DeleteProjectStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceAuthzStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/DeleteWorkspaceStateStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/GoogleCloudSyncStep.java
src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java
src/test/java/bio/terra/workspace/service/job/JobServiceTest.java
src/test/java/bio/terra/workspace/service/job/JobServiceTestStep.java
workspace-manager-clienttests/src/main/java/scripts/utils/WorkspaceTestScriptBase.java

`Analyze | Code cleanup...` menu in IJ Ultimate 2020.2. This mostly caught places where `final` could be profitably added to class members.

PF-386: IntelliJ Cleanup changes

---

src/main/java/bio/terra/workspace/common/utils/ControllerValidationUtils.java
src/main/java/bio/terra/workspace/service/workspace/flight/PullProjectFromPoolStep.java
src/main/resources/api/service_openapi.yaml

removing un-designed credential argument and code to ensure it's not  present.

PF-385: remove credentialId from CreateDataReferenceRequestBody

---

build.gradle
src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
src/main/java/bio/terra/workspace/app/controller/common/ReferenceController.java
src/main/java/bio/terra/workspace/common/utils/ControllerTranslationUtils.java
src/main/java/bio/terra/workspace/db/DataReferenceDao.java
src/main/java/bio/terra/workspace/service/datareference/DataReferenceService.java
src/main/java/bio/terra/workspace/service/datareference/flight/CreateDataReferenceStep.java
src/main/java/bio/terra/workspace/service/datareference/flight/DataReferenceFlightMapKeys.java
src/main/java/bio/terra/workspace/service/datareference/model/DataReference.java
src/main/java/bio/terra/workspace/service/datareference/model/DataReferenceRequest.java
src/main/resources/api/service_openapi.yaml
src/main/resources/db/changelog.xml
src/main/resources/db/changesets/20210212_rename_description.yaml
src/test/java/bio/terra/workspace/db/DataReferenceDaoTest.java
src/test/java/bio/terra/workspace/service/datareference/DataReferenceServiceTest.java

Also ensures that an omitted description is a blank string instead of null.
Once this is good to go I'll publish the new client.

rename referenceDescription to description [AS-512]

---

src/main/java/bio/terra/workspace/service/resource/controlled/flight/CreateControlledResourceFlight.java
src/main/java/bio/terra/workspace/service/resource/controlled/flight/CreateGcsBucketStep.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateGcsBucketStepTest.java
src/test/java/bio/terra/workspace/service/resource/controlled/flight/StoreControlledResourceMetadataStepTest.java

Next step of the flight is to create a GCS bucket.

[PF-415] Step to create GCS Bucket

---

build.gradle

Copied from [janitor](https://github.com/DataBiosphere/terra-resource-janitor/blob/603db78f0a985e7f64d6feaefa6896e3f1c4dce7/build.gradle#L128) and [buffer](https://github.com/DataBiosphere/terra-resource-buffer/blob/eb26012e4f745ead2c749f6ddc4acc86e953b265/build.gradle#L138)

add google cloud profiler client [AS-640]

---

build.gradle
src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
src/main/java/bio/terra/workspace/db/WorkspaceDao.java
src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
src/main/java/bio/terra/workspace/service/workspace/flight/CreateWorkspaceStep.java
src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
src/main/java/bio/terra/workspace/service/workspace/model/WorkspaceRequest.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java
workspace-manager-clienttests/build.gradle
workspace-manager-clienttests/src/main/java/scripts/testscripts/WorkspaceLifecycle.java
workspace-manager-clienttests/src/main/resources/configs/integration/WorkspaceLifecycle.json
workspace-manager-clienttests/src/main/resources/configs/perf/WorkspaceLifecycle.json
workspace-manager-clienttests/src/main/resources/suites/BasicIntegration.json
workspace-manager-clienttests/src/main/resources/suites/BasicPerf.json

- Define new API for UpdateWorkspace.
- Add displayName and description fields as needed.
- Implement UpdateWorkspace in the controller and the service.

[PF-529] Add functionality to update a workspace.

---

build.gradle
gradle.lockfile
src/main/java/bio/terra/workspace/app/Main.java
src/main/java/bio/terra/workspace/service/job/JobService.java
src/main/resources/application.yml
src/test/resources/application-test.yml

Decided to roll this back ahead of the release Monday.
revert 75a8c0e5f7d623fdce4a7d71beca7bd29e8cf71a

PF-522: roll back Multi-instance changes

---

src/main/java/bio/terra/workspace/common/utils/DelayHook.java

Delay hook for manual testing and debugging. Makes a flight step take arbitrarily long.

PF-522: delay hook

---

README.md
src/test/java/bio/terra/workspace/integration/WorkspaceIntegrationTest.java

Update readme with non-split VPN caveat
Remove note about unavailability of a prod environment

[no ticket] Update readme with non-split VPN caveat

---

.github/workflows/build.yml
.github/workflows/tag-publish.yml

This workflow is not done, but I need to merge it in order to debug it. When it is ready, I will uncomment the merge trigger.

PF-637 publish on merge

---

src/main/java/bio/terra/workspace/app/controller/ResourceController.java
src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAiNotebookInstanceResource.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/workspace/service/resource/MakeApiResourceDescriptionTest.java

Also update a TODO for more parameters to a new ticket number.

PF-469 Support controlled AI notebook instance in enumeration

---

service/src/main/java/bio/terra/workspace/service/workspace/flight/CreateCustomGcpRolesStep.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/CreateGoogleContextFlightTest.java

Populate the title field so that the UI will have something readable to show in that field.

[PF-708] set title field on Role to RoleName value

---

build.gradle

[Plugin](https://gitlab.com/barfuin/gradle-taskinfo) to show task dependencies as a tree and ordering. Supports JSON output for downstream analysis (like a graphviz translator).
I added it to the top level gradle file, since there's no reason to prefer one of the sub-projects.
[Example output](https://gist.github.com/jaycarlton/fe1c15b6723ee22bab33f635ad384a20)

taskInfo plugin

---

service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java

[no ticket] fix logging bug

---

integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
integration/src/main/java/scripts/utils/ClientTestUtils.java
integration/src/main/resources/configs/integration/ControlledGcsBucketLifecycle.json

Instead of waiting a fixed interval, keep trying to access the bucket until it works or we run out of attempts.

[no ticket] poll until we don't get a StorageException

---

integration/src/main/resources/configs/integration/CloneGcsBucket.json
service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java

Missed one comment before checking in #375.

PF-809 fix one more spot

---

.github/workflows/tag-publish.yml
settings.gradle

[PF-749] re-refix tag publish

---

integration/src/main/java/scripts/testscripts/CloneBigQueryDataset.java
integration/src/main/resources/configs/integration/CloneBigQueryDataset.json
integration/src/main/resources/suites/FullIntegration.json
service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java
service/src/main/java/bio/terra/workspace/common/utils/IamRoleUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CopyGcsBucketDefinitionStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CopyBigQueryDatasetDefinitionStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/RetrieveGcsBigQueryDatasetCloudAttributesStep.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/WorkspaceDeleteFlightTest.java

Copy definition using the create dataset flight.

[PF-813] Copy BigQuery Dataset Definition

---

.github/workflows/pr-integration.yml
.github/workflows/tag-publish.yml
.github/workflows/test.yml
DEVELOPMENT.md

The changes are to documentation and the GHAs. When I do the branch rename, I will then want to immediately merge this. It cannot really be tested until I do the branch rename. So I'd like to have this reviewed and approved before I do the rename.

[PF-879] Compensating changes for renaming dev to main

---

integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java

The integration test `PrivateControlledAiNotebookInstanceLifecycle` sometimes fails because GCP may respond with either a 403 or 404 when we attempt to fetch a deleted notebook, depending on timing. This change fixes the test to accept either response instead of just a 404.
I've also added messages to the assertions in this test to make debugging a little clearer.

[No ticket] Fix flakiness in PrivateControlledAiNotebookInstanceLifecycle test

---

AZURE_POC.md
service/build.gradle
service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
service/src/main/java/bio/terra/workspace/app/configuration/external/AzureState.java
service/src/main/java/bio/terra/workspace/app/configuration/external/AzureStateDisabled.java
service/src/main/java/bio/terra/workspace/app/configuration/external/AzureStateEnabled.java
service/src/main/resources/application-azure.yml
service/src/test/java/bio/terra/workspace/app/configuration/external/AzureStateDisabledTest.java
service/src/test/java/bio/terra/workspace/app/configuration/external/AzureStateEnabledTest.java
service/src/test/java/bio/terra/workspace/common/BaseAzureTest.java

- configuration
- feature control
- AZURE_POC readme document

[PF-984] Initial setup

---

AZURE_POC.md
service/src/main/java/bio/terra/workspace/db/IamDao.java
service/src/main/java/bio/terra/workspace/service/iam/AuthenticatedUserRequest.java
service/src/main/java/bio/terra/workspace/service/iam/ProxiedAuthenticatedUserRequestFactory.java
service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
service/src/main/resources/db/changelog.xml
service/src/main/resources/db/changesets/20210914_azure_poc.yaml
service/src/test/java/bio/terra/workspace/db/IamDaoTest.java

First installment of mock Sam. This sets up a couple of database tables, provides a DAO, and a "azure" test for the DAO.
I am going to merge this and then rebase azure-poc from main to pull in the SamService tidying changes.

[PF-984] Setup basic permission tables and write a DAO

---

service/src/main/java/bio/terra/workspace/service/workspace/model/AzureCloudContext.java

Moved the database serialization format version into the serialization class.

[PF-1029] Move version number to make jackson happier

---

integration/src/main/java/scripts/disruptivescripts/DeleteInitialPods.java
integration/src/main/java/scripts/testscripts/CloneBigQueryDataset.java
integration/src/main/java/scripts/testscripts/CloneGcsBucket.java
integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
integration/src/main/java/scripts/testscripts/CloneWorkspace.java
integration/src/main/java/scripts/testscripts/ControlledBigQueryDatasetLifecycle.java
integration/src/main/java/scripts/testscripts/ControlledGcsBucketLifecycle.java
integration/src/main/java/scripts/testscripts/DataReferenceLifecycle.java
integration/src/main/java/scripts/testscripts/DeleteGcpContextWithControlledResource.java
integration/src/main/java/scripts/testscripts/DeleteWorkspaceWithControlledResource.java
integration/src/main/java/scripts/testscripts/EnablePet.java
integration/src/main/java/scripts/testscripts/EnumerateResources.java
integration/src/main/java/scripts/testscripts/ListWorkspaces.java
integration/src/main/java/scripts/testscripts/PrivateControlledAiNotebookInstanceLifecycle.java
integration/src/main/java/scripts/testscripts/PrivateControlledGcsBucketLifecycle.java
integration/src/main/java/scripts/testscripts/RemoveUser.java
integration/src/main/java/scripts/testscripts/ValidateReferencedResources.java
integration/src/main/java/scripts/utils/ClientTestUtils.java
integration/src/main/java/scripts/utils/CloudContextMaker.java
integration/src/main/java/scripts/utils/DataRepoTestScriptBase.java
integration/src/main/java/scripts/utils/GcsBucketTestFixtures.java
integration/src/main/java/scripts/utils/ResourceMaker.java
integration/src/main/java/scripts/utils/ResourceModifier.java
integration/src/main/java/scripts/utils/SamClientUtils.java
integration/src/main/java/scripts/utils/WorkspaceAllocateTestScriptBase.java

This is the result of running `./gradlew spotlessApply` at the top level with no other changes. This is now available after the gradle refactor in #459.

[PF-990] Apply spotless to integration module

---

DEVELOPMENT.md

I noticed some issues when I set up my development environment. Made some adjustment to the doc and hopefully will make the next person's set up easier.

[No ticket] Minor adjustment to the developmenet doc 

---

service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/WsmResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateGcsBucketStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferenceValidationUtilsTest.java

Add char limit to description and privateUserEmail (assigned user).

PF-800: Validation of Controlled Resource Metadata Fields

---

service/src/main/java/bio/terra/workspace/app/configuration/external/AzureConfiguration.java
service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureVmResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateAzureVmStep.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateAzureVmStepTest.java

tried running swagger locally...some small bug fixes
https://broadworkbench.atlassian.net/browse/IA-2986

IA-2986 Small fixes

---

integration/src/main/java/scripts/testscripts/CloneReferencedResources.java
integration/src/main/java/scripts/testscripts/CloneWorkspace.java
integration/src/main/java/scripts/testscripts/ValidateReferencedResources.java
integration/src/main/java/scripts/utils/ClientTestUtils.java
integration/src/main/java/scripts/utils/ResourceMaker.java
service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
service/src/main/java/bio/terra/workspace/app/controller/ResourceController.java
service/src/main/java/bio/terra/workspace/db/ResourceDao.java
service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/WsmResourceType.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsBucketFileAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedGcsBucketFileResource.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/ReferencedResource.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java
service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java

This is a draft. Starting the github actions.

PF-1174: Add reference type bucket file

---

service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
service/src/main/java/bio/terra/workspace/db/ResourceDao.java
service/src/main/java/bio/terra/workspace/service/resource/ValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/WsmResourceType.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureDiskResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureIpResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureNetworkAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureNetworkResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAzureVmResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateAzureNetworkStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateControlledResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/GetAzureNetworkStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteAzureIpStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteAzureNetworkStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteControlledResourceFlight.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateAzureNetworkStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/GetAzureNetworkStepTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/create/azure/CreateControlledResourceFlightTest.java

Unit tests and end to end test added and are passing, merge conflicts have been fixed and tested end to end through swagger as well

[IA-2917] Add create/delete/get Azure Network APIs

---

service/src/main/resources/api/service_openapi.yaml

responses was incorrectly nested under requestBody.

Fix wsm schema broken in last commit.

---

.github/workflows/pr-integration.yml
.github/workflows/tag-publish.yml
.github/workflows/test.yml

Simple edit to remove the targets. Hand tested.

[PF-944] Remove the dev target now that rename to main is done

---

service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledAiNotebookInstanceResource.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledAiNotebookInstanceResourceTest.java

This logic is copied from CLI to keep the auto-gen logic consistent.

[PF-1276] Generate instance id based on user name and date

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteAzureVmStep.java
service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/CreateAndDeleteAzureControlledResourceFlightTest.java

https://broadworkbench.atlassian.net/browse/IA-3097
See [this doc](https://docs.google.com/document/d/1yT3Io_FbOj_RybYl-rtvRAEcEuCgdmhCEMkQCta3XmY/edit) for a bit more context
Tested locally via swagger

IA-3097 delete OS disk and nic during VM deletion

---

service/src/main/resources/application.yml

The service-account field will be populated by a terra-helmfile PR soon to come, the ID will be static across envs.

[IA-3185] Add leo app config

---

service/src/main/java/bio/terra/workspace/service/job/JobService.java
service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java

I missed comments by @zloery at https://github.com/DataBiosphere/terra-workspace-manager/pull/542#pullrequestreview-869401561.

address comments on #542

---

integration/src/main/java/scripts/testscripts/EnumerateJobs.java
service/gradle.lockfile
service/gradle/dependencies.gradle
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
service/src/main/java/bio/terra/workspace/service/crl/CrlService.java
service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceHandler.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/CreateAzureRelayNamespaceStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/DeleteAzureRelayNamespaceStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/GetAzureRelayNamespaceStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/create/CreateControlledResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceFamily.java
service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceType.java
service/src/main/resources/api/service_openapi.yaml
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
service/src/test/java/bio/terra/workspace/common/utils/AzureTestUtils.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/CreateAzureRelayNamespaceStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/GetAzureRelayNamespaceStepTest.java

https://broadworkbench.atlassian.net/browse/TOAZ-36
cc @sergiygetlin

TOAZ-36 Add APIs for Relay Namespace

---

integration/src/main/java/scripts/testscripts/CloneWorkspace.java
integration/src/main/java/scripts/utils/BqDatasetUtils.java
integration/src/main/java/scripts/utils/ClientTestUtils.java
integration/src/main/java/scripts/utils/GcsBucketObjectUtils.java
integration/src/main/java/scripts/utils/GcsBucketUtils.java

Plus standardized the logging around a few test fixtures. We now indicate which errors are expected versus not.

Logging Improvements for CloneWorkspace

---

openapi/src/parts/controlled_azure_relay_namespace.yaml
openapi/src/parts/controlled_azure_vm.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/relayNamespace/ControlledAzureRelayNamespaceResource.java

[no ticket] Make create namespace API async a few other small fixes

---

.github/actions/start-local-server/action.yml
.github/workflows/pr-integration.yml
integration/src/main/resources/suites/FullIntegration.json

This should make flaky tests easier to debug.
Example:
https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2005828712

For PR integration tests, upload WSM logs to GitHub

---

integration/src/main/resources/uploadlists/CompressDirectoryToTerraKernelK8S.json

Fix a mistake in this file from #539 where I copied the wrong bucket name

[No ticket] Fix copy-paste error in test result upload

---

.github/workflows/tag-publish.yml

Multiple choice inputs are [apparently supported now](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs).

options for semver part

---

integration/src/main/java/scripts/testscripts/ReferencedDataRepoSnapshotLifecycle.java
integration/src/main/resources/configs/integration/alpha/ReferencedDataRepoSnapshotLifecycle.json
integration/src/main/resources/configs/integration/staging/ReferencedDataRepoSnapshotLifecycle.json
integration/src/main/resources/suites/alpha/FullIntegration.json
integration/src/main/resources/suites/staging/FullIntegration.json

https://broadworkbench.atlassian.net/browse/WOR-164
- Create TDR datasets/snapshots alpha and staging (done outside of this PR)
- Setup the snapshots for use in WSM alpha and staging tests.
- Add test for `getDataRepoSnapshotReferenceByName`

WOR-164 - setup snapshots tests on alpha and staging

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/StorageTransferServiceUtils.java

Fix a bug where a failed UndoStep causes a dismal failure.

[PF-1500] determine if job exists before trying to delete it

---

openapi/src/parts/controlled_azure_relay_namespace.yaml

https://broadworkbench.atlassian.net/browse/PF-1611

PF-1611 fix get relaynamespace

---

integration/src/main/java/scripts/testscripts/WorkspaceLifecycle.java

Fix this failure:
https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/2237678331

Fix WorkspaceLifecycle perf test

---

.gitignore
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java

https://broadworkbench.atlassian.net/browse/IA-3120
Tested locally

IA-3120 Fix getRelaynamespace API

---

service/src/main/java/bio/terra/workspace/service/job/JobService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/AzureVmHelper.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/DeleteAzureVmStep.java

https://broadworkbench.atlassian.net/browse/IA-3120
When we delete VM, we also need to delete OS disk and nic automatically

IA-3120 fix createAzureVm undo step

---

openapi/src/common/schemas.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledResourceControllerBase.java

https://broadworkbench.atlassian.net/browse/IA-3120

IA-3120 IA-3390 Take an optional resource ID

---

openapi/src/parts/controlled_azure_vm.yaml
service/src/main/java/bio/terra/workspace/common/utils/AzureVmUtils.java
service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java

Extend VM image with version parameter.

TOAZ-128 Create VM endpoint should handle version parameter for the VM image

---

service/src/main/java/bio/terra/workspace/db/ApplicationDao.java
service/src/main/java/bio/terra/workspace/service/workspace/WsmApplicationService.java

All environments have migrated to the new workspace application configuration. This PR removes the fixup code that was part of that migration.

[PF-1407] Remove obsolete fixup code

---

openapi/src/parts/controlled_azure_vm.yaml
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/CreateAzureVmStep.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java

Make public ip optional for VM
https://broadworkbench.atlassian.net/browse/TOAZ-79

TOAZ-79 [WSM] Create VM that has no public IP

---

integration/src/main/resources/configs/integration/WorkspaceLifecycle.json

I'm confused at how this test passed. It takes more than 5 seconds to create a workspace...

[PF-1642] Increase timeout for WorkspaceLifecycle integration test

---

service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/CreateAndDeleteAzureControlledResourceFlightTest.java

https://broadworkbench.atlassian.net/browse/TOAZ-155
Changes:
Fix azuretests so they clean up created resources after themselves.

TOAZ-155 AzureTests doesn't clean up created resources after completion

---

ADDING_RESOURCES.md
integration/src/main/java/scripts/testscripts/ReferencedTerraWorkspaceLifecycle.java
integration/src/main/java/scripts/utils/TestUtils.java
integration/src/main/resources/configs/integration/ReferencedTerraWorkspaceLifecycle.json
integration/src/main/resources/suites/FullIntegration.json
openapi/src/parts/referenced_terra_workspace.yaml
openapi/src/resources/resource_type.yaml
openapi/src/resources/terra_workspace.yaml
service/src/main/java/bio/terra/workspace/app/controller/ReferencedGcpResourceController.java
service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceFamily.java
service/src/main/java/bio/terra/workspace/service/resource/model/WsmResourceType.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/terra/workspace/ReferencedTerraWorkspaceAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/terra/workspace/ReferencedTerraWorkspaceHandler.java
service/src/main/java/bio/terra/workspace/service/resource/referenced/terra/workspace/ReferencedTerraWorkspaceResource.java
service/src/test/java/bio/terra/workspace/service/resource/referenced/ReferencedResourceServiceTest.java

Did some manual testing via Swagger.

[PF-1736] Implement new TERRA_WORKSPACE resource

---

.github/workflows/nightly-tests.yml

Copied from the PR integration test flow. To be honest I'm not sure how we've gone this long without needing these logs...

[PF-1801] Upload server-side logs for nightly integration tests

---

.github/actions/integration-test/action.yml

Thanks @ichengchang for spotting this and proposing the fix!

[PF-1814] Upload integration test results even on failure

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh

Re-creating Nicole's PR (#704) from a branch instead of a fork to see if that fixes the GHA errors

[PF-1806] Recreate Nicole's dsub PR

---

service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
service/src/main/resources/application.yml
service/src/test/java/bio/terra/workspace/service/resource/ValidationUtilsTest.java

now support bitbucket, gitlab, azure and aws.

[PF-1698] Add more git server to the allowlist

---

service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/bqdataset/CreateBigQueryDatasetStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/CreateGcsBucketStep.java
service/src/main/java/bio/terra/workspace/service/workspace/model/WorkspaceConstants.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java

Created as draft to run integration tests.

PF-1085 use default location property from workspace when creating resources

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh

https://cromwell.readthedocs.io/en/stable/tutorials/FiveMinuteIntro/
Create a new cromwell directory and download the 81 (latest) cromwell jar in the directory.

[PF-1837] Install cromwell in post-startup.sh.

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java

Currently, we aren't retrying any steps in the flight to clone a GCS bucket. This leads to rare failure cases where the IAM permissions on the storage transfer SA don't propagate in time and the flight fails.

[PF-1860] Add retry rules for clone bucket flight

---

openapi/src/common/schemas.yaml
service/src/main/java/bio/terra/workspace/service/resource/model/CloningInstructions.java

Document enum, as I didn't understand it until @zloery explained it to me.

Document CloningInstructions enum

---

.github/workflows/linter-tests.yml
.github/workflows/nightly-tests.yml
.github/workflows/pr-integration.yml
.github/workflows/release-promotion-tests.yml
.github/workflows/tag-publish.yml
.github/workflows/test.yml

- From https://github.com/verily-src/terra-service-resource-buffer/pull/103
- keeping services updated and versions consistent across services

[PF-1909] Upgrade set up actions version from v2 -> v3 for Java 17

---

openapi/src/parts/controlled_azure_storage_container.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java

We need to be able to delete azure storage containers, this wires up the relevant API call.

[WOR-466] Wire up delete storage container API

---

integration/src/main/java/scripts/testscripts/CloneWorkspace.java
integration/src/main/java/scripts/testscripts/DeleteWorkspaceWithControlledResource.java
integration/src/main/java/scripts/testscripts/GetWorkspace.java
integration/src/main/java/scripts/testscripts/WorkspaceLifecycle.java
openapi/src/parts/workspace.yaml
service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
service/src/main/java/bio/terra/workspace/service/iam/model/SamConstants.java
service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
service/src/main/java/bio/terra/workspace/service/workspace/model/Workspace.java
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/WorkspaceApiControllerConnectedTest.java
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/WorkspaceApiControllerTest.java
service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java

Also deleted some redundant tests from WorkspaceApiControllerTest.java
Manual testing:
- Added second user as discover
- Called getWorkspace/getWorkspaceByUserFacingId with various combinations of requester, minimumHighestRole

[PF-1875] Add minimumHighestRole to GetWorkspace/GetWorkspaceByUserFacingId requests

---

service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java

I was in the neighborhood so.. couldn't resist.

PF-1956: Delete some deadcode in WorkspaecDaoTest and TODO

---

service/src/main/java/bio/terra/workspace/app/controller/shared/PropertiesUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtils.java
service/src/main/java/bio/terra/workspace/service/workspace/model/WorkspaceConstants.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledResourceFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/WorkspaceCloneUtilsTest.java

original gcs-bucket:
```
{
"resources": [
{
"metadata": {
"workspaceId": "d6765c27-93a3-4573-bc4c-9e509f080a95",
"resourceId": "0c737261-874b-4c02-8d86-d00843796aa3",
"name": "my-bucket",
"resourceType": "GCS_BUCKET",
"stewardshipType": "CONTROLLED",
"cloudPlatform": "GCP",
"cloningInstructions": "COPY_RESOURCE",
"controlledResourceMetadata": {
"accessScope": "SHARED_ACCESS",
"managedBy": "USER",
"privateResourceUser": {},
"privateResourceState": "NOT_APPLICABLE"
},
"resourceLineage": [],
"properties": [
{
"key": "TERRA_WORKSPACE_FOLDER_ID",
"value": "6b04f199-d895-4d7e-ab6f-1d0bd64818af"
}
]
},
"resourceAttributes": {
"gcpGcsBucket": {
"bucketName": "my-bucket-terra-wsm-t-swift-turnip-3879"
}
}
}
]
}
```
Cloned gcs-bucket:
```
{
"resources": [
{
"metadata": {
"workspaceId": …
```

PF-1965: When cloning resources, clear certain properties (a.k.a TERRA_WORKSPACE_FOLDER_ID)

---

openapi/src/parts/controlled_azure_disk.yaml
openapi/src/parts/controlled_azure_ip.yaml
openapi/src/parts/controlled_azure_network.yaml
openapi/src/parts/controlled_azure_relay_namespace.yaml
openapi/src/parts/controlled_azure_vm.yaml

https://broadworkbench.atlassian.net/browse/WOR-490

[WOR-490] Add 404 swagger response documentation to all azure resource deletion endpoints

---

openapi/src/parts/tps.yaml
service/src/main/java/bio/terra/workspace/amalgam/tps/TpsApiController.java
service/src/main/java/bio/terra/workspace/amalgam/tps/TpsApiDispatch.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/ClonePolicyAttributesStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/bucket/CloneControlledGcsBucketResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/dataset/CloneControlledGcpBigQueryDatasetResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneGcpWorkspaceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneControlledGcpBigQueryDatasetResourceFlightStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneGcsBucketResourceFlightStep.java
service/src/main/java/bio/terra/workspace/service/resource/exception/PolicyConflictException.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
service/src/test/java/bio/terra/workspace/amalgam/tps/TpsBasicPaoTest.java
service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java

This is take 2 on this PR. Since the TPS work to support replace went in, I went back and added the replace support. That let me finish up the UNDO of the clone policy step properly.

[PF-1972] Call TPS to merge policy on workspace clone and resource clone

---

service/src/main/java/bio/terra/workspace/amalgam/tps/TpsApiDispatch.java
service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
service/src/main/java/bio/terra/workspace/db/WorkspaceActivityLogDao.java
service/src/main/java/bio/terra/workspace/db/WorkspaceDao.java
service/src/main/java/bio/terra/workspace/service/workspace/AzureCloudContextService.java
service/src/main/java/bio/terra/workspace/service/workspace/GcpCloudContextService.java

For `terra workspace list`, it's helpful to show GCP project (or corresponding Azure details). So I'll try to figure out slowness, rather than implement `/brief`.

[PF-2104] Add @Traced to help debug list-workspace slowness

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/CustomGcpIamRoleMapping.java

https://broadworkbench.atlassian.net/browse/PF-2046

PF-2046: Add notebooks.instances.checkUpgradability

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/ControlledAzureVmResource.java

https://broadworkbench.atlassian.net/browse/TOAZ-254
related to https://github.com/DataBiosphere/terra-workspace-manager/pull/822

TOAZ-254 region is optional

---

README.md

The smallest PR

---

service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java
service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiControllerTest.java
service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatchTest.java
service/src/test/java/bio/terra/workspace/common/fixtures/AzureLandingZoneFixtures.java

Remove reference get LZ Ids obsolete API

[TOAZ-256] Remove Landing zone APIs based on LZ target.

---

openapi/src/parts/controlled_aws_bucket.yaml
openapi/src/parts/workspace.yaml
openapi/src/parts/workspace_cloudcontext.yaml

Add AWS context to WorkspaceDescription

[TERRA-208] Add AWS context to WorkspaceDescription

---

service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerTest.java
service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java

ControlledGcpResourceApiControllerGcsBucketTest#clone_copyNothing
When I'm running this test locally, the cloning finishes so fast that it returns 200 consistently for me.

PF-2258: fix flaky test ControlledGcpResourceApiControllerGcsBucketTest

---

service/src/main/java/bio/terra/workspace/app/controller/GlobalExceptionHandler.java

I copied the WSM global exception handler over to TPS. In review, several minor cleanup issues were found. This PR fixes those in WSM.

[PF-2266] Minor cleanup from TPS GEH review

---

openapi/src/resources/aws_sagemaker_notebook.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledAwsResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/ResourceValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakernotebook/ControlledAwsSageMakerNotebookAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakernotebook/ControlledAwsSageMakerNotebookHandler.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sagemakernotebook/ControlledAwsSageMakerNotebookResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/storagebucket/ControlledAwsBucketHandler.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookHandler.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/ControlledAiNotebookInstanceResource.java

- Add instanceType to AWS Notebook creation parameters / attributes
- Validate instanceId
- Use a common checkFieldNonNull function

AWS Notebook - Add instanceType, validate instanceId

---

integration/src/main/java/scripts/testscripts/WorkspaceLifecycle.java

https://github.com/DataBiosphere/terra-workspace-manager/compare/522b0a4f78c7b73c8e7d0dfe139d376786dcf467...b76148ce380f96e9e02c17262c8e7f4bc1cde468
I uncommented some test code that i thought would be harmless to re-enable.

PF-2246: Fix integration test in the verily-src/ repo downstream

---

service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java

Intermittent failures on testing notebook permissions. Adding retry so we wait for permission settings to propagate.

[PF-2282] Add retry to notebook permission retrieval

---

service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java

to be consistent with validateRequiredEntries and validateCommonEntries.

[no ticket] throw missingRequiredFieldException for getRequired

---

integration/src/main/resources/suites/FullIntegration.json

I spelled `json` as `Json` so testing failed.

[PF-2408] Typo in test suite spec

---

service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java

There is a race between the log being written and the flight finished and we assert the log.

PF-2368: deflake test

---

openapi/src/parts/resource.yaml
service/src/main/java/bio/terra/workspace/app/controller/ResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/WsmResourceService.java

Expose the getResource method in ResourceDao as a new resource endpoint

[PF-2422] Add getResource endpoint

---

openapi/src/parts/admin.yaml
service/src/main/java/bio/terra/workspace/app/StartupInitializer.java
service/src/main/java/bio/terra/workspace/app/controller/AdminApiController.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/flight/UpdateGcpControlledResourceRegionFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gcsbucket/ControlledGcsBucketResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/update/UpdateResourcesRegionStep.java
service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceTest.java

Still getting Json deserilization exception from getting the resources via typeReference and castByEnum.
Make this an endpoint so we don't print out a blob of deserilization failure everytime we start up wsm.

PF-2368: More on gcs bucket with underscore name.

---

openapi/src/parts/controlled_azure_batch_pool.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
service/src/main/java/bio/terra/workspace/common/utils/MapperUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/ControlledAzureBatchPoolResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/CreateAzureBatchPoolStep.java
service/src/test/java/bio/terra/workspace/common/utils/MapperUtilsTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/BatchPoolFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/batchpool/CreateAzureBatchPoolStepTest.java

Add 'metadata' to the batch pool create payload which is required by TES

TOAZ-316 Enrich payload for Batch pool creation with metadata

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/flight/RetrieveAzureResourcesRegionStep.java

manage group is sometimes not found.

PF-2368: Catch api error 404.

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh

https://github.com/DataBiosphere/terra-cli/pull/440

PF-2500: Add the new flag --include-private-key

---

openapi/src/parts/controlled_gcp_ai_notebook_instance.yaml
service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
service/src/main/java/bio/terra/workspace/common/utils/FlightBeanBag.java
service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/CreateAzureContextFlight.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/CreateDbAzureCloudContextStartStep.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/azure/ValidateMRGStep.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/gcp/CreateDbGcpCloudContextFinishStep.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/gcp/CreateDbGcpCloudContextStartStep.java
service/src/main/java/bio/terra/workspace/service/workspace/flight/gcp/CreateGcpContextFlightV2.java
service/src/main/java/bio/terra/workspace/service/workspace/model/CloudContextHolder.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/CreateGcpContextFlightV2Test.java

minor cleanup and refactor
No functional changes

[no ticket] minor cleanup and refactor

---

openapi/README.md
openapi/src/common/parameters.yaml
openapi/src/common/responses.yaml
openapi/src/common/responses_azure.yaml
openapi/src/common/schemas.yaml
openapi/src/common/schemas_azure.yaml
openapi/src/parts/workspace_cloudcontext.yaml
service/src/main/java/bio/terra/workspace/service/workspace/model/AzureCloudContext.java
service/src/main/java/bio/terra/workspace/service/workspace/model/GcpCloudContext.java

Move cloud-specific (Azure) schema / parameter definitions to separate file
This is in preparation for AWS related changes coming in with similar separate files

[TERRA-314] Move cloud-specific schema / parameter definitions to separate file

---

integration/src/main/java/scripts/testscripts/CloneWorkspace.java
integration/src/main/java/scripts/utils/ClientTestUtils.java
integration/src/main/java/scripts/utils/FlexResourceUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/flexibleresource/CloneControlledFlexibleResourceFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/CloneAllResourcesFlight.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/FindResourcesToCloneStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/clone/workspace/LaunchCloneControlledFlexibleResourceFlightStep.java

All the cloning logic is done from #1133 . We just need to put it in the clone workspace flight.

[PF-2626] Include flex resources in workspace clone flight.

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh

Reverts DataBiosphere/terra-workspace-manager#1097

PF-2628: Revert "PF-2509: convert https url to git url"

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/ainotebook/post-startup.sh

Fixes the error noted in https://broadworkbench.atlassian.net/browse/PF-2703.

Correct quoting of terra tab completion command in post-startup.sh

---

service/src/main/java/bio/terra/workspace/service/resource/AwsResourceValidationUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3storageFolder/ControlledAwsS3StorageFolderResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3storageFolder/ValidateAwsS3StorageFolderCreateStep.java
service/src/test/java/bio/terra/workspace/service/resource/AwsResourceValidationUtilsTest.java

- Update Uniqueness check for S3 storage folder names (bucket + prefix)
- Disallow special characters from prefix names, add Unit test

[TERRA-519] Update Uniqueness check for S3 storage folder names

---

service/src/main/java/bio/terra/workspace/service/workspace/flight/create/cloudcontext/CreateCloudContextFlight.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/CreateGcpContextFlightTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/DeleteGcpContextFlightTest.java

Several test failures in the "connectedPlus" tests handling GCP failures.

[PF-2749] Fix test failures from the context state merge

---

service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
service/src/main/java/bio/terra/workspace/service/workspace/model/AwsCloudContext.java

Change - only compare relevant fields in cloud context for sanity check

[TERRA-566] Update getLandingZone

---

service/src/main/resources/application.yml

We need these tables in data export for long term storage

[WOR-1012] Add table names for azure protected data landing zone LTS

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/ControlledResourceMetadataManager.java

The code is forbidding reading resources that are not in READY state.
This change allows read regardless of state.

[PF-2801] Allow read operations to proceed regardless of resource state

---

service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ControlledGcpResourceApiControllerConnectedTest.java
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/DO_NOT_PUT_TESTS_HERE.md
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/FolderApiControllerTest.java
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ReferencedGcpResourceControllerTest.java
service/src/test/java/bio/terra/workspace/app/configuration/external/controller/ResourceApiControllerConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerAiNotebookConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerBqDatasetConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGcsBucketConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqDatasetConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerBqTableConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerDataRepoSnapshotConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsBucketConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGcsObjectConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedGcpResourceControllerGitRepoConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/ReferencedResourceCloneConnectedTest.java
service/src/test/java/bio/terra/workspace/app/controller/TempGrantConnectedTest.java
service/src/test/java/bio/terra/workspace/common/utils/AzureUtilsTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDisabledTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/storage/StorageAccountKeyProviderUnitTest.java

- old files meant to be removed as part of https://broadworkbench.atlassian.net/browse/PF-2030
- Rename some of the connected Test classes to reflect the type of tests

[PF-2030] Remove old / deprecated test files; rename tests to include 'connected' in name

---

.github/workflows/consumer_contract_tests.yml
service/src/test/java/bio/terra/workspace/pact/ProfileApiTest.java

[WOR-939](https://broadworkbench.atlassian.net/browse/WOR-939)
* adds github action to publish pacts
* update WSM's consumer pacts to work with BPM
[WOR-939]: https://broadworkbench.atlassian.net/browse/WOR-939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WOR-939 publish WSM pacts to pact broker

---

service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java

Testing - 
- create folder, add subfolders and files
- call delete API, all subfolders deleted

[BENCH-659] Fix aws folder deletion

---

service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java

The test makes an application resource that the workspace owner cannot delete, so the cleanup fails.
I moved the setup of the app token and the cleanup of the resource into the setup/teardown code.

[PF-2838] Clean up application resource before workspace delete

---

.github/workflows/full-service-tests.yml
service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/CreateAwsS3StorageFolderStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/DeleteAwsS3StorageFolderStep.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java
service/src/test/java/bio/terra/workspace/common/fixtures/WorkspaceFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/AwsResourceValidationUtilsTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderHandlerTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResourceTest.java
service/src/test/java/bio/terra/workspace/service/workspace/AwsCloudContextUnitTest.java

[BENCH-470] S3 Storage Folder Unit tests

---

service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
service/src/test/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiControllerGceInstanceConnectedTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/ControlledResourceServiceGceInstanceConnectedTest.java

Should've merged main in first!

[PF-2866] Fix compilation errors

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/CreateAwsS3StorageFolderStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/DeleteAwsS3StorageFolderStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ValidateAwsS3StorageFolderCreateStep.java
service/src/test/java/bio/terra/workspace/common/utils/TestUtils.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java

- Split do & undo to separate tests
- update comments
- remove repeated / duplicate undo-asserts

[BENCH-470] Minor updates to Aws S3 tests

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStepTest.java

https://broadworkbench.atlassian.net/browse/WOR-1085
centralized exception handling for dealing with k8s and retry database creation pod failures

WOR-1085 retries for db creation failure

---

service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateAwsSageMakerNotebookStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/DeleteAwsSageMakerNotebookStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ValidateAwsSageMakerNotebookDeleteStep.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/AwsSageMakerNotebookStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookHandlerTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResourceTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStepTest.java

- Extract common code in AWS Sagemaker implementation to util functions, make it more testable
- Minor fix in stop.undo
- Add unit test for sagemaker ops

[BENCH-471] AWS Sagemaker Notebook unit tests

---

service/src/test/java/bio/terra/workspace/common/BaseAwsConnectedTest.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java
service/src/test/java/bio/terra/workspace/common/utils/MockMvcUtils.java
service/src/test/java/bio/terra/workspace/common/utils/MvcAwsApi.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderHandlerTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResourceTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/aws/CreateAwsWorkspaceFlightTest.java

- AWS S3 Storage folder Connected Test
- Add resource creation to cloud context connected test

[BENCH-715] AWS S3 Storage folder Connected Test

---

README.md
service/gradle/testing.gradle
service/src/main/java/bio/terra/workspace/common/utils/AwsUtils.java
service/src/test/java/bio/terra/workspace/common/BaseAwsConnectedTest.java
service/src/test/java/bio/terra/workspace/common/fixtures/ControlledAwsResourceFixtures.java
service/src/test/java/bio/terra/workspace/common/utils/AwsUtilsTest.java
service/src/test/java/bio/terra/workspace/common/utils/MvcAwsApi.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/ControlledAwsS3StorageFolderResourceTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/AwsSageMakerNotebookFlightMiscTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/AwsSageMakerNotebookFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/BaseAwsSageMakerNotebookStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookHandlerTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/ControlledAwsSageMakerNotebookResourceTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/CreateDeleteAwsSageMakerNotebookStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/StopAwsSageMakerNotebookStepTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/aws/CreateAwsWorkspaceFlightTest.java

- AWS Sagemaker notebook connected & connectedPlus tests
- Fix build warning in AWS Sagemaker UT
Connected test (primary ops)
ConnectedPlus test (force delete + undo, create undo) 
Note - function name fixed and combined post this run sample

[BENCH-716] AWS Sagemaker notebook connected / connectedPlus tests

---

service/src/main/java/bio/terra/workspace/service/iam/SamService.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/flight/delete/DeleteSamResourceStep.java
service/src/test/java/bio/terra/workspace/common/BaseTest.java
service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/RemoveUserFromWorkspaceFlightTest.java

Remove chatty logging as well.

[PF-2884] disable flaky test

---

service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetPetManagedIdentityStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetWorkspaceManagedIdentityStepTest.java

for some reason github did not add this to the original PR... computers!

enhance test

---

azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseDao.java
azureDatabaseUtils/src/main/resources/application.yml
azureDatabaseUtils/src/test/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseDaoTest.java

https://broadworkbench.atlassian.net/browse/WOR-1152

WOR-1152 make create db idempotent

---

service/src/test/java/bio/terra/workspace/service/workspace/flight/gcp/WorkspaceDeleteFlightConnectedTest.java

Autowire SamService in WorkspaceDeleteFlightConnectedTest
samService is not directly used in the test. Autowire it to ensure it is ready before tests
Add this to debug flaky tests
Reason: this test is flaky downstream. logs hint at samservice not being ready during the first call.
Bug BENCH-845 to be kept open for debugging

[BENCH-845] Autowire SamService in WorkspaceDeleteFlightConnectedTest

---

service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/s3StorageFolder/AwsS3StorageFolderFlightTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/aws/sageMakerNotebook/AwsSageMakerNotebookFlightMiscTest.java

Fix AWS connected test - final createResponseStep cannot fail, hence fail the create step

[BENCH-888] Fix AWS connected test

---

azureDatabaseUtils/README.md
azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/CreateDatabaseWithDbRoleRunner.java
azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseDao.java
azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseRunner.java
azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseService.java
azureDatabaseUtils/src/main/java/bio/terra/workspace/azureDatabaseUtils/validation/Validator.java
azureDatabaseUtils/src/test/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseDaoTest.java
azureDatabaseUtils/src/test/java/bio/terra/workspace/azureDatabaseUtils/create/CreateDatabaseServiceTest.java
azureDatabaseUtils/src/test/java/bio/terra/workspace/azureDatabaseUtils/validation/ValidatorTest.java
openapi/src/parts/controlled_azure_database.yaml
openapi/src/resources/azure_database.yaml
service/src/main/java/bio/terra/workspace/app/controller/ControlledAzureResourceApiController.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseGuardStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseAttributes.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseHandler.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ValidateDatabaseOwnerStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetManagedIdentityStep.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/AzureDatabaseGuardStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseHandlerTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResourceTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/GetAzureDatabaseStepTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ValidateDatabaseOwnerStepTest.java

https://broadworkbench.atlassian.net/browse/WOR-1161
please see design doc linked from ticket

WOR-1161 split level db roles

---

service/src/main/java/bio/terra/workspace/service/policy/flight/MergeGroupsStep.java

The step to merge groups was calling Sam for every clone, whether the groups had changed or not. We only need to call Sam if groups change.
This was causing some connectedPlus tests to fail.

PF-2713: Only call Sam to add groups if groups have changed.

---

service/src/main/java/bio/terra/workspace/service/policy/flight/MergeGroupsStep.java

The problem was that we were trying to get the original group list from tps but by the time this step is called, tps is already updated so the current group list == merged group list. Both lists are already stored in the flight, so the solution is to get the original list from there rather than querying tps.
I believe this happened because originally we had the steps in a different order, so querying tps for the original list worked.
Still thinking how to test this. We do have coverage for the tps updates and merge logic. We need to add in validating the actual Sam groups but we don't do anything like that currently.

PF-2957: Group policy not enforced after adding from a data collection

---

service/src/main/java/bio/terra/workspace/app/controller/WorkspaceApiController.java
service/src/main/java/bio/terra/workspace/app/controller/WorkspaceV2Api.java

- Fetch user email from sam using userRequest
- Check if aws is enabled for the user during clone workspace

[BENCH-970] Fetch user email from sam using userRequest

---

service/src/main/java/bio/terra/workspace/db/ResourceDao.java
service/src/main/java/bio/terra/workspace/service/workspace/AzureCloudContextService.java
service/src/test/java/bio/terra/workspace/db/ResourceDaoTest.java

https://broadworkbench.atlassian.net/browse/WOR-1249

delete k8s namespaces first

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java

fixes NPE in the [last PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/1470)

WOR-1250 fix npe

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java

https://broadworkbench.atlassian.net/browse/WOR-1265

Actually retry

---

service/src/test/java/bio/terra/workspace/service/workspace/WorkspaceServiceTest.java

The service account in code didn't match the service account in a Verily test environment.

Use service account from config in tests

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/CreateAzureDatabaseStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/DeleteAzureDatabaseStep.java

https://broadworkbench.atlassian.net/browse/WOR-1237
Postgres server name used twice instead of database name.

Fix logging during postgres database deletion

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/database/ControlledAzureDatabaseResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResource.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/DeleteFederatedCredentialStep.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/managedIdentity/GetFederatedIdentityStep.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/AzureDatabaseConnectedTest.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/kubernetesNamespace/ControlledAzureKubernetesNamespaceResourceTest.java

https://broadworkbench.atlassian.net/browse/WOR-1277

WOR-1277 delete fed creds when deleting k8s namespace

---

service/src/main/java/bio/terra/workspace/service/resource/GcpFlightExceptionUtils.java
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/gceinstance/CreateGceInstanceStep.java

Return errors instead of dropping into a dismal failure.

[BENCH-1264] No retries on more errors creating GCE instance

---

service/src/test/java/bio/terra/workspace/pact/WdsContractVerificationTest.java

This adds pacts to cover additional WDS <-> WSM interactions.
It is paired with consumer changes in https://github.com/DataBiosphere/terra-workspace-data-service/pull/414

AJ-1451: More WDS pacts

---

service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/EnableVmLoggingStep.java

https://broadworkbench.atlassian.net/browse/IA-4718

IA-4623 retry EnableVmLoggingStep

---

service/src/main/java/bio/terra/workspace/service/iam/SamService.java

I was going through the backlog and thought it was easier to just do this then discuss it. :)

Remove incorrect VisibleForTesting tag (WOR-1382).

---

service/gradle/dependencies.gradle
service/src/main/java/bio/terra/workspace/service/policy/TpsApiDispatch.java
service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
service/src/test/java/bio/terra/workspace/app/controller/FolderApiControllerTest.java
service/src/test/java/bio/terra/workspace/app/controller/WorkspaceApiControllerTest.java

https://broadworkbench.atlassian.net/browse/WOR-1419

WOR-1419 use new listPao TPS api

---

integration/build.gradle

This is https://github.com/DataBiosphere/terra-workspace-manager/pull/1582.

guava integration library upgrade (WOR-1416).

---

README.md
service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/EnableVmLoggingStep.java
service/src/test/java/bio/terra/workspace/service/resource/controlled/cloud/azure/vm/EnableVmLoggingStepTest.java

Also updates README with required `jq` installation.

test(IA-4623): add tests for AzureMonitorLinuxAgent retry logic

---

buildSrc/build.gradle

Originally https://github.com/DataBiosphere/terra-workspace-manager/pull/1595

Update jacoco (WOR-1416).

---

.github/dependabot.yml

[NO TICKET] Feedback from grouping dependabot updates.

---

service/gradle/dependencies.gradle
service/src/main/resources/application.yml
service/src/test/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatchTest.java

Ticket: [WOR-1410](https://broadworkbench.atlassian.net/browse/WOR-1410)
* Bump LZS version
* Add regional default SKUs for Azure landing zones
[WOR-1410]: https://broadworkbench.atlassian.net/browse/WOR-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1410] Add regional landing zone config

---

openapi/src/parts/azure_landing_zone.yaml
service/gradle/dependencies.gradle
service/src/main/java/bio/terra/workspace/amalgam/landingzone/azure/LandingZoneApiDispatch.java

Ticket: [WOR-1436](https://broadworkbench.atlassian.net/browse/WOR-1436)
* Update WSM with new LZS version
* Add region to API response objects
[WOR-1436]: https://broadworkbench.atlassian.net/browse/WOR-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WOR-1436 pull in region changes from LZS

---

service/gradle/dependencies.gradle

Update the landing zone version to pick up the fix for [WOR-1478](https://broadworkbench.atlassian.net/browse/WOR-1478)
[WOR-1478]: https://broadworkbench.atlassian.net/browse/WOR-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WOR-1478: update landing zone version

---

service/gradle/dependencies.gradle

[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1520)
We should do the same thing as we did in BPM and remove this constraint and bump the sam lib.

Update sam client, remove json lib constraint

---

azureDatabaseUtils/gradle/dependencies.gradle
service/gradle/dependencies.gradle

Related ticket: https://broadworkbench.atlassian.net/browse/WOR-1530
Pull in the latest PG driver to mitigate a security vulnerability.

[WOR-1530] Pull in latest pg driver

---

service/src/main/java/bio/terra/workspace/common/utils/FlightUtils.java

Small follow-up PR from https://github.com/DataBiosphere/terra-workspace-manager/pull/1688/, now that TCL has been [updated](https://github.com/DataBiosphere/terra-workspace-manager/pull/1686/files#diff-fac97ffc118e8fd12491b0786763b2700eb8fea8f67769b0070e4117f5bd6adcR37).

Switch to Stairway isActive method to avoid code duplication (WOR-1591).

---

.github/workflows/consumer_contract_tests.yml

https://broadworkbench.atlassian.net/browse/WOR-1458
Mirrors [the changes made to BPM](https://github.com/DataBiosphere/terra-billing-profile-manager/pull/445/files)

WOR-1458: update contract tests to publish all pacts

---

.github/workflows/verify_consumer_pacts.yaml
service/dependencies.gradle
service/src/test/java/bio/terra/workspace/pact/TpsApiTest.java

[Ticket](https://broadworkbench.atlassian.net/browse/WOR-1666)
The Terra AWS resource lib 0.6.3 has an updated avro version which mitigates the CVE, pull it in.
Dep before: ```org.apache.avro:avro:1.11.2```
Dep after: ```org.apache.avro:avro:1.11.3```

Pull in updated aws resource discovery lib with avro fix

---

service/src/main/resources/application.yml

Ticket: https://broadworkbench.atlassian.net/browse/WOR-1669

Add Australia East to Azure regions (WOR-1669).

---

.github/workflows/full-integration-tests.yml
.github/workflows/full-service-tests.yml
.github/workflows/test.yml
scripts/write-config.sh

We don't need a BEE for TPS, we can just use the dev instance.

Switch away from TPS in a bee to TPS in dev

---

service/src/main/java/bio/terra/workspace/service/iam/SamService.java

https://broadworkbench.atlassian.net/browse/WOR-1722

WOR-1722 fix isApplicationEnabledInSam

---

service/src/test/java/bio/terra/workspace/pact/ProfileApiTest.java

https://broadworkbench.atlassian.net/browse/WOR-1769
update test to use new state

WOR-1769 use state in billingProfileUnAvailable

---

service/src/main/java/bio/terra/workspace/app/controller/GlobalExceptionHandler.java

It's hard to debug POST requests that are missing fields with the default error handling -- WSM gives back a generic ```  "message": "Request could not be parsed or was invalid: MethodArgumentNotValidException. Ensure that all types are correct and that enums have valid values.",``` msg.
With this modification the error message looks like this:
```
{
"message": "Request could not be parsed or was invalid: MethodArgumentNotValidException. Ensure that all types are correct and that enums have valid values.",
"statusCode": 400,
"causes": [
"jobControl.id: must not be null"
]
}```

[WOR-1798] Indicate which fields are missing when giving back a 400 on MethodArgumentNotValidException

---

.github/workflows/full-service-tests.yml
.github/workflows/test.yml

Ticket: https://broadworkbench.atlassian.net/browse/WOR-1813

Disable Azure connected tests (WOR-1813).

---

integration/build.gradle

Replicates #1814, but as me instead of as dependabot.

CORE-69: update google dataproc library

---

integration/build.gradle
service/dependencies.gradle

* update LZS libs to adopt the changes from https://github.com/DataBiosphere/terra-landing-zone-service/pull/547
* update the Sam client to latest (which also happened in https://github.com/DataBiosphere/terra-landing-zone-service/pull/547)

CORE-391: update Sam and LZ libs
